### ISSUE TITLE
xt_ndpi: kernel module version missmatch.

### ISSUE THREAD

**Issue by tacitus-def** [vel21ripn/nDPI#10]
After installing xt_ndpi module via DKMS I can't create rules for iptables and get error: iptables v1.6.0: xt_ndpi: kernel module version missmatch.

OS: Ubuntu 16.04 Xenial 64bit
Kernel: Linux server 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vel21ripn** [comment]
Needed recompile and reinstall libxt_ndpi.so

**Comment by tacitus-def** [comment]
I get same error.

**Comment by vel21ripn** [comment]
compare
```
stribgs libxt_ndpi.so | grep 1.7.0-netfilter
```
and
```
grep 1.7.0-netfilter /proc/net/xt_ndpi/proto
```

**Comment by tacitus-def** [comment]
`# strings /usr/src/xt_ndpi-1.7.0/ndpi-netfilter/ipt/libxt_ndpi.so | grep 1.7.0-netfilter`
`1.7.0-netfilter-222-edf7a3b`

`# grep 1.7.0-netfilter /proc/net/xt_ndpi/proto`
`#id     mark ~mask     name   # count #version 1.7.0-netfilter-222-edf7a3b`

`# iptables -m ndpi -h`
`iptables v1.6.0: xt_ndpi: kernel module version missmatch.`
`Try `iptables -h' or 'iptables --help' for more information.`

**Comment by tacitus-def** [comment]
`cat /proc/net/xt_ndpi/proto`

http://pastebin.com/JtgMSPZn

**Comment by vel21ripn** [comment]
iptables not use libxt_ndpi.so from /usr/src/xt_ndpi-1.7.0/ndpi-netfilter/ipt/
Check in
```
pkg-config --variable=xtlibdir xtables
```

**Comment by tacitus-def** [comment]
I copy libxt_ndpi.so to /lib/xtables/ and it works! Thanks!
