### ISSUE TITLE
How to increase number of protocols under the proc file system

### ISSUE THREAD

**Issue by chirayu-patel** [vel21ripn/nDPI#100]
root@OpenWrt:/proc/5237/net/xt_ndpi# cat /proc/net/xt_ndpi/proto | wc
      321      1852     15881

So in addition to the already created protocols , only max 321 protocols can be defined ??

If yes, Is it possible to increase this limit ??

**Comment by vel21ripn** [comment]
Yes.
We must change NDPI_NUM_BITS definition.
