### ISSUE TITLE
How to work with redirect?

### ISSUE THREAD

**Issue by Zxilly** [vel21ripn/nDPI#102]
Hello,@vel21ripn.
I'm trying to using ndpi to redirect all http packet (not only on tcp/80) to participant port on my router.
I'm using these iptable rules
```iptables
iptables -t nat -N http_ua_drop

iptables -t mangle -A PREROUTING -m ndpi --proto http -j MARK --set-mark 17
iptables -t mangle -A POSTROUTING -m ndpi --proto http -j MARK --set-mark 17

iptables -t nat -A http_ua_drop -d 0.0.0.0/8 -j RETURN
iptables -t nat -A http_ua_drop -d 127.0.0.0/8 -j RETURN
iptables -t nat -A http_ua_drop -d 192.168.0.0/16 -j RETURN
iptables -t nat -A http_ua_drop -p tcp -j REDIRECT --to-port 8118

iptables -t nat -A PREROUTING -m mark --mark 17 -j http_ua_drop 
```
However,I noticed it only work for the http on port/80.NDPI didn't detect the http flow on tcp/8118.
This is the limited of NDPI,or I write the wrong rules?
Any suggestion will be help,thanks a lot.

**Comment by vel21ripn** [comment]
This is wrong ideas.
Only the first packet of the connection gets into "NAT", which is always "unknown protocol".
http protocol is defined only after the fourth packet.

**Comment by Zxilly** [comment]
> This is wrong ideas.
> Only the first packet of the connection gets into "NAT", which is always "unknown protocol".
> http protocol is defined only after the fourth packet.

So how could i set the iptables?Or I can not implement it with NDPI?
Or maybe I should use CONNMARK to track the whole connection?
@vel21ripn

**Comment by Zxilly** [comment]
I read some document about TCP,so it means we can `ONLY` recognize what a connection is and broke it later,but not redirect it?
However,I actually know an appliction,which can redirect any http flow from any port.How it implement really annoyed me.

**Comment by vel21ripn** [comment]
> I read some document about TCP,so it means we can ONLY recognize what a connection is and broke it later,but not redirect it?

Yes.

You can remember the address and port through ipset, and the next connection to this address and port can be redirected without using nDPI data.
