### ISSUE TITLE
CentOS 8  build error: ‘nf_ct_destroy’ undeclared

### ISSUE THREAD

**Issue by netcons** [vel21ripn/nDPI#103]
Thanks for your work with this Vitaly !
Any ideas on what I am missing while building ndpi-netfilter from flow_info-3.2 on CentOS 8 ?

**Rebuilt Kernel with :**
_rpm -Uvh https://vault.centos.org/8.3.2011/BaseOS/Source/SPackages/kernel-4.18.0-240.1.1.el8_3.src.rpm_

_cd /root/rpmbuild/SOURCES
sed -i "/CONFIG_NF_CONNTRACK_IRC/ a\CONFIG_NF_CONNTRACK_LABELS=y" kernel-x86_64.config
sed -i "s/^# CONFIG_UNUSED_SYMBOLS .*$/CONFIG_UNUSED_SYMBOLS=y/" kernel-x86_64.config_

_cd /root/rpmbuild/SPECS_
_sed -i "s/^# define buildid .*$/%define buildid \_ndpi/" kernel.spec_

_rpmbuild -bb kernel.spec --without kabichk_

**Installed the kernel, rebooted and confirmed settings in /boot/config-4.18.0-240.1.1.el8_ndpi.x86_64
and in /usr/src/kernels/4.18.0-240.1.1.el8_ndpi.x86_64/.config :**
_CONFIG_NF_CONNTRACK= y
CONFIG_NF_CONNTRACK_LABELS=y
CONFIG_NETFILTER_XT_MATCH_CONNLABEL=m
CONFIG_UNUSED_SYMBOLS=y_

**ndpi_netfilter make error :**
_In file included from ./include/linux/rbtree.h:34,
                 from ./include/linux/mm_types.h:10,
                 from ./include/linux/mmzone.h:23,
                 from ./include/linux/gfp.h:6,
                 from ./include/linux/umh.h:4,
                 from ./include/linux/kmod.h:22,
                 from ./include/linux/module.h:13,
                 from /usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c:25:
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c: In function ‘replace_nf_destroy’:
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c:2734:49: error: ‘nf_ct_destroy’ undeclared (first use in this function); did you mean ‘ndpi_mt_destroy’? 
ndpi_nf_ct_destroy = rcu_dereference_protected(nf_ct_destroy,lockdep_is_held(&ndpi_hook_mutex));_

**Comment by vel21ripn** [comment]
```
CONFIG_NF_CONNTRACK= y
```

Is it a typo, that there is a space between '=' and 'y'?

**Comment by vel21ripn** [comment]
I can understand what kind of mutant this linux4.18.0-240.1.1.el8_3 is!
Judging by the code, it is close to vanilla 5.x kernels.
Try replacing lines in main.c 167 and 846
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,0)
```
on
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,18,0)
```
Replace lines in main.c 2748 and 2771 
```
#if LINUX_VERSION_CODE <KERNEL_VERSION (4,19,0)
```
on
```
#if LINUX_VERSION_CODE <KERNEL_VERSION (4,18,0)
```

**Comment by netcons** [comment]
Apologies, yes, the space was a typo.

**The line numbers seem different, but applied the change :**
_grep -n  "4,19,0" main.c_

_167:#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,0)_
_846:#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,19,0)_
_2733:#if LINUX_VERSION_CODE < KERNEL_VERSION(4,19,0)_
_2756:#if LINUX_VERSION_CODE < KERNEL_VERSION(4,19,0)_

_sed -i "s/4,19,0/4,18,0/g" main.c_

**new make error :**
  _CC [M]  /usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.o
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c: In function ‘nflow_put_str’:
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c:2055:44: error: macro "access_ok" passed 3 arguments, but takes                                                                          just 2
  if (!(ACCESS_OK(VERIFY_WRITE, buf+(*p), rl) &&
                                            ^
In file included from /usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c:190:
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/ndpi_main_common.h:22:26: error: ‘access_ok’ undeclared (first use in                                                                          this function)
 #define ACCESS_OK(a,b,c) access_ok(a,b,c)
                          ^~~~~~~~~
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c:2055:8: note: in expansion of macro ‘ACCESS_OK’
  if (!(ACCESS_OK(VERIFY_WRITE, buf+(*p), rl) &&
        ^~~~~~~~~
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/ndpi_main_common.h:22:26: note: each undeclared identifier is reported                                                                          only once for each function it appears in
 #define ACCESS_OK(a,b,c) access_ok(a,b,c)
                          ^~~~~~~~~
/usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.c:2055:8: note: in expansion of macro ‘ACCESS_OK’
  if (!(ACCESS_OK(VERIFY_WRITE, buf+(*p), rl) &&
        ^~~~~~~~~
make[3]: *** [scripts/Makefile.build:313: /usr/src/ndpi-flow_info-3.2/ndpi-netfilter/src/main.o] Error 1_

**Comment by netcons** [comment]
**Got it working on Centos 8 with Kernel 5 :**

_rpm -Uvh https://elrepo.org/linux/kernel/el8/SRPMS/kernel-ml-5.10.4-1.el8.elrepo.nosrc.rpm_

_cd /root/rpmbuild/SOURCES_

_wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.4.tar.xz_
_sed -i "s/^# CONFIG_UNUSED_SYMBOLS .*$/CONFIG_UNUSED_SYMBOLS=y/" config-5.10.4-x86_64_

_cd /root/rpmbuild/SPECS_

_sed -i "s/^# define buildid .*$/%define buildid .ndpi/" kernel-ml-5.10.spec_
_rpmbuild -bb kernel-ml-5.10.spec --without kabichk_

_cd /root/rpmbuild/RPMS/x86_64_

_dnf install kernel-ml-5.10.4-1.el8.ndpi.x86_64.rpm \\
kernel-ml-core-5.10.4-1.el8.ndpi.x86_64.rpm \\
kernel-ml-modules-5.10.4-1.el8.ndpi.x86_64.rpm \\
kernel-ml-devel-5.10.4-1.el8.ndpi.x86_64.rpm_

_dnf install kernel-ml-headers-5.10.4-1.el8.ndpi.x86_64.rpm --allowerasing_
_reboot_

**If you still wish to pursue a solution for Kernel 4.18, many thanks.**

**Comment by netcons** [comment]
Here is the DKMS config I used :

_dkms.conf_ 
```
PACKAGE_VERSION="3.2"

PACKAGE_NAME="ndpi-netfilter"
BDIR="$dkms_tree/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
PRE_BUILD="dkms-prebuild.sh"
CLEAN="make clean"
MAKE="make -C ndpi-netfilter; find ${BDIR} -name '*.ko' -exec mv -v {} ${BDIR} \;"

AUTOINSTALL="yes"

BUILT_MODULE_LOCATION[0]=""
BUILT_MODULE_NAME[0]="xt_ndpi"
DEST_MODULE_LOCATION[0]="/extra"

POST_INSTALL="dkms-postinstall.sh"
POST_REMOVE="dkms-postremove.sh"
```
_dkms-prebuild.sh_
```
#!/bin/sh
./autogen.sh
make -C src/lib ndpi_network_list.c.inc
```
_dkms-postinstall.sh_
```
#!/bin/sh
make -C ndpi-netfilter/ipt
make -C ndpi-netfilter/ipt install
```
_dkms-postremove.sh_
```
#!/bin/sh
make -C ndpi-netfilter/ipt uninstall
```
_Added to /ndpi-netfilter/ipt/Makefile_
```
uninstall:
        rm $(DESTDIR)$(XTBL)/libxt_ndpi.so
```
_Actual dkms :_
```
dkms add -m ndpi-netfilter -v 3.2
dkms build -m ndpi-netfilter -v 3.2
dkms install -m ndpi-netfilter -v 3.2
&
dkms remove -m ndpi-netfilter/3.2 --all
```

**Comment by elico** [comment]
Was this resolved? I don't understand..

**Comment by elico** [comment]
?

**Comment by roltd** [comment]
> Here is the DKMS config I used :
...
...

This is working, thank you!

**Comment by elico** [comment]
Can someone post a spec or SRPM?
What I have seen is for 7:
https://github.com/NethServer/nethserver-ndpi

I have tried to build for Oracle Linux 7 and 8 but I do not have the devel packages and I assume it's because these are in ULN repository.

I have not tried on CentOS 8 yet.
I am working with Debian buster in production and it is very stable for a very long time now.

**Comment by netcons** [comment]
CentOS 8 RPM :

_updated dkms.conf :_
```
PACKAGE_VERSION="3.2"

PACKAGE_NAME="ndpi-netfilter"
BDIR="$dkms_tree/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
PRE_BUILD="dkms-prebuild.sh"
CLEAN="make clean"
MAKE="make -C ndpi-netfilter; find ${BDIR} -name '*.ko' -exec mv -v {} ${BDIR} \;; make -C ndpi-netfilter/ipt; make -C ndpi-netfilter/ipt install "

AUTOINSTALL="yes"

BUILT_MODULE_LOCATION[0]=""
BUILT_MODULE_NAME[0]="xt_ndpi"
DEST_MODULE_LOCATION[0]="/extra"

POST_REMOVE="dkms-postremove.sh"
```

_dkms-prebuild.sh_
```
#!/bin/bash
./autogen.sh
make -C src/lib ndpi_network_list.c.inc
```

_dkms-postremove.sh_
```
#!/bin/sh
make -C ndpi-netfilter/ipt uninstall
```

_Fix Makefile :_
```
echo -e "uninstall:
\trm \$(DESTDIR)\$(XTBL)/libxt_ndpi.so" ./ndpi-netfilter/ipt/Makefile
```

DKMS and RPM Build :
```
dkms add -m ndpi-netfilter -v 3.2
dkms build -m ndpi-netfilter -v 3.2

sed -i "s/\/usr\/bin\/env python/\/usr\/libexec\/platform-python/" /usr/src/ndpi-netfilter-3.2/example/ndpi2timeline.py
cp /etc/dkms/template-dkms-mkrpm.spec ./ndpi-netfilter-dkms-mkrpm.spec
dkms mkrpm -m ndpi-netfilter -v 3.2
```
