### ISSUE TITLE
Facing issues with the new NSS firmware.

### ISSUE THREAD

**Issue by chirayu-patel** [vel21ripn/nDPI#104]
Qualcomm in its newer chipsets has come up with an offloading feature with the help of NSS. This diagram will explain it nicely.

![image](https://user-images.githubusercontent.com/1511739/104115951-8f297700-533a-11eb-858d-b9dacaa1134b.png)

For blocking youtube, I placed the drop rule in each and every chain of every table possible. From what I observed, the youtube traffic does get dropped momentraily, when I open youtube.com - I even get the page that says not reachable and then all of a sudden the traffic starts.

As per the above diagram , it could be that NSS would have taken over and now netfliter has no idea about it.

What I am failing to understand is that even if I am dropping traffic in prerouting chain, why is it still being taken over by NSS..

Any idea here.. ?

**Comment by vel21ripn** [comment]
Do not use "NSS" if you need to use complex filtering options.
Until iptables/nftables has the ability to enable/disable NSS processing of the connection, we will not get anything good from NSS.
NSS has its own limited scope - simple filtering at the L2/L3/L4 level. As soon as you need to filter data at the L7 level, it immediately turns from a useful feature of NSS into a problem.

**Comment by chirayu-patel** [comment]
Ok.. I understand..

**Comment by chirayu-patel** [comment]
Sorry to reopen this , but I have had a lengthy discussion on one of the NSS forums. I had forwarded your reply to one of the guys I was having discussion with.

This is what he replied -

"The nDPI folks is correct with their explanation of the NSS scope, being mainly operating in L2/L3/L4. So I think for NSS to work with nDPI, we need to do the following  - 
1) delay ECM's trigger to NSS, 
2) When nDPI decides to drop any connection, said connection has to be flushed from netfilter's connection tracking database. 

If such a scenario can be achieved, NSS can be used with nDPI. I imagine nDPI would have to create a kernel module to flush the netfilter connection, instead of solely being at the L7 layer."

For the point (1) ---->
There is already a patch available in one of the recent versions that lets you delay the packets as to when the NSS should take over . This is the patch right here -

https://source.codeaurora.org/quic/qsdk/oss/lklm/qca-nss-ecm/commit/?h=NHSS.QSDK.11.3&id=1de80f85fb49f9d90b20916e848bc3a4754b08fb

It has these controls - 
Enable different features by setting the accel_delay_pkts
- 0 means feature is disabled
- 1 means  delay until both direction is seen
- <N> means delay until N number of packets are seen.

**My question here - What number of packets would you recommend here before nDPI decides on the signature of the connection ?**

For the Point (2) ------->
Are we already doing this right now ? Invalidating the conntrack entry in case of DROP ?

**Comment by vel21ripn** [comment]
10 packets with payload.

nDPI can't drop packets. Only netfilter (iptables/nftables) can drop packets.
Netfilter removes data from conntrack. Tracking the deletion of data from conntack was the biggest challenge when creating ndpi-netfilter.

I still cannot understand how I can help you.
Packet latency is a half measure. It is simple to implement, but its flexibility is minimal.
I think that creating an "iptables target" that would enable hardware acceleration for all subsequent connection packets and report the connection was dropped would be the most versatile means of integrating nDPI/iptables and NSS.

**Comment by chirayu-patel** [comment]
Got it.. thx !!
