### ISSUE TITLE
Is it possible to define port number to be a service name without set iptables mark?

### ISSUE THREAD

**Issue by lyt0112** [vel21ripn/nDPI#108]
Hi 
I want to define some ports to show protocols without set iptables mark and config IP:
for example:
any:5300:Service1 
tcp:8100:Service2
...etc

cat /proc/net/xt_ndpi/flows and show P=Service1 directly
1616048148 1616048258 4 6 192.168.1.26 54967 x.x.x.x 5300 80 80 2 2 I=150,0 CM=c357 SN=x1.x1.x1.x1,54967 P=Service1 H=x.x.x.x

Is it possible?

**Comment by vel21ripn** [comment]
No.
The entries in /proc/net/xt_ndpi/ip_proto require an ip address.

**Comment by lyt0112** [comment]
ok..I see..
Thanks for your reply
