### ISSUE TITLE
custom service can not work with IP+port ?

### ISSUE THREAD

**Issue by lyt0112** [vel21ripn/nDPI#109]
Hi 
I tested the following two commands,but if I add port info into the command,it can not work..
May I know how to make it work?

echo '+182.54.195.0/24 maintain' >/proc/net/xt_ndpi/ip_proto <=it can work fine
1616466675 1616466696 4 6 192.168.1.26 49898 182.54.195.54 4444 834 550 6 6 I=145,0 CM=c358 SN=36.225.180.115,49898 P=maintain H=182.54.195.54
1616466654 1616466675 4 6 192.168.1.26 49887 182.54.195.54 4444 834 550 6 6 I=145,0 CM=c358 SN=36.225.180.115,49887 P=maintain H=182.54.195.54
1616466633 1616466648 4 6 192.168.1.26 49866 182.54.195.54 4444 834 550 6 6 I=145,0 CM=c358 SN=36.225.180.115,49866 P=maintain H=182.54.195.54
1616466612 1616466633 4 6 192.168.1.26 49861 182.54.195.54 4444 834 550 6 6 I=145,0 CM=c358 SN=36.225.180.115,49861 P=maintain H=182.54.195.54

echo '+182.54.195.0/24 any:4444:maintain' >/proc/net/xt_ndpi/ip_proto <=It can not work.
1616467458 1616467458 4 6 192.168.1.26 50065 182.54.195.54 4444 92 52 2 1                 I=145,0 CM=c358 SN=36.225.180.115,50065 P=Unknown
1616467458 1616467458 4 6 192.168.1.26 50064 182.54.195.54 4444 2157 2388 6 5         I=145,0 CM=c358 SN=36.225.180.115,50064 P=HTTP H=182.54.195.54
1616467453 1616467458 4 6 192.168.1.26 50062 182.54.195.54 4444 3297 32826 19 28   I=145,0 CM=c358 SN=36.225.180.115,50062 P=HTTP H=182.54.195.54
1616467437 1616467459 4 6 192.168.1.26 50058 182.54.195.54 4444 3950 133317 52 94 I=145,0 CM=c358 SN=36.225.180.115,50058 P=HTTP H=182.54.195.54

**Comment by vel21ripn** [comment]
Next week I will try to deal with this problem.

**Comment by vel21ripn** [comment]
Fixed in 1088121034e32697c705beb54cbd85fd0ade85f6

**Comment by lyt0112** [comment]
Hi 
I compile the new source code and do a test:
[root@ xt_ndpi]# echo "add_custom Test" >/proc/net/xt_ndpi/proto
[root@ xt_ndpi]# echo "+1.1.1.1 any:4444:Test" >/proc/net/xt_ndpi/ip_proto
[root@ xt_ndpi]# cat flows |grep 4444
1619425837 1619425844 4 6 192.168.1.26 49460 1.1.1.1 4444 208 0 4 0 I=145,0 CM=c358 SN=36.225.181.99,49460 P=Unknown

The custom defined traffic still be marked to Unknown.

**Comment by vel21ripn** [comment]
This is inbound traffic with no outbound and no payload. Currently, ip_proto is only applied after a few non-empty packets.
Try to check on the established connection.
I started changing the ip_proto implementation. If the protocol name is followed by "!", Then the protocol will be used without being determined by the contents of the package.
As soon as I fix the error of adding data to ip_proto, I will make a commit right away.

**Comment by lyt0112** [comment]
Hi
If I establish connections to known server,I can not see the custom defined protocol name. e.g. HTTP,Test or SSH,Test_23456
Is it normal?

[root@ net]# echo "add_custom Test" >/proc/net/xt_ndpi/proto
[root@ net]# echo "+172.104.86.111 any:80:Test" >/proc/net/xt_ndpi/ip_proto
[root@ net]# cat xt_ndpi/ip_proto |grep 172.104.86.111
172.104.86.111   udp:80:Test tcp:80:Test
[root@ net]# cat xt_ndpi/flows |grep 172.104.86.111
1619489530 1619489531 4 6 192.168.1.26 62175 172.104.86.111 80 839 3087 5 6     I=145,0 CM=c358 SN=36.225.179.25,62175 P=HTTP H=www.slime.com.tw
1619489528 1619489528 4 6 192.168.1.26 62163 172.104.86.111 80 891 7458 6 9     I=145,0 CM=c358 SN=36.225.179.25,62163 P=HTTP H=www.slime.com.tw
1619489528 1619489528 4 6 192.168.1.26 62162 172.104.86.111 80 1023 15808 7 14  I=145,0 CM=c358 SN=36.225.179.25,62162 P=HTTP H=www.slime.com.tw
1619489527 1619489528 4 6 192.168.1.26 62158 172.104.86.111 80 943 3476 5 6     I=145,0 CM=c358 SN=36.225.179.25,62158 P=HTTP H=www.slime.com.tw
1619489527 1619489528 4 6 192.168.1.26 62157 172.104.86.111 80 929 1107 5 5     I=145,0 CM=c358 SN=36.225.179.25,62157 P=HTTP H=www.slime.com.tw
1619489525 1619489525 4 6 192.168.1.26 62138 172.104.86.111 80 771 544 5 5      I=145,0 CM=c358 SN=36.225.179.25,62138 P=HTTP H=www.slime.com.tw
1619489525 1619489525 4 6 192.168.1.26 62137 172.104.86.111 80 778 1074 5 5     I=145,0 CM=c358 SN=36.225.179.25,62137 P=HTTP H=www.slime.com.tw
1619489525 1619489525 4 6 192.168.1.26 62135 172.104.86.111 80 749 7082 5 9     I=145,0 CM=c358 SN=36.225.179.25,62135 P=HTTP H=www.slime.com.tw
1619489524 1619489524 4 6 192.168.1.26 62130 172.104.86.111 80 707 2886 5 6     I=145,0 CM=c358 SN=36.225.179.25,62130 P=HTTP H=www.slime.com.tw
1619489524 1619489524 4 6 192.168.1.26 62129 172.104.86.111 80 1567 63101 24 46 I=145,0 CM=c358 SN=36.225.179.25,62129 P=HTTP H=www.slime.com.tw


[root@ net]# echo "add_custom Test_23456" >/proc/net/xt_ndpi/proto
[root@ net]# echo "+182.54.195.1 any:23456:Test_23456" >/proc/net/xt_ndpi/ip_proto
[root@ net]# cat xt_ndpi/flows |grep 182.54.195.1
1619490103 1619490110 4 6 192.168.1.26 62285 182.54.195.1 23456 3208 4016 19 21 I=145,0 CM=c358 SN=36.225.179.25,62285 P=SSH
1619490010 1619490012 4 6 192.168.1.26 62269 182.54.195.1 23456 2204 2908 11 10 I=145,0 CM=c358 SN=36.225.179.25,62269 P=SSH

**Comment by vel21ripn** [comment]
278b3cd57c65d1dc3af272771f7a6a2cf01edff7
See the ndpi-netfilter/INSTALL for the use of the "!" after the name of the protocol

**Comment by lyt0112** [comment]
Hi 
The custom service can show defined application name on the protocol field.
1620628108 1620628108 4 6 192.168.1.26 60373 172.104.86.111 80 747 2886 5 6 I=145,0 CM=c358 SN=36.225.179.25,60373 P=Slime,HTTP H=www.slime.com.tw
Thanks for the newest version.
