### ISSUE TITLE
Ubuntu Xenail 16.04 docker container build

### ISSUE THREAD

**Issue by elico** [vel21ripn/nDPI#11]
For debian 8 compilation I composed the next Docker:
https://github.com/elico/debian8-dev-ndpi-vel

I will try to compose also one for xenial(it should be around here on my server already.. so couple days and it's here)

**Comment by vel21ripn** [comment]
Moved to wiki.

**Comment by elico** [comment]
@vel21ripn but the existing one is for debian and not for ubuntu... so change it in the wiki an I will update the issue with the gist for the ubuntu one.
( I already have it but need to pull it from my server)

**Comment by elico** [comment]
@vel21ripn this is the ubuntu 16.04 docker build node gist:
https://gist.github.com/elico/13b25804aa8d3dc7d8f15e43f6df2448
