### ISSUE TITLE
A memory leak issue of ndpi_ctinfo

### ISSUE THREAD

**Issue by lyt0112** [vel21ripn/nDPI#116]
Hi 
I just tested the kernel module on a real environment.
I found the module caused a memory leak issue ..

At this time,the conntrack number is 1593 entries.

# name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab> : tunables <limit> <batchcount> <sharedfactor> : slabdata <active_slabs> <num_slabs> <sharedavail>
ipt_netflow         1388   1792    144   28    1 : tunables    0    0    0 : slabdata     64     64      0
ndpi_ids             965   1380    344   23    2 : tunables    0    0    0 : slabdata     60     60      0
ndpi_flows          1661   2592   2616   12    8 : tunables    0    0    0 : slabdata    216    216      0
**ndpi_ctinfo       4147038 4147038    176   23    1 : tunables    0    0    0 : slabdata 180306 180306      0**
squashfs_inode_cache    399    700    640   25    4 : tunables    0    0    0 : slabdata     28     28      0
UDPLITEv6              0      0   1088   30    8 : tunables    0    0    0 : slabdata      0      0      0
UDPv6                120    120   1088   30    8 : tunables    0    0    0 : slabdata      4      4      0
tw_sock_TCPv6         84     84    192   21    1 : tunables    0    0    0 : slabdata      4      4      0
TCPv6                 64     64   1984   16    8 : tunables    0    0    0 : slabdata      4      4      0
nf_conntrack_ffffffff818b9000   1782   4342    304   26    2 : tunables    0    0    0 : slabdata    167    167      0
scsi_cmd_cache       126    126    384   21    2 : tunables    0    0    0 : slabdata      6      6      0
cfq_queue             68     68    232   17    1 : tunables    0    0    0 : slabdata      4      4      0
bsg_cmd                0      0    312   26    2 : tunables    0    0    0 : slabdata      0      0      0
mqueue_inode_cache     18     18    896   18    4 : tunables    0    0    0 : slabdata      1      1      0
fat_inode_cache      512    598    704   23    4 : tunables    0    0    0 : slabdata     26     26      0
fat_cache            612    612     40  102    1 : tunables    0    0    0 : slabdata      6      6      0
hugetlbfs_inode_cache     56     56    584   28    4 : tunables    0    0    0 : slabdata      2      2      0
jbd2_journal_handle      0      0     48   85    1 : tunables    0    0    0 : slabdata      0      0      0
jbd2_journal_head      0      0    112   36    1 : tunables    0    0    0 : slabdata      0      0      0
jbd2_revoke_table_s      0      0     16  256    1 : tunables    0    0    0 : slabdata      0      0      0
jbd2_revoke_record_s      0      0     32  128    1 : tunables    0    0    0 : slabdata      0      0      0
ext4_inode_cache       0      0    992   16    4 : tunables    0    0    0 : slabdata      0      0      0
ext4_free_data         0      0     64   64    1 : tunables    0    0    0 : slabdata      0      0      0
ext4_allocation_context      0      0    128   32    1 : tunables    0    0    0 : slabdata      0      0      0
ext4_io_end            0      0     72   56    1 : tunables    0    0    0 : slabdata      0      0      0
ext4_extent_status      0      0     40  102    1 : tunables    0    0    0 : slabdata      0      0      0
ext2_inode_cache     718   1100    736   22    4 : tunables    0    0    0 : slabdata     50     50      0
configfs_dir_cache      0      0     88   46    1 : tunables    0    0    0 : slabdata      0      0      0
dquot                  0      0    256   16    1 : tunables    0    0    0 : slabdata      0      0      0
fsnotify_mark         36     36    112   36    1 : tunables    0    0    0 : slabdata      1      1      0
pid_namespace          0      0   2200   14    8 : tunables    0    0    0 : slabdata      0      0      0
posix_timers_cache      0      0    216   18    1 : tunables    0    0    0 : slabdata      0      0      0
ip4-frags             24     24    168   24    1 : tunables    0    0    0 : slabdata      1      1      0
UDP-Lite               0      0    896   18    4 : tunables    0    0    0 : slabdata      0      0      0
flow_cache          5709   7449    104   39    1 : tunables    0    0    0 : slabdata    191    191      0
xfrm_dst_cache       468    468    448   18    2 : tunables    0    0    0 : slabdata     26     26      0
ip_fib_trie          292    292     56   73    1 : tunables    0    0    0 : slabdata      4      4      0
UDP                   72     72    896   18    4 : tunables    0    0    0 : slabdata      4      4      0
tw_sock_TCP           84     84    192   21    1 : tunables    0    0    0 : slabdata      4      4      0
TCP                   90     90   1792   18    8 : tunables    0    0    0 : slabdata      5      5      0
scsi_data_buffer       0      0     24  170    1 : tunables    0    0    0 : slabdata      0      0      0
blkdev_queue          36     36   1816   18    8 : tunables    0    0    0 : slabdata      2      2      0
blkdev_requests      594    594    368   22    2 : tunables    0    0    0 : slabdata     27     27      0
user_namespace         0      0    224   18    1 : tunables    0    0    0 : slabdata      0      0      0
dmaengine-unmap-256     15     15   2112   15    8 : tunables    0    0    0 : slabdata      1      1      0
sock_inode_cache     275    275    640   25    4 : tunables    0    0    0 : slabdata     11     11      0
skbuff_fclone_cache    476    476    576   28    4 : tunables    0    0    0 : slabdata     17     17      0
net_namespace          0      0   4160    7    8 : tunables    0    0    0 : slabdata      0      0      0
shmem_inode_cache   1104   1104    656   24    4 : tunables    0    0    0 : slabdata     46     46      0
taskstats             96     96    328   24    2 : tunables    0    0    0 : slabdata      4      4      0
proc_inode_cache     700    700    632   25    4 : tunables    0    0    0 : slabdata     28     28      0
sigqueue             125    125    160   25    1 : tunables    0    0    0 : slabdata      5      5      0
bdev_cache            76     76    832   19    4 : tunables    0    0    0 : slabdata      4      4      0
kernfs_node_cache  31620  31620    120   34    1 : tunables    0    0    0 : slabdata    930    930      0
mnt_cache            125    125    320   25    2 : tunables    0    0    0 : slabdata      5      5      0
inode_cache          952    952    568   28    4 : tunables    0    0    0 : slabdata     34     34      0
dentry              2697   7749    192   21    1 : tunables    0    0    0 : slabdata    369    369      0
buffer_head         5343   5343    104   39    1 : tunables    0    0    0 : slabdata    137    137      0
vm_area_struct      4565   4598    184   22    1 : tunables    0    0    0 : slabdata    209    209      0
mm_struct            327    414    896   18    4 : tunables    0    0    0 : slabdata     23     23      0
files_cache          481    650    640   25    4 : tunables    0    0    0 : slabdata     26     26      0
signal_cache         353    480   1088   30    8 : tunables    0    0    0 : slabdata     16     16      0
sighand_cache        285    285   2112   15    8 : tunables    0    0    0 : slabdata     19     19      0
task_struct          289    308   2272   14    8 : tunables    0    0    0 : slabdata     22     22      0
Acpi-ParseExt       3472   3472     72   56    1 : tunables    0    0    0 : slabdata     62     62      0
Acpi-State           204    204     80   51    1 : tunables    0    0    0 : slabdata      4      4      0
Acpi-Namespace      2346   2346     40  102    1 : tunables    0    0    0 : slabdata     23     23      0
anon_vma            4256   4256     72   56    1 : tunables    0    0    0 : slabdata     76     76      0
shared_policy_node    340    340     48   85    1 : tunables    0    0    0 : slabdata      4      4      0
numa_policy           30     30    136   30    1 : tunables    0    0    0 : slabdata      1      1      0
radix_tree_node     3847   7896    584   28    4 : tunables    0    0    0 : slabdata    282    282      0
idr_layer_cache      360    360   2096   15    8 : tunables    0    0    0 : slabdata     24     24      0
dma-kmalloc-8192       0      0   8192    4    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-4096       0      0   4096    8    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-2048       0      0   2048   16    8 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-1024       0      0   1024   16    4 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-512        0      0    512   16    2 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-256        0      0    256   16    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-128        0      0    128   32    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-64         0      0     64   64    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-32         0      0     32  128    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-16         0      0     16  256    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-8          0      0      8  512    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-192        0      0    192   21    1 : tunables    0    0    0 : slabdata      0      0      0
dma-kmalloc-96         0      0     96   42    1 : tunables    0    0    0 : slabdata      0      0      0
kmalloc-8192         480    544   8192    4    8 : tunables    0    0    0 : slabdata    136    136      0
kmalloc-4096         716    736   4096    8    8 : tunables    0    0    0 : slabdata     92     92      0
kmalloc-2048        1684   1984   2048   16    8 : tunables    0    0    0 : slabdata    124    124      0
kmalloc-1024        1286   1344   1024   16    4 : tunables    0    0    0 : slabdata     84     84      0
kmalloc-512         3700   5568    512   16    2 : tunables    0    0    0 : slabdata    348    348      0
kmalloc-256        13663  13776    256   16    1 : tunables    0    0    0 : slabdata    861    861      0
kmalloc-192         3677   4536    192   21    1 : tunables    0    0    0 : slabdata    216    216      0
kmalloc-128        13218  13312    128   32    1 : tunables    0    0    0 : slabdata    416    416      0
kmalloc-96          4200   4200     96   42    1 : tunables    0    0    0 : slabdata    100    100      0
kmalloc-64        135675 137024     64   64    1 : tunables    0    0    0 : slabdata   2141   2141      0
kmalloc-32        1259008 1259008     32  128    1 : tunables    0    0    0 : slabdata   9836   9836      0
kmalloc-16        169965 173056     16  256    1 : tunables    0    0    0 : slabdata    676    676      0
kmalloc-8           9216   9216      8  512    1 : tunables    0    0    0 : slabdata     18     18      0
kmem_cache_node      320    320     64   64    1 : tunables    0    0    0 : slabdata      5      5      0

**Comment by vel21ripn** [comment]
If you are using "-j NDPI --flow-info" then you should regularly read the file "/proc/net/xt_ndpi/flows".
Does the "cat /proc/net/xt_ndpi/flows" command decrease ndpi_ctinfo?

**Comment by lyt0112** [comment]
I edit ./ndpi-netfilter/src/ndpi_proc_flow.c
n->acc_read_mode = 0; =>n->acc_read_mode = 2; to make the behavior same as nf_conntrack
And then added command on crontab "cat /proc/net/xt_ndpi/flows >>/mnt/storage/conntrack.log" to save the logs every 1 min

**Comment by vel21ripn** [comment]
This is not a memory leak.
You need to periodically read all the contents of the file /proc/net/xt_ndpi/flows to clean all outdated data.
Use ndpi_flow_dump to read the contents of /proc/net/xt_ndpi/flows. You can specify the read mode in it.
