### ISSUE TITLE
Can't delete iptbales rules (iptables: Bad rule (does a matching rule exist in that chain?)

### ISSUE THREAD

**Issue by lailitty** [vel21ripn/nDPI#117]
when set iptables rule success like:
    iptables  -A FORWARD -m ndpi  --host www.youtube.com -j DROP

but delete failed with the following command:
    iptables  -D FORWARD -m ndpi  --host www.youtube.com -j DROP
    iptables: Bad rule (does a matching rule exist in that chain?).

**Comment by vel21ripn** [comment]
man iptables
```
iptables [-t table] -D chain rulenum
```

**Comment by lailitty** [comment]
Thank you for your answer, delete a iptables rule maybe have 3 ways
1. Delete according to rulenum, like you said(can work)
2. Delete the exact match and change '- A' into '- D'(Like my question)
3. Delete the entire linked list(iptables [-t table] -F)

you mean precise deletion is not supported?

**Comment by vel21ripn** [comment]
I don’t know why deleting rules by exact match doesn’t work.
If you know how to fix it, then do a Pull Requtst.

**Comment by lailitty** [comment]
I have fixed it and did a Pull Request, Pls check it

**Comment by vel21ripn** [comment]
Thanks!
