### ISSUE TITLE
ssl certificate CN based custom dissector

### ISSUE THREAD

**Issue by moriscis** [vel21ripn/nDPI#118]
I built ndpi onto a Debian 10 machine and am trying to create a custom dissector that could match the CN or other certificate details on the network traffic. I found that the tls.c protocol file had functions that are checking the certificate details in them and tried to open the debugging options on the protocol file to see if it was able to get the certificate information and log it(in order to maybe duplicate that behavior for my dissector).

With the xt_ndpi module loaded and rules to log ndpi detected tls protocol packets on the INPUT, FORWARD, and OUTPUT chains of the filter table there was nothing happening, and the counters for the rules didn't increase at all. I also tried adding a rule to the nat prerouting chain just to be sure but nothing happened.
![image](https://user-images.githubusercontent.com/88894686/129376317-b3f78ddb-11be-42d2-9851-706d63f172bd.png)

The Syslog kept showing the following logs from the tls.c protocol file.
![image](https://user-images.githubusercontent.com/88894686/129376549-b685f63f-d9ec-4f48-ad6e-fdc2ebf93cd0.png)

I couldn't find another example of a dissector that was checking the certificate information from traffic to classify it. 
As far as I could tell most of the directors are either working with TCP opcodes, ports, IP addresses or the payload hex code patterns to match traffic and classify it.

I also saw in the xt_ndpi modules help that there are flags for --cert or --host-or-cert matching.
![image](https://user-images.githubusercontent.com/88894686/129376698-6b33a261-753b-4584-8dbd-c9f8fea689d8.png)
Using this flag to try to block the traffic for a website by providing the certificate name ended in blocking all web traffic for the client rather than just the intended website.
The following is an example of the rule I tried to use (the rule was tried on different chains to see if it made a difference too):
![image](https://user-images.githubusercontent.com/88894686/129377049-59f3714f-2dd9-478a-83f8-ccbf89e494f7.png)

So I wanted to ask if there is a way to get the certificate information on the traffic and use that information to match traffic using the ndpi and iptables xt_ndpi module and how the --cert and --host-or-cert flags work?

**Comment by vel21ripn** [comment]
You can use the user-defined protocol.
I'm still busy updating ndpi-netfilter to nDPI version 4.0
