### ISSUE TITLE
Some question about protocol category？

### ISSUE THREAD

**Issue by lailitty** [vel21ripn/nDPI#121]
I found that there are some places in the code through macros "__ KERNEL__"  Shielding support for protocol category，just like ：
![1631168718(1)](https://user-images.githubusercontent.com/17486664/132634281-2cd5c801-c126-4ad5-b579-93d1e80aa3fa.png)
or
![1631168909(1)](https://user-images.githubusercontent.com/17486664/132634392-f00dba43-731b-4ec2-accb-fd43e3e8a1b5.png)

for what reason of this？and if I have same idea with issue #87 “Is it possible to match a lists of protocols as category?”  
Can I modify macros"__ KERNEL__" Affected by these codes to achieve the purpose.

**Comment by vel21ripn** [comment]
`Can I modify macros"__ KERNEL__" Affected by these codes to achieve the purpose.`
What will you do next with these categories?
There is no way to check traffic by categories. The category is not exported to flows.
If you need to group protocols, then use mark/mask in /proc/net/xt_ndpi/proto.
Can you offer a full implementation of category support?
We need an interface for creating and editing categories (custom categories) via procfs, add options for iptables and export the category to flows.

**Comment by lailitty** [comment]
At present, most protocols supported by nDPI library define categories, As shown in ndpiReader:
![Image](https://user-images.githubusercontent.com/17486664/132648688-6bcf7607-fea3-4752-be36-2058daa3d21c.png)
maybe this can also show in /proc/net/xt_ndpi/flows, and add the match options in iptables we can batch operation of a certain category of protocol.(First identify the traffic protocol and then find the corresponding category, rather than identifying the category directly from the traffic)

**Comment by vel21ripn** [comment]
Can you offer a full implementation of category support?
At the moment there are problems in the project to be solved.
