### ISSUE TITLE
facbook/whatsapp/Instagram/youtube-Mobile apps not blocking 

### ISSUE THREAD

**Issue by xbeowulfx** [vel21ripn/nDPI#123]
ptables -A OUTPUT -m ndpi --match-proto --proto whatsapp -j DROP ; 
iptables -A FORWARD -m ndpi --match-proto --proto whatsapp -j DROP ; 
iptables -A INPUT -m ndpi --match-proto --proto whatsapp -j DROP

^^ These are my iptable rules

**Comment by vel21ripn** [comment]
Try to collect traffic samples and test it using ndpiReader.
