### ISSUE TITLE
iptables does not allow adding more than one protocol with ndpi

### ISSUE THREAD

**Issue by prozaklob** [vel21ripn/nDPI#124]
hi!

im add two custom proto in:
`/proc/net/xt_ndpi/proto`

```
proto1
proto2
```

try app rule to iptables:

`iptables -A FORWARD -m ndpi --proto1 -m physdev --physdev-is-bridge -j ACCEPT`
it's - ok

```
iptable -vL
 ndpi protocol bad_host PHYSDEV match --physdev-is-bridged
```

next, i,m try other rule:

`iptables -A FORWARD -m ndpi --proto2 -m physdev --physdev-is-bridge -j ACCEPT`

and i get error:

```
iptables -A FORWARD -m ndpi --proto2 -m physdev --physdev-is-bridge -j DROP
iptables v1.8.2 (nf_tables): unknown option "--proto2"
Try `iptables -h' or 'iptables --help' for more information.
```

` iptables -m ndpi --help`

proto1 and proto 2 exist

host_proto too exist records "proto1: and proto2:"

it makes no difference in what order to try to add the rules proto2 / proto1

thx

**Comment by vel21ripn** [comment]
Which version are you using?
The "--proto" form has long been canceled.
Use "--proto proto1".

**Comment by prozaklob** [comment]
> Which version are you using? The "--proto" form has long been canceled. Use "--proto proto1".

hmm. how i can see version?
