### ISSUE TITLE
NDPI SSL info now logged as Hostname instead of Certificate

### ISSUE THREAD

**Issue by netcons** [vel21ripn/nDPI#127]
### Description
_NDPI SSL info used to be logged as C= but now gets logged as H=_

### Expected behavior
_1553364301 1553364301 4 6 xxx.xxx.xxx.3 59438 64.233.161.104 443 447 2762 4 3 I=20,20 Google.SSL C=www.google.com_
### Obtained behavior
_1553364301 1553364301 4 6 xxx.xxx.xxx.3 59438 64.233.161.104 443 447 2762 4 3 I=20,20 Google.SSL H=www.google.com_

## nDPI Environment (please complete the following information):
* OS name: CentOS
* OS version: 8 Stream
* Architecture: x86_64
* nDPI version or commit hash: xt_ndpi v1.2 ndpi 4.1.0
* nDPI compilation flags used: ./autogen.sh; make -C src/lib ndpi_network_list.c.inc; make -C ndpi-netfilter
[config.log](https://github.com/vel21ripn/nDPI/files/8087657/config.log)

## How to reproduce the reported bug
_-m ndpi ! --error -j NDPI --flow-info_

**Comment by vel21ripn** [comment]
"C=" will be removed in the next updates.

**Comment by netcons** [comment]
Thanks Vitaly, makes sense.
