### ISSUE TITLE
Number of protocols more than 256 and iptables options limit?...

### ISSUE THREAD

**Issue by sharonenoch** [vel21ripn/nDPI#128]
@vel21ripn  Have couple of questions ..

1) I remember some time back you had mentioned that iptables options had a limit of 256.. Now the number of protocols have increased to 278, so how was this handled?

2) The IP databases, are they region based or worldwide? 

3) Would IPv6 IPs also included in the IP database in future or are they included somewhere already?

**Comment by vel21ripn** [comment]
1. iptables have limit on 256 names of option. Because of this, the options with protocol names had to be abandoned. Currently only the --proto \<name\> option is used. 
2. IMHO WW
3. This needs to be implemented at the nDPI project level.

**Comment by sharonenoch** [comment]
Thankyou.. @vel21ripn for the answers... 

I had another question on the detection of the protocols like Salesforce.. Is the Salesforce application detected from the initial TLS handshake.. and if so which portion of the TLS header is used to determine the same? Is it generic for all TLS application detection like Office365 etc? Could you point me to where this detection takes place.. 

I was always referring the dissector functions in the protocols directory and did not see it there..

**Comment by sharonenoch** [comment]
I think I got it now.. it uses the TLS dissector itself and then from there the certificate information is dissected to get the DNSname and then that is matched against the protocol.. ndpi_match_hostname_protocol().. Let me know if this flow is accurate..
