### ISSUE TITLE
update ip list

### ISSUE THREAD

**Issue by Anthony-76** [vel21ripn/nDPI#129]
Hi,
I use nDPI with iptables on Linux system in order to block unwanted applications.
It works very well.

So, I just seen in the source files the Utils directory with the following files

aws_ip_addresses_download.sh
azure_ip_addresses_download.sh
google_cloud_ip_addresses_download.sh

etc ....

So, in my case if I block Google Cloud application or TOR nodes with NDPI module with Iptables, do I need to use these scripts?
If yes, How these scripts works?

Thanks for your help and explainations

Best regards
Anthony

**Comment by sharonenoch** [comment]
Earlier those IP list were hardcoded / kind of manually updated in their corresponding match.c.inc files or in the global  ndpi_content_match.c.inc file. 
Some used the .yaml files to generate the same using nlist.pl but still the yaml file was hardcoded and required manual updates if ips changed.. 

Now those match.c.inc are auto generated to pull the list from the corresponding website links..  

For example : The AWS global ip ranges is available in https://ip-ranges.amazonaws.com/ip-ranges.json

What you see in the utils folder is a parser what visits these links and parses it into the format of what the _match.c.inc files expect it to be in.. 

There are invoked by update_every_lists.sh.. But I am not sure where this is invoked from yet.. My understanding is they would be used during compile time.... I believe these are still in development and this script would be invoked sometime during compile time..

To answer your question though,  you would not use these files during runtime when you add iptable rules..

**Comment by vel21ripn** [comment]
At the moment, I use \*.yaml files to describe service addresses.
The ndpi_network_list_compile program checks and compiles address lists of all services into the file ndpi_network_list.c.inc
I don't use ndpi_\*_match.c.inc files.
A strange step was taken in the main project - the address lists for some of the services were moved to separate files. This will only make it easier to update them.
I plan to change the scripts to update address lists for services.

Address lists can be changed without changing the ndpi-netfilter code. Addresses can be added and removed via /proc/net/xt_ndpi/ip_proto  in any moment.

**Comment by Anthony-76** [comment]
Hi @vel21ripn and @sharonenoch 

Thank you for yours answers and explainations

So, if I can update the ip list via the /proc/net/xt_ndpi/ip_proto file, it's very nice.

In this case, nDPI module (with iptables) will be updated to "block" new ip addresses without re-compile the program? If yes, it's very interresting and well thought out.

Thank you

Anthony-76
