### ISSUE TITLE
1.7 and 1.8

### ISSUE THREAD

**Issue by mkoubar** [vel21ripn/nDPI#13]
the ndpi 1.7 is working fine on my system but i am guessing if we can use the ndpi 1.8

**Comment by k0ste** [comment]
@vel21ripn told about 1.8 not earlier than in May.

**Comment by vel21ripn** [comment]
The 2.0-stable branch is launched for testing.

**Comment by elico** [comment]
@vel21ripn I want to try and build it on couple systems.
Is the 2.0-stable branch the main branch of the repository or a special one?

**Comment by vel21ripn** [comment]
https://github.com/ntop/nDPI/tree/2.0-stable

**Comment by elico** [comment]
@vel21ripn OK.
Starting to build I will try to update later.

**Comment by elico** [comment]
@vel21ripn I have seen you have the branch:
https://github.com/vel21ripn/nDPI/tree/2.0-stable

but it's missing the ndpi-netfilter directory.
And i'm not sure I understood how https://github.com/ntop/nDPI/tree/2.0-stable
is related to your branch?
Let say I want to build your 2.0-stable, what netfilter module do I use?

**Comment by vel21ripn** [comment]
https://github.com/vel21ripn/nDPI/tree/2.0-stable is clone of https://github.com/ntop/nDPI/tree/2.0-stable
ndpi-netfilter-2.0 has not yet been published. The branch will be called netfilter2.
During testing, a very large percentage of unknown traffic was received. It is necessary to understand and fix it.

**Comment by elico** [comment]
@vel21ripn Thanks.
I managed to build the 2.0-stable but I was sure that a ndpi-netfilter module was already ready.
For now I am testing the latest netfilter branch.

**Comment by faizatahir94** [comment]
@elico Can you please guide me how did you incorporate version 2.0 with net-filter?

**Comment by elico** [comment]
@faizatahir94 it won't to just build 2.0-stable.. you need to also have a compatible  ndpi-netfilter module and this is yet to be ready as far as I know and can tell.

**Comment by faizatahir94** [comment]
@elico . Do you have an idea when netfilter2.0 will be released ( with ndpi 2.0 version ).  I need one more advise on how to calculate the latency if you use net-filter.

**Comment by elico** [comment]
@faizatahir94 Sorry but I have no clue about this.
@vel21ripn or\and @k0ste should be able to answer if it's on their goals list.
It's actually a big project so even if we would want to speed it up it might take more then you would expect.

**Comment by vel21ripn** [comment]
The netfilter2 branch is available for testing.
