### ISSUE TITLE
unable ti delete host to procol

### ISSUE THREAD

**Issue by didgaudin** [vel21ripn/nDPI#130]
Hello,
in the INSTALL doc, there is instruction to delete entry in host_proto : 
Delete match:
  "echo '-protoname:host' >/proc/net/xt_ndpi/host_proto"

i have made a test : 
echo 'add_custom protoname' >/proc/net/xt_ndpi/proto
echo 'protoname:host,host1' >/proc/net/xt_ndpi/host_proto

cat /proc/net/xt_ndpi/host_proto  => 
...
protoname:host,host1

if i want to delete 'host' i do : 
 echo '-protoname:host' >/proc/net/xt_ndpi/host_proto

the kernel said : 
[371335.597997] xt_ndpi: exists 'host'

and the host 'host' is always in the /proc/net/xt_ndpi/host_proto

do i need to do others command to remove my entry

**Comment by vel21ripn** [comment]
fixed in https://github.com/vel21ripn/nDPI/commit/07888e6e628d5af5068653b36392f735aca10730
