### ISSUE TITLE
Handle IP blacklist with "ipset" or "ip_proto"

### ISSUE THREAD

**Issue by someonebw** [vel21ripn/nDPI#136]
hi,vel21ripn
  
I have a question I would like to ask;

I have a scenario where IP addresses in a black-list are dropped in a Netfilter.

I would like to ask if the number of black-list-IP is relatively large, such as 2W-4W IP addresses

I have two choices:
1. Add these IP addresses to the hash-table-list of the IPset and drop them in the forward field
2. Place these IP addresses in /proc/net/xt_ndpi/ip_proto. Drop in forward

Which one works better? Less load on the system, more efficient?

**Comment by vel21ripn** [comment]
ipset has much less overhead.
"2W-4W IP addresses" is 2-4 million addresses?
To work with a large number of addresses, you must explicitly specify hashsize and maxelem.

**Comment by someonebw** [comment]
"2W-4W IP addresses" is 2-4 million addresses?
 20000 ip ---------40000 ip
 
 In this case, the hash table of ipset is used to process the hash table, which consumes less performance.
 Thank you for your reply,vel21ripn :)
