### ISSUE TITLE
Adding custom protocols over 512?

### ISSUE THREAD

**Issue by sharonenoch** [vel21ripn/nDPI#137]
@vel21ripn 

The NDPI_NUM_BITS is defined to 512 and the number of custom protocols is defined as 512-(current existing protocols).. 

Is there any way we can increase the protocols to more than 512 say 8192 etc.? Since if we increase the number of bits, it seems to be affecting other structures.. Is there a existing method to add more custom protocols over 512 or any changes that you can recommend to achieve the same?

**Comment by vel21ripn** [comment]
Change NDPI_NUM_BITS to a multiple of 32.
The sizes of data structures depend on NDPI_NUM_BITS.
I can't think of a reason for such a significant increase in the number of protocols.

**Comment by sharonenoch** [comment]
Thankyou @vel21ripn.. 

We were using nDPI for flow steering using marks and firewall, via the iptables.. So like how CNN protocol id is defined, we were adding for some 1000+ websites which we wanted to steer to different interfaces based on nDPI detection.. Is this the proper method or do you suggest any other direction that we could take?. Since only if we add the website in host proto, do we get the selection in iptables to refer to that particular proto/website.

**Comment by vel21ripn** [comment]
Changing NDPI_NUM_BITS will require changing the size of the hostname field in struct xt_ndpi_mtinfo.
Do you have thousands of interfaces in use? What are these interfaces? I have not yet understood what is at stake.
Note that when a hostname is detected, it happens after the connection is established and can no longer be redirected.

**Comment by sharonenoch** [comment]
So the use case is.. 
We have branches and a datacenter and it would just be 2 or 3 tunnel interfaces to the DC via either IPSEC or VPN or any such tunnel.. All traffic from the LAN including internet is sent to the DC via the tunnels.. So NAT is not an issue as it would happen only at the DC to the outside internet.. 

The branches can balance the packets runtime across the tunnels or just decide to use a specific tunnel based on performance characteristics at point in time..  Due to this we don't mind when the hostname is detected... 

We also thought of grouping multiple websites under a single custom protocol so that we don't go over the 512 limit.. But looks like as you mentioned above the hostname field has a a size limit of 

char	hostname[256 - sizeof(NDPI_PROTOCOL_BITMASK) - sizeof(unsigned short int)-sizeof(void *)];
