### ISSUE TITLE
Regex matching in the current ahocorasic implementation

### ISSUE THREAD

**Issue by subhajit-cdot** [vel21ripn/nDPI#138]
Hi @vel21ripn 
Is it possible to support regular expression matching with the current ahocorasic implementation ? Currently I use it for substring matching only which leads to a large number of rules/policies in the system. The goal is to reduce number of configuration commands in the system and match similar substrings deduced from a regex.

Thanks
Subhajit

**Comment by vel21ripn** [comment]
Please read about the algorithm https://en.wikipedia.org/wiki/Aho%E2%80%93Corasick_algorithm
Regular expressions cannot be implemented within this algorith

**Comment by subhajit-cdot** [comment]
So, I was checking https://pyahocorasick.readthedocs.io/en/1.1.1/ , and found they provided wildcard support of the matcher using trie and used ahocorasick finally.

**Comment by vel21ripn** [comment]
wildcard is not regex.
The idea looks simple. Can you implement it yourself?
There is a separate project https://github.com/vel21ripn/ahocorasick in which it is easier to experiment.
If you can implement wildcard comparison, then I will move them to ndpi-netfilter.
I won't be able to do development anytime soon.

**Comment by subhajitchatu** [comment]
Ok let me check the code and discuss with you.

**Comment by subhajit-cdot** [comment]
Hi @vel21ripn ,
I think you have already incorporated Wildcard support in the current ahocorasic library used by ndpi. I can see that you have kept from_start  and at_end inside AC_REP_t structure. If I understand correctly these features can be enabled/accessed using "^" and "$" respectively. (ac_automata_exact_match)
Have you maintained any detailed design document about the changes/adaptations you have taken for ahocorasic and the reason behind the changes (I mean how you achieve optimal performance) ?

Thanks
Subhajit
