### ISSUE TITLE
Openwrt Compilation

### ISSUE THREAD

**Issue by lantis1008** [vel21ripn/nDPI#14]
Hi @vel21ripn 

I have been using ndpi-netfilter from betolj's repository. I would like to try yours to see if i can get more stability and more active development.

Are you able to assist in modifying [this Makefile](https://raw.githubusercontent.com/lantis1008/gargoyle/afabcd275f26db6374dcbb24e319b2cb34637231/package/ndpi-netfilter/Makefile) to suit your repository? I have made some of my own attempts ([here](https://pastebin.com/raw/RhR5s0e8)) but am currently [unsuccessful](https://pastebin.com/raw/3eVqJGcN).

**Comment by vel21ripn** [comment]
> libxt_ndpi.c:28:21: fatal error: xtables.h: No such file or directory
I can not help you.  I did not use the openwrt build system.

**Comment by elico** [comment]
@lantis1008 if it can help you take a a look at:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ipt_ndpi
and maybe the builds and patched I used that are mentioned on my docker recpies at:
https://github.com/vel21ripn/nDPI/wiki

**Comment by spacedream** [comment]
I getting bunch of errors about missing LITTLE_ENDIAN
after googling i guess its missing line somewhere like ````#include <endian.h>```` but in what file exactly? ty.

**Comment by elico** [comment]
@spacedream on OpenWRT?
