### ISSUE TITLE
Clarification on --host option

### ISSUE THREAD

**Issue by rightkick** [vel21ripn/nDPI#143]
Hi! 

Was wondering how one would use the `--host` option to match a specific hostname or regex, especially when one needs to allow the specific traffic for HTTPs encrypted sites. I am trying the following although I am observing that the matching is not always successful or many packets are allowed through the `--inprogress` rule. 

```
-A FORWARD -s 172.16.100.11/32 -m ndpi --inprogress http,tls -j ACCEPT
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto http,tls -j ACCEPT
```

or (all protocols)

```
-A FORWARD -s 172.16.100.11/32 -m ndpi --inprogress all -j ACCEPT
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto all -j ACCEPT
```

I understand that with HTTPs traffic one will need to match the hostname in the certificate SNI. 
The ndpi rules are added at the FORWARD chain before any other rules. 

Is there any other better approach to allow specific hosts/sites? I am wondering if `--untracked`, `--clevel` or other option can help. 

I can easily block either HTTP or HTTPs traffic as below: 

```
# HTTP block
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto http -j REJECT
# HTTPs block
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto http,tls -j REJECT
# Block all protocols
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto all -j REJECT
```

I running the latest build from the flow_info-4 branch on a 5.10 kernel (compiled with the required configs enabled) and iptables v1.6.0. 

Thanks, 
Alex

**Comment by vel21ripn** [comment]
The --inprogress option is the ability to let unknown traffic through until the protocol is determined.
I haven't checked, but perhaps a more correct sequence

````
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto http,tls -j ACCEPT
-A FORWARD -s 172.16.100.11/32 -m ndpi --inprogress all --proto unknown -j ACCEPT
-A FORWARD -s 172.16.100.11/32 -m ndpi --proto http,tls -j DROP
````

If the list of hosts is large, then user defined protocols can be used (see INSTALL p.7 add_custom).

**Comment by rightkick** [comment]
Thank you for your reply. The syntax `-A FORWARD -s 172.16.100.11/32 -m ndpi --inprogress all --proto unknown -j ACCEPT` is not accepted. I can add though `iptables -A FORWARD -s 172.16.100.11/32 -m ndpi --inprogress unknown -j ACCEPT`. I understand that the `--inprogress all` will match packets of all protocols that are still in the process of detection. Maybe `--inprogress unknown` does not make sense?

I am aware also of the custom defined protocols at `/proc/net/xt_ndpi/host_proto` though there it seems I cannot use regex.

**Comment by vel21ripn** [comment]
No.
--inprogress unknown - impossible condition.

IMHO in your case the following set of rules should be the most accurate
```
-A FORWARD -s 172.16.100.11/32 -m ndpi --host "example.com" --proto http,tls -j ACCEPT
-A FORWARD -s 172.16.100.11/32 -m ndpi --proto http,tls -j DROP
-A FORWARD -s 172.16.100.11/32 -m ndpi --inprogress http,tls -j ACCEPT
```
If you really need to use regex then use --host.

**Comment by rightkick** [comment]
My major problem is that the iptables I use accepts traffic that is `ESTABLISHED` or `RELATED`. Leaving few packets with `--inprogress` might result for some flows to get in an `ESTABLISHED` state and then all subsequent traffic to be allowed making the app filtering somehow relaxed. 

To address this I moved state check after the DPI allow rules and mark/connmark traffic that matches `--inprogress` and accept `ESTABLISHED,RELATED` that does not have this specific mark so as to avoid accepting it when checking its state. I don't like very much the approach as it seems a bit convoluted and would prefer to avoid using connmark for this purpose as it affects other rules that use connmark also. Moving the rules also at mangle seems to do no difference since one will still need to allow few packets at filter for the detection to progress. 

Any ideas how one can best use DPI allow rules with stateful firewalls so as to minimize traffic leakage?

Thanx.

**Comment by vel21ripn** [comment]
In the tcp protocol, there are always 3 packets to establish a connection. 
DPI works with the contents of the packets that appear after the connection is established.
It was to solve this problem that the --inprogress option had to be introduced.

**Comment by rightkick** [comment]
I see it is tricky to allow a specific app. DPI seems most suitable to classify or block apps.  At the moment in order to differentiate --inprogress DPI traffic from normal established traffic I mark the --inprogress DPI traffic and accept only established traffic that is not marked. In this way with the few accepted traffic through the --inprogress rules the app is eventually detected and allowed. 

I see the module provides also the following options: 

```
NDPI target options:
  --value value/mask                  Set value = (value & ~mask) | value
  --ndpi-id                           Set value = (value & ~proto_mask) | proto_mark by any proto
  --ndpi-id-p                         Set value = (value & ~proto_mask) | proto_mark by proto
  --ndpi-id-m                         Set value = (value & ~proto_mask) | proto_mark by master protocol
  --set-mark                          Set nfmark = value
  --set-clsf                          Set priority = value
  --flow-info                         Save flow info
  --accept                            -j ACCEPT
```

I am not sure how `--ndpi-id` is used. How `-j NDPI --ndpi-id` affects a packet? Does it has to do with the values at `/proc/net/xt_ndpi/proto` and should be used with the other options so as to set a priority or a packet mark? Trying to understand since this might be a better way to label such traffic instead of connmark.

**Comment by vel21ripn** [comment]
"-j NDPI --ndpi-id --set-mark" takes the label and mask from /proc/net/xt_ndpi/proto and applies it to the network packet.
This is the equivalent of "-j MARK".
Analog "-j CONNMARK" is not implemented.
"-j NDPI --ndpi-id --set-clsf" works like "-j CLASSIFY".

**Comment by rightkick** [comment]
Thank you.
