### ISSUE TITLE
Is this a bug or is it intentional?

### ISSUE THREAD

**Issue by abilly007** [vel21ripn/nDPI#148]
In function bt_ port_gc, there have such a piece of code:
![36089AED-7F32-447f-A63D-3BF1B5B58009](https://user-images.githubusercontent.com/37547039/206404534-57dc3828-bdc6-4542-877f-9ba34ee7e071.png)
According to the code logic, there is a problem: if jiffies  once before(not after) n->acc_gc, n->acc will be updated n->acc_gc = jiffies+5 * HZ, 
which will result in n ->acc_gc always after jiffies and will never execute ndpi_delete_acct function, that is, the flow will never be deleted.
Is this a bug or is it deliberately not to delete the stream? when user Read by cat /proc/net/xt_ndpi/flows, the stream will be aged and deleted? 
Thank you very much for checking my questions and answering them in your busy schedule. Thank you.

**Comment by vel21ripn** [comment]
This is bug.
This bug does not appear if "flows" is read in a timely manner.

**Comment by vel21ripn** [comment]
Fixed in 7c9a1049d9b9a5b43f0a18a4b2ee9d95184d0258
