### ISSUE TITLE
При попытке установить ndpi-netfilter на debian 9 возникает ошибка (при этом, библиотека nDPI собирается успешно).

### ISSUE THREAD

**Issue by kubeengineering** [vel21ripn/nDPI#149]
## Describe the bug
При попытке установить ndpi-netfilter на debian 9 возникает ошибка (при этом, библиотека nDPI собирается успешно).

### Obtained behavior
nDPI устанавливается успешно.
Утилита ndpi-netfilter при попытке make возвращает ошибку.

## nDPI Environment (please complete the following information):
* OS name: Debian
* OS version: 9
* Kernel version: 4.9.0-4-amd64 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
* Architecture: amd64
* nDPI version: commit 22e73317bb4455da0eb967c8be35a81b71d40837 (default branch: flow_info-4)

### Steps to reproduce the behavior:
	
./autogen.sh
( cd src/lib ; make ndpi_network_list.c.inc )
cd  ndpi-netfilter
	
	root@debian-9-x64:/home/xkubee/nDPI/ndpi-netfilter# make
        make -C ipt
        make[1]: Entering directory '/home/xkubee/nDPI/ndpi-netfilter/ipt'
        make[1]: Nothing to be done for 'all'.
        make[1]: Leaving directory '/home/xkubee/nDPI/ndpi-netfilter/ipt'
        make -C src
        make[1]: Entering directory '/home/xkubee/nDPI/ndpi-netfilter/src'
        grep: /lib/modules/4.9.0-11-amd64/build: Is a directory
        grep: /source/include/linux/skbuff.h: No such file or directory
        $xt_ndpi-y is [main.o ndpi_strcol.o ndpi_proc_parsers.o ndpi_proc_generic.o ndpi_proc_info.o  ndpi_proc_flow.o ndpi_proc_hostdef.o ndpi_proc_ipdef.o ../libre/regexp.o ../../src/lib/third_party/src/ndpi_md5.o ../../src/lib/third_party/src/ndpi_sha1.o ../../src/lib/third_party/src/ahocorasick.o ../../src/lib/third_party/src/libcache.o ../../src/lib/third_party/src/ndpi_patricia.o ../../src/lib/third_party/src/gcrypt_light.o ../../src/lib/third_party/src/btlib.o ../../src/lib/ndpi_main.o ../../src/lib/ndpi_utils.o ../../src/lib/ndpi_serializer.o ../../src/lib/ndpi_geoip.o ../../src/lib/protocols/*.o] -I/../../src/include -I/../../src/lib -I/../libre -I/../../src/lib/third_party/include  -DHAVE_CONFIG_H -DNDPI_LIB_COMPILATION -DOPENDPI_NETFILTER_MODULE -DNDPI_DETECTION_SUPPORT_IPV6 -g  -Wno-declaration-after-statement
        \
        make  -C /lib/modules/4.9.0-11-amd64/build  M=$PWD modules -w;
        make[2]: Entering directory '/usr/src/linux-headers-4.9.0-11-amd64'
        grep: /lib/modules/4.9.0-11-amd64/build: Is a directory
        grep: /source/include/linux/skbuff.h: No such file or directory
          CC [M]  /home/xkubee/nDPI/ndpi-netfilter/src/main.o
        /home/xkubee/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_nat_do_chain’:
        /home/xkubee/nDPI/ndpi-netfilter/src/main.c:2146:37: error: ‘IP_CT_UNTRACKED’ undeclared (first use in this function)
             enum ip_conntrack_info ctinfo = IP_CT_UNTRACKED;
                                             ^~~~~~~~~~~~~~~
        /home/xkubee/nDPI/ndpi-netfilter/src/main.c:2146:37: note: each undeclared identifier is reported only once for each function it appears in
        At top level:
        /home/xkubee/nDPI/ndpi-netfilter/src/main.c:405:29: warning: ‘dbg_ipt_names’ defined but not used [-Wunused-variable]
         static struct dbg_ipt_names dbg_ipt_names [] = {
                                     ^~~~~~~~~~~~~
        /usr/src/linux-headers-4.9.0-11-common/scripts/Makefile.build:312: recipe for target '/home/xkubee/nDPI/ndpi-netfilter/src/main.o' failed
        make[5]: *** [/home/xkubee/nDPI/ndpi-netfilter/src/main.o] Error 1
        /usr/src/linux-headers-4.9.0-11-common/Makefile:1543: recipe for target '_module_/home/xkubee/nDPI/ndpi-netfilter/src' failed
        make[4]: *** [_module_/home/xkubee/nDPI/ndpi-netfilter/src] Error 2
        Makefile:152: recipe for target 'sub-make' failed
        make[3]: *** [sub-make] Error 2
        Makefile:8: recipe for target 'all' failed
        make[2]: *** [all] Error 2
        make[2]: Leaving directory '/usr/src/linux-headers-4.9.0-11-amd64'
        Makefile:50: recipe for target 'modules' failed
        make[1]: *** [modules] Error 2
        make[1]: Leaving directory '/home/xkubee/nDPI/ndpi-netfilter/src'
        Makefile:2: recipe for target 'all' failed
        make: *** [all] Error 2

## Additional context
Подскажите, пожалуйста, в чём проблема.  Библиотека nDPI собирается успешно, но без ndpi-netfilter использовать её не получится.

**Comment by vel21ripn** [comment]
Без исходников и конфига ядра оно не соберётся.
При сборке можно явно указать путь к ядру через KERNEL_DIR=

**Comment by kubeengineering** [comment]
Спасибо
Подхачил ndpi-netfilter/src/Makefile, добавил в него явно путь к ядру

Но проблема не ушла:

      root@debian-9-x64:/home/xkubee/nDPI/ndpi-netfilter# make
      make -C ipt
      make[1]: Entering directory '/home/xkubee/nDPI/ndpi-netfilter/ipt'
      make[1]: Nothing to be done for 'all'.
      make[1]: Leaving directory '/home/xkubee/nDPI/ndpi-netfilter/ipt'
      make -C src
      make[1]: Entering directory '/home/xkubee/nDPI/ndpi-netfilter/src'
      $xt_ndpi-y is [main.o ndpi_strcol.o ndpi_proc_parsers.o ndpi_proc_generic.o ndpi_proc_info.o  ndpi_proc_flow.o ndpi_proc_hostdef.o ndpi_proc_ipdef.o ../libre/regexp.o ../../src/lib/third_party/src/ndpi_md5.o ../../src/lib/third_party/src/ndpi_sha1.o ../../src/lib/third_party/src/ahocorasick.o ../../src/lib/third_party/src/libcache.o ../../src/lib/third_party/src/ndpi_patricia.o ../../src/lib/third_party/src/gcrypt_light.o ../../src/lib/third_party/src/btlib.o ../../src/lib/ndpi_main.o ../../src/lib/ndpi_utils.o ../../src/lib/ndpi_serializer.o ../../src/lib/ndpi_geoip.o ../../src/lib/protocols/*.o] -I/../../src/include -I/../../src/lib -I/../libre -I/../../src/lib/third_party/include  -DHAVE_CONFIG_H -DNDPI_LIB_COMPILATION -DOPENDPI_NETFILTER_MODULE -DNDPI_DETECTION_SUPPORT_IPV6 -g  -Wno-declaration-after-statement
      \
      make  -C /lib/modules/4.9.0-11-amd64/build/ M=$PWD modules -w;
      make[2]: Entering directory '/usr/src/linux-headers-4.9.0-11-amd64'
        CC [M]  /home/xkubee/nDPI/ndpi-netfilter/src/main.o
      /home/xkubee/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_nat_do_chain’:
      /home/xkubee/nDPI/ndpi-netfilter/src/main.c:2146:37: error: ‘IP_CT_UNTRACKED’ undeclared (first use in this function)
           enum ip_conntrack_info ctinfo = IP_CT_UNTRACKED;
                                           ^~~~~~~~~~~~~~~
      /home/xkubee/nDPI/ndpi-netfilter/src/main.c:2146:37: note: each undeclared identifier is reported only once for each function it appears in
      At top level:
      /home/xkubee/nDPI/ndpi-netfilter/src/main.c:405:29: warning: ‘dbg_ipt_names’ defined but not used [-Wunused-variable]
       static struct dbg_ipt_names dbg_ipt_names [] = {
                                   ^~~~~~~~~~~~~
      /usr/src/linux-headers-4.9.0-11-common/scripts/Makefile.build:312: recipe for target '/home/xkubee/nDPI/ndpi-netfilter/src/main.o' failed
      make[5]: *** [/home/xkubee/nDPI/ndpi-netfilter/src/main.o] Error 1
      /usr/src/linux-headers-4.9.0-11-common/Makefile:1543: recipe for target '_module_/home/xkubee/nDPI/ndpi-netfilter/src' failed
      make[4]: *** [_module_/home/xkubee/nDPI/ndpi-netfilter/src] Error 2
      Makefile:152: recipe for target 'sub-make' failed
      make[3]: *** [sub-make] Error 2
      Makefile:8: recipe for target 'all' failed
      make[2]: *** [all] Error 2
      make[2]: Leaving directory '/usr/src/linux-headers-4.9.0-11-amd64'
      Makefile:50: recipe for target 'modules' failed
      make[1]: *** [modules] Error 2
      make[1]: Leaving directory '/home/xkubee/nDPI/ndpi-netfilter/src'
      Makefile:2: recipe for target 'all' failed
      make: *** [all] Error 2

**Comment by vel21ripn** [comment]
С этим должно собираться. Коммит будет позже, т.к. сейчас тестируется обновление после merge.
````
diff --git a/ndpi-netfilter/src/main.c b/ndpi-netfilter/src/main.c
index 90aafac..4783469 100644
--- a/ndpi-netfilter/src/main.c
+++ b/ndpi-netfilter/src/main.c
@@ -58,6 +58,10 @@
 #include <net/netfilter/nf_nat.h>
 #include <linux/ktime.h>
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(4,12,0)
+#define IP_CT_UNTRACKED IP_CT_NUMBER
+#endif
+
 #define BT_ANNOUNCE
 
 #include "ndpi_config.h"
````

**Comment by kubeengineering** [comment]
Подхачил main.c, добавив то, что Вы посоветовали, собралось
Спасибо!
Я так понимаю, это изменение можно ждать в скором времени?

**Comment by vel21ripn** [comment]
Думаю, что через сутки.

**Comment by kubeengineering** [comment]
Изменения проверил. Теперь на Debian 9 утилита ndpi-netfilter устанавливается успешно.
Спасибо!
