### ISSUE TITLE
how to enable remotescan, qqlive protocols detection (not initialized by default)?

### ISSUE THREAD

**Issue by dinarsalem** [vel21ripn/nDPI#151]
I am trying to enable some protocols that are not initialized by default.
I followed: https://github.com/vel21ripn/nDPI/blob/flow_info-4/ndpi-netfilter/INSTALL
Tried:
  "echo init >/proc/net/xt_ndpi/proto" enable all protocols and set mark by ID and mask 0xff.

But noticed the protocols are enabled with custom names. Is there a way to enable it with the correct name?

Also, is there a way to enable only certain protocols, not all of them?

**Comment by dinarsalem** [comment]
I am noticing different behaviour in different versions:
The most recent version (commit hash 3ff5a9b05f344e05492586079e228dab43bd62b0)
 xt_ndpi v1.2 ndpi 4.5.0-4251-3ff5a9b0
is missing  skypecall/qqlive/remotescan

However, version   xt_ndpi v1.2 ndpi 4.3.0-3723-447265b9 (commit hash 447265b9c978aaf899e9ede55bc31e47af2b903c`) is not missing any. 

 I would like to know why support for the above was removed in the new version please?

**Comment by vel21ripn** [comment]
These protocols have been removed from the main project.
Several more protocols have recently been removed.

> I am trying to enable some protocols that are not initialized by default.

At the moment, disabling protocols is broken. This problem is on the list of works under the first number.
