### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by Comandante1977** [vel21ripn/nDPI#152]
## Describe the bug
make[1]: Entering directory '/opt/nDPI/ndpi-netfilter/src'
$xt_ndpi-y is [main.o ndpi_strcol.o ndpi_proc_parsers.o ndpi_proc_generic.o ndpi_proc_info.o  ndpi_proc_flow.o ndpi_proc_hostdef.o ndpi_proc_ipdef.o ../libre/regexp.o ../../src/lib/third_party/src/ndpi_md5.o ../../src/lib/third_party/src/ndpi_sha1.o ../../src/lib/third_party/src/ahocorasick.o ../../src/lib/third_party/src/libcache.o ../../src/lib/third_party/src/ndpi_patricia.o ../../src/lib/third_party/src/gcrypt_light.o ../../src/lib/third_party/src/btlib.o ../../src/lib/ndpi_main.o ../../src/lib/ndpi_utils.o ../../src/lib/ndpi_serializer.o ../../src/lib/ndpi_geoip.o ../../src/lib/protocols/*.o] -I/../../src/include -I/../../src/lib -I/../libre -I/../../src/lib/third_party/include  -DHAVE_CONFIG_H -DNDPI_LIB_COMPILATION -DOPENDPI_NETFILTER_MODULE -DNDPI_DETECTION_SUPPORT_IPV6 -g  -Wno-declaration-after-statement
\
make  -C /lib/modules/5.10.0-20-amd64/build M=$PWD modules -w;
make[2]: Entering directory '/usr/src/linux-headers-5.10.0-20-amd64'
  CC [M]  /opt/nDPI/ndpi-netfilter/src/main.o
/opt/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_net_init’:
/opt/nDPI/ndpi-netfilter/src/main.c:2872:26: error: ‘debug_printf’ undeclared (first use in this function); did you mean ‘seq_printf’?
 2872 |  ndpi_debug_print_init = debug_printf;
      |                          ^~~~~~~~~~~~
      |                          seq_printf
/opt/nDPI/ndpi-netfilter/src/main.c:2872:26: note: each undeclared identifier is reported only once for each function it appears in
/opt/nDPI/ndpi-netfilter/src/main.c:2873:26: error: ‘ndpi_lib_trace’ undeclared (first use in this function); did you mean ‘ndpi_list_struct’?
 2873 |  ndpi_debug_level_init = ndpi_lib_trace;
      |                          ^~~~~~~~~~~~~~
      |                          ndpi_list_struct
At top level:
/opt/nDPI/ndpi-netfilter/src/main.c:409:29: warning: ‘dbg_ipt_names’ defined but not used [-Wunused-variable]
  409 | static struct dbg_ipt_names dbg_ipt_names [] = {
      |                             ^~~~~~~~~~~~~

### Obtained behavior
Cant compile

## nDPI Environment (please complete the following information):
* OS name: Debian
* OS version: 11
* Architecture: arm64

**Comment by vel21ripn** [comment]
See e39b6ccd9343c9b66d5e6e5c79caa6aa2527d5bc
