### ISSUE TITLE
libxt_ndpi.so link error after iptables version 1.8.9 

### ISSUE THREAD

**Issue by Vigilans** [vel21ripn/nDPI#153]
After commit https://git.netfilter.org/iptables/commit/include/xtables.h?id=ef108943f69a6e20533d58823740d3f0534ea8ec (shipped in v1.8.9), the `_INIT` macro (convert `_init` function name to `libxt_ndpi_init`) is guarded by `XTABLES_INTERNAL`. Without `XTABLES_INTERNAL`, following error will occur during linking:
```
cc -shared -o libxt_ndpi.so libxt_ndpi.o;
/usr/bin/ld: libxt_ndpi.o: in function `_init':
libxt_ndpi.c:(.text+0x2fa0): multiple definition of `_init'; /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/crti.o:(.init+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: libxt_ndpi.so] Error 1
```
This is because `_init` name will not be renamed to `libxt_ndpi_init`, and collide with `_init` from `crti.o`.

**Comment by vel21ripn** [comment]
Thanks.
See 97acb7ade7c90a02a19f3ffe3beec0fbbe10610c
