### ISSUE TITLE
Request for clarification on installing nDPI Netfilter with xtables on Debian 11

### ISSUE THREAD

**Issue by houmie** [vel21ripn/nDPI#156]
Hello @vel21ripn

Thank you for this amazing project. Your project seems to be the only actively maintained nDPI Netfilter on the internet. 

The [INSTALL](https://github.com/vel21ripn/nDPI/blob/flow_info-4/ndpi-netfilter/INSTALL) is pretty good up to the paragraph of `3. Compile and install`.

> Finally, also as root, you should copy the iptables module into the corresponding directory. Usually this is "/lib/xtables" or "/usr/lib/xtables".

This part isn't clear to me. What do I need to do?  I have installed the following modules on Debian 11:
```
apt install xtables-addons-common
apt install xtables-addons-source
apt install module-assistant
module-assistant auto-install xtables-addons-source

```

But I still don't have any `/lib/xtables` nor `/usr/lib/xtables`. And where do I copy the iptables modules from?

My goal is to use nDPI-netfilter to block torrent traffic on my network.

`iptables -I FORWARD 1 -m ndpi --proto bittorrent -j REJECT`

Many Thanks,

**Comment by houmie** [comment]
I actually got it working. Simply by running `make install` it will automatically copy/link them in the xtables folder, which happens to be under `/usr/lib/x86_64-linux-gnu/xtables/` in Debian.

It works great! Thanks for the great work. 

I leave this question open for now, to see if others have a comment.

**Comment by vel21ripn** [comment]
Path for extensions of iptables may be found via command
```
pkg-config --variable=xtlibdir xtables
```
If we compiled new version of iptables (in separate directory) then use
```
export PKG_CONFIG_PATH=...../iptables/iptables
make -C ipt install DESTDIR=$PKGDIR
```

**Comment by houmie** [comment]
Yes, perfect.  

I ran `pkg-config --variable=xtlibdir xtables` under Debian 11 and it returned `/usr/lib/x86_64-linux-gnu/xtables`.

That's the path `make install` found automatically. 👍🏼 

I have one more question please. What is the purpose of this optional part below? In what way is this utilised?

```
cd src/lib
make ndpi_network_list.c.inc
```

Will `make modules_install` and `make install` find the compiled `ndpi_network_list.c.inc` automatically and make use of it? Thanks

**Comment by vel21ripn** [comment]
The ndpi_network_list.c.inc file has a lot of dependencies.
It is generated using the ndpi_network_list_compile program from the ndpi_network_list_*.yaml files.
Running "make -C src/lib ndpi_network_list.c.inc" is much easier than trying to explain it to autoconf.
