### ISSUE TITLE
Make throws an error that skbuff.h could not be found

### ISSUE THREAD

**Issue by houmie** [vel21ripn/nDPI#157]
## Describe the bug
When running make in `~/nDPI/ndpi-netfilter` it throws an error that skbuff.h could not be found:

```
make -C ipt
make[1]: Entering directory '/home/admin/nDPI/ndpi-netfilter/ipt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/admin/nDPI/ndpi-netfilter/ipt'
make -C src
make[1]: Entering directory '/home/admin/nDPI/ndpi-netfilter/src'
grep: /lib/modules/5.10.0-21-amd64/build/source/include/linux/skbuff.h: No such file or directory
```

When searching for it `sudo find / -name skbuff.h` I was able to find it under: `/usr/src/linux-headers-5.10.0-21-common/include/linux/skbuff.h`

### Expected behavior
It should find the file.

### Obtained behavior
It doesn't find the file.

## nDPI Environment (please complete the following information):
* OS name: Debian
* OS version: 11
* Architecture: amd64
* nDPI version or commit hash: ac0ad66b3644a43cbaa821a6135d3e610f8b2c1a
* nDPI compilation flags used: if you are building from source 

```
git clone https://github.com/vel21ripn/nDPI.git
cd nDPI
./autogen.sh
cd src/lib
make ndpi_network_list.c.inc
cd ..
cd ..
cd ndpi-netfilter
make
```

**Comment by houmie** [comment]
I tried to set these variables in the make file, but it didn't help.

```
KERNELDIR=/usr/src/linux-headers-$(uname -r)
CPPFLAGS+=-I$(KERNELDIR)/include
```

I ended up copying them over to fix this issue. Not great, I know.

```
sudo mkdir -p /lib/modules/5.10.0-21-amd64/build/source/include/linux/
sudo cp -r /usr/src/linux-headers-5.10.0-21-common/include/linux/* /lib/modules/5.10.0-21-amd64/build/source/include/linux/
```

But I discovered one last Warning. 
```
Warning: modules_install: missing 'System.map' file. Skipping depmod.
```

Full:
```
MODPOST /home/admin/nDPI/ndpi-netfilter/src/Module.symvers
  CC [M]  /home/admin/nDPI/ndpi-netfilter/src/xt_ndpi.mod.o
  LD [M]  /home/admin/nDPI/ndpi-netfilter/src/xt_ndpi.ko
make[2]: Leaving directory '/usr/src/linux-headers-5.10.0-21-amd64'
make[1]: Leaving directory '/home/admin/nDPI/ndpi-netfilter/src'
make -C src modules_install
make[1]: Entering directory '/home/admin/nDPI/ndpi-netfilter/src'
make -C /lib/modules/5.10.0-21-amd64/build M=$PWD modules_install;
make[2]: Entering directory '/usr/src/linux-headers-5.10.0-21-amd64'
  INSTALL /home/admin/nDPI/ndpi-netfilter/src/xt_ndpi.ko
  DEPMOD  5.10.0-21-amd64
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[2]: Leaving directory '/usr/src/linux-headers-5.10.0-21-amd64'
depmod -a;
make[1]: Leaving directory '/home/admin/nDPI/ndpi-netfilter/src'
make -C ipt install
make[1]: Entering directory '/home/admin/nDPI/ndpi-netfilter/ipt'
if [ -n "/usr/lib/x86_64-linux-gnu/xtables" -a -d "/usr/lib/x86_64-linux-gnu/xtables" ]; then install -v libxt_ndpi.so /usr/lib/x86_64-linux-gnu/xtables; ln -fs libxt_ndpi.so /usr/lib/x86_64-linux-gnu/xtables/libxt_NDPI.so ; else echo "No pkg-config --variable=xtlibdir xtables"; fi
'libxt_ndpi.so' -> '/usr/lib/x86_64-linux-gnu/xtables/libxt_ndpi.so'
make[1]: Leaving directory '/home/admin/nDPI/ndpi-netfilter/ipt'
```

Thanks

**Comment by vel21ripn** [comment]
I don't have debian. Slackware and ubuntu only.
I assume source code is in /usr/src/kts2/linux-x.xx directory, object files and configuration are in /usr/src/kts2/obj-x.xx directory, iptables source code is in /usr directory /src/kts2/iptables/include.
Assembly for different kernel versions is done with scripts like

```
make -j9 KERNEL_DIR=/usr/src/kts2/obj-6.1 IPTINC=/usr/src/kts2/iptables/include
```
I will correct the error with the non-existent skbuff.h in the near future.

**Comment by houmie** [comment]
@vel21ripn Thanks for that. If you need me to test the pull request, I'm happy to volunteer. I love your project. 
Ubuntu is based on Debian. They should be quite similar.

I researched about the warning `Warning: modules_install: missing 'System.map' file. Skipping depmod.`.  It seems this happens because `depmod -a` should happen AFTER `modules_install`. [This](https://stackoverflow.com/a/57523643/92153) is what I found. 

Do you think this warning is a serious issue?

**Comment by vel21ripn** [comment]
The "depmod -a" command allows you to find errors related to undefined references, which should not be.
As a developer, this is important to me. In other cases, you may not need to run depmod at all.

**Comment by Vigilans** [comment]
`KERNEL_DIR` default to be `/lib/modules/$(uname -r)/build`, so `$KERNEL_DIR/source` is `/lib/modules/$(uname -r)/build/source`

I fixed it by replacing
```
$(shell grep -qc userid $(KERNEL_DIR)/source/include/linux/skbuff.h)
```
with
```
$(shell grep -qc userid $(shell dirname $(KERNEL_DIR))/source/include/linux/skbuff.h)
```
