### ISSUE TITLE
protocol line and linecall not recognised by iptables 

### ISSUE THREAD

**Issue by clebig** [vel21ripn/nDPI#165]
Dear Vitaly,

I'm facing what appears to be a bug when trying to call proto 'line' and 'linecall'. I'm using the branch flow_info-4 ([fbb2104](https://github.com/vel21ripn/nDPI/commit/fbb2104d125a13db3b8c7fdc34ea0e3fcfe92d12)) as last commit on a Debian Bullseye 11.7 up to date that runs the kernel 5.10 provided by Debian and iptables 1.8.7-1.

```
root@LTgateway:~/bin/tc-viewer# iptables -t mangle -I FORWARD 15 --proto linecall -j MARK --set-mark 0xa
iptables v1.8.7 (nf_tables): unknown protocol "linecall" specified
Try `iptables -h' or 'iptables --help' for more information.

```
Everything works fine with all the 43 other protocols I use in my firewall rules.

Thank you for your great project.

Clément.

**Comment by vel21ripn** [comment]
Missing "-m ndpi" before "--proto linecall"

**Comment by clebig** [comment]
Oh nooo, I'm so dumb ! Sorry for this.

Le jeu. 4 mai 2023 à 22:38, Vitaly Lavrov ***@***.***> a
écrit :
