### ISSUE TITLE
modify iptables extension for better performance

### ISSUE THREAD

**Issue by BrainSlayer** [vel21ripn/nDPI#166]
as shown here in this partially patch https://github.com/mirror/dd-wrt/commit/32397eedf2864b96c6ddbda88678c1ea3932fa23
its usuall to initialize protocol and risk just in the match method. otherwise its initialized each time iptables is called, even if ndpi isnt used. this is important if iptables is staticly linked with its extensions (commonly the case for embedded systems)
if you have alot of single iptables calls in a firewall script it will significant increase performance of running such a script

i can make a pull request with a complete patch based on the upstream source if required. but its really simple to make. not sure if my effort is required here

another issue is that the init method fails and iptables failes at all to initialize and is not working anymore if ndpi isnt loaded. this is also covered by this method and concept

**Comment by vel21ripn** [comment]
Your idea is good.
But then it makes sense to read the list of protocols in the same way.

**Comment by BrainSlayer** [comment]
@vel21ripn: exact and thats what i also wrote in my suggestion. the patch above does not do that since i hardcoded the protocol list in my variant of the iptables module. so this is just a example for better understanding

**Comment by BrainSlayer** [comment]
btw. since the risk list may change (the a and d attribute). we usually need to consider the use of iptables-restore. here in this case the risk list is just readed one time, but usually we need to reread it on each match instance. but to be honest. i dont even know that he 'd' and 'a' really means here

**Comment by vel21ripn** [comment]
a - allow, d - deny. The description is in the ndpi-netfilter/INSTALL. We can ignore some of the risks.
Reading the /proc/net/xt_ndpi/proto file has become a necessity for implementing user-defined protocols.

**Comment by BrainSlayer** [comment]
yes like i wrote in my initial text, initializing the protocols is neccessary. but we should relocated from init to a "only if needed" usecase.
