### ISSUE TITLE
Lost of packet filtering on bittorrent

### ISSUE THREAD

**Issue by bbqaaq** [vel21ripn/nDPI#17]
Hi! Sorry for using the issue tracker to ask question here.

Recently im trying to filter bittorrent on my Ubuntu 16.04 server (which is a strongswan vpn server). After a few days effort of solution searching, i've found your repository, which is nice to use with and base the modern DPI library nDPI (compared with those ipp2p and l7-filter).

However, the performance of bittorrent filtering is not that effective as expected. Some bittorrent packet is being dropped, but still many of them are passed as they are "unknown" packet.

![screen shot 2017-07-26 at 11 56 30](https://user-images.githubusercontent.com/6056605/28603969-02934ed0-71fa-11e7-8927-7fd998f597ec.png)

The photo attached is the snapshot when the user have tried to bt through the vpn for a few seconds.
As in the photo, you will there are lots of packet going to the "unknown" rules. If I blocked the unknown packets, there will be a mess. (as you mention in the installation instruction). However, if i remove it, the bittorrent will able to be continued as normal.

Any idea/solution can help? Thanks!

**Comment by k0ste** [comment]
1. Add ndpi rules to `mangle`, not `filter`.
2. You should match all traffic for properly dissector work.
```                                             
iptables -t mangle -A PREROUTING -m ndpi --all   
iptables -t mangle -A POSTROUTING -m ndpi --all  
```
And then add your p2p proto rules.

**Comment by bbqaaq** [comment]
![screen shot 2017-07-26 at 12 16 12](https://user-images.githubusercontent.com/6056605/28604307-492d0668-71fc-11e7-989a-160ed429e371.png)

So i should add the bittorrent rules to mangle tables also?
I see its dropping some bittorrent packet but still my bittorrent client is running normally.

**Comment by k0ste** [comment]
Yep, after `all`. If you want to drop this packets, I think the `raw` table is better for this. I'm not drop any packets, I think it's dirty and useless. I recommend add priorities and attach qdisc's.

```
[k0ste@Router1 ~]$ uptime              
 11:19:49 up 17 days, 16:44,  1 user,  load average: 0.05, 0.28, 0.27
[k0ste@Router1 ~]$ sudo iptables -nvL -t mangle | grep torrent
1366M  514G NDPI       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ndpi protocol bittorrent NDPI set MARK  set 0xf
1988M 2591G NDPI       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ndpi protocol bittorrent NDPI set MARK  set 0xf
```

**Comment by bbqaaq** [comment]
Im so sorry im not those kind of profession in system development and asking some dumb question.
May i ask if currently your bittorrent is adding to "mangle" table and which chain you are using?

**Comment by k0ste** [comment]
See command I present:
`iptables -nvL -t mangle | grep torrent`
This show only mangle table.

`PREROUTING` chain - All packets entering the system in any way, before routing decides whether the packet is to be forwarded (FORWARD chain) or is destined locally (INPUT chain).
`POSTROUTING` chain - All packets leaving the system go through this chain.

So, for matching bittorrent in manlge you should add (with your action, of course):
```
iptables -t mangle -A PREROUTING -m ndpi  --all 
iptables -t mangle -A PREROUTING -m ndpi  --bittorrent  -j NDPI --value 0xf --set-mark
iptables -t mangle -A PREROUTING -m ndpi  --unknown  -j NDPI --value 0xf --set-mark
iptables -t mangle -A POSTROUTING -m ndpi  --all 
iptables -t mangle -A POSTROUTING -m ndpi  --bittorrent  -j NDPI --value 0xf --set-mark
iptables -t mangle -A POSTROUTING -m ndpi  --unknown  -j NDPI --value 0xf --set-mark
```

Hope this example helps.

**Comment by bbqaaq** [comment]
Thanks so much, seems its matching those packet now. But seems after i do the matching in nat table, the packet is not rejected/dropped, and the user can still do bt.

As stated you don't suggest me to drop, so do you have some more suggestion on how i can block the bt?

Once again, sorry for dumb question and thanks so much.

![screen shot 2017-07-26 at 13 24 24](https://user-images.githubusercontent.com/6056605/28605729-d5558378-7205-11e7-9878-5f9edd5baea2.png)

**Comment by k0ste** [comment]
> Thanks so much, seems its matching those packet now. But seems after i do the matching in nat table, the packet is not rejected/dropped, and the user can still do bt.

You should not use in `nat` table, because `nat` going after `mangle`.

> As stated you don't suggest me to drop, so do you have some more suggestion on how i can block the bt?

I suggest to you use QoS. If you don't know what it is, I recommend you to do nothing before you learn LARTC.
If you don't care what is going on and just need to drop `bittorrent`, execute this:

```
iptables -t mangle -A PREROUTING -m ndpi --all
iptables -t mangle -A PREROUTING -m ndpi --bittorrent -j DROP
iptables -t mangle -A PREROUTING -m ndpi --unknown
iptables -t mangle -A POSTROUTING -m ndpi --all
iptables -t mangle -A POSTROUTING -m ndpi --bittorrent -j DROP
iptables -t mangle -A POSTROUTING -m ndpi --unknown
```

Cheers.

**Comment by bbqaaq** [comment]
Thousands thanks for your help! Currently i may just need a quick solution, so maybe i will learn more about QoS and LARTC later.

But still, after adding your suggested rules, some bt packet are still recognized as 'unknown' and get pass the rules.

So maybe i can suspect now that there are still bittorrent packet that are missed?

![screen shot 2017-07-26 at 16 41 15](https://user-images.githubusercontent.com/6056605/28612396-c2af0548-7221-11e7-868e-bfced4c4186b.png)
![screen shot 2017-07-26 at 16 42 16](https://user-images.githubusercontent.com/6056605/28612397-c2b0fdb2-7221-11e7-9d8e-69bcc12244cb.png)

**Comment by k0ste** [comment]
You should run `conntrack -F` every time when you change something in `ndpi`, because for many dissectors work we should know about all (in and out) connections.
Or just reboot.

Also, order of load modules to kernel is important, I described it here https://github.com/vel21ripn/nDPI/issues/6#issuecomment-255913027

**Comment by k0ste** [comment]
@bbqaaq close if resolved.

**Comment by bbqaaq** [comment]
Im so sorry with such a late reply, as I was busy on another project.

Indeed base on you suggestion, the problem isn't get fixed, some packet still getting pass the rules, and recognized as "unknown" packet. But I guess the problem isn't on this repo, i think basically it's ntop/ndpi problem, as i used the newest repo over there, with their ndpi reader, similar problem is arised. Probably ndpi cannot recognize all the bittorrent packet.

See if i will submit an issue over there. Thanks so much @k0ste

**Comment by k0ste** [comment]
@bbqaaq, you should try to increase [bt_hash_size](https://github.com/vel21ripn/nDPI/blob/netfilter/ndpi-netfilter/INSTALL#L194).
As you can see, this is increases quality of dissection of bittorrent.

```
[k0ste@WorkStation bin]$ ./ndpiReader -i ~/bond.pcap | grep -E '(BitTorrent|Unknown)'
	Unknown              packets: 5833063       bytes: 5396718972    flows: 13297        
	BitTorrent           packets: 3897212       bytes: 3495930474    flows: 21162 
```
```
[k0ste@WorkStation bin]$ ./ndpiReader -i ~/bond.pcap -B 32 | grep -E '(BitTorrent|Unknown)'
	Unknown              packets: 1589116       bytes: 1357617310    flows: 7915         
	BitTorrent           packets: 8151681       bytes: 7543434705    flows: 26555
```

**Comment by elico** [comment]
@k0ste I didn't understood if it's a compilation settings or a module configuration.
Also where and when do I need to set the bt_hash_size?
after I load the xt_ndpi? on the modprobe line?
Somewhere in the /proc/... files?

**Comment by k0ste** [comment]
@elico this is module param.

**Comment by elico** [comment]
@k0ste so I just compiled a kmod for CentOS 7 and I want to understand where should I put the parameter there.
Can you please give me an example on how and where to put it?
Are you talking about something like what mentioned at:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Setting_Module_Parameters.html
?
And for persistent examples I think there are couple here:
https://wiki.archlinux.org/index.php/Kernel_modules

**Comment by k0ste** [comment]
> Are you talking about something like what mentioned at

Yes.

**Comment by elico** [comment]
@k0ste ok Thanks.
