### ISSUE TITLE
Валятся тесты из папки tests после сборки

### ISSUE THREAD

**Issue by omikhaylov** [vel21ripn/nDPI#170]
Собираю пакет для Debian.
Debhelper автоматически подхватывает на этапе dh_auto_test (если не прописать override) тесты из папки tests. Тесты проходят и разваливают сборку. Лог во вложении.

Следует просто отключить автотесты или все-таки некая проблема присутствует и надо решать?
[test-suite.log](https://github.com/vel21ripn/nDPI/files/11770299/test-suite.log)

**Comment by vel21ripn** [comment]
Ошибки несовпадения "LRU cache bittorrent"  в 4-х тестах закономерны, т.к. bittorrent.c сильно отличается.
В последних коммитах  еще 3 теста завершаются неудачей из-за несовпадения числа вызовов.
Если будет время попробую понять откуда оно берется.
