### ISSUE TITLE
Question about Flow Risk

### ISSUE THREAD

**Issue by Anthony-76** [vel21ripn/nDPI#171]
Hi, 

Maybe It's not the good place but I ask the question

Int the NDPI documentation there is NDPI_URL_POSSIBLE_XSS, NDPI_URL_POSSIBLE_XSS, etc... 

How to implement these flow risks and how does it work?

Thank you for your help and tips

Best regards
Anthony

**Comment by vel21ripn** [comment]
libinjection is not used in kernel mode.

**Comment by Anthony-76** [comment]
Hi,

Thank you for your answer. 

Last question, is there in the future the possibility to have this feature?

**Comment by vel21ripn** [comment]
I have not yet planned to add this code.

**Comment by Anthony-76** [comment]
Ok, no problem, your job is already nice
