### ISSUE TITLE
CentOS 7 and Fedora 26 kmod testers are needed.

### ISSUE THREAD

**Issue by elico** [vel21ripn/nDPI#18]
I took the work of @gsanchietti and @filippocarletti at:
https://github.com/NethServer/xt_ndpi-kmod

And converted it into a docker build container which I have tested to on both CentOS 7 and Fedora 26.
More details are at the [wiki](https://github.com/vel21ripn/nDPI/wiki) and we need testers that want to help and verify if these modules run as expected on other systems then my test lab.
For CentOS 7 there is a repository and the RPM can be downloaded directly from:
http://ngtech.co.il/repo/centos/7/x86_64/kmod-xt_ndpi-2.0.1-2.el7.centos.x86_64.rpm

**Comment by hisham2630** [comment]
how can i build it for openwrt?

**Comment by elico** [comment]
@hisham2630 It depends on couple factors but you first need to make sure that the device you want to use it on can handle this module.
It means that it has the right CPU the right amount of RAM and DISK.
It is possible that you will not be able to simply build it for OpenWRT for use on a specific device but might be able to build it for x86 or x86_64 devices.
I have not tested it on OpenWRT since this kind of a module will only work properly on very specific devices.
The only embedded device that I have seen which have a similar module is the Ubiquiti  Edge Router but it is guaranteed to reduce the performance of these devices(MIPS64, 512MB RAM) from 1 million packets per second to something below 200 thousand packets per second.. so before you try to build it make sure you really want and need it.

**Comment by hisham2630** [comment]
hi,thanks
i had compiled betolji version and it compiled successfully,also i don't have a high speed connection, i have only 1 Mbps.
i tried this make file but it will produce a lots of errors, so i did change the source to use the latest version,there's no errors, but only config.h is missing.

**Comment by elico** [comment]
@hisham2630 try to run the betoji version in production on a "lively" system and you will see the difference.
I have tested every DPI module and proxy I got my hands on in the last couple years and the only one which worked as expected is vendors and vel21ripn.
If you have only 1 Mbps it will change the basic requirements of the library and the module.
This module requires at-least 32 bit CPU with proper kernel and with proper connection tracking extensions to work.
I am not an expert in build tools but any DPI requires more then a 16bit MIPS compatible or any similar CPU.
If it works for you well with betoji package stick with it and see how far you can take it.

**Comment by hisham2630** [comment]
but from what i know vel21ripn version is most updated with new protocols and some fix's
my router is tp-link-w8970,from what i know openwrt dose support many libraries.
 i think vel21ripn version will work but i need a proper settings for compiler.

**Comment by elico** [comment]
@hisham2630 I would recommend you to first ask at OpenWRT if there is any support to this set of modules and if so then move one step forward and try to find out what libraries it might require to build based on what is being used on the Debian\Ubuntu\CentOS\Fedora and other builds.
The closest linux distro if at all to OpenWRT is Alpine Linux but you still are asking in the wrong place since **_This_** thread\issue is related to CentOS\Fedora and also you really need someone that know's how to work with OpenWRT specifically.

**Comment by hisham2630** [comment]
thanks for your help, yeah i did opened a thread in lede forum but still no much help.
