### ISSUE TITLE
Question about echo command

### ISSUE THREAD

**Issue by hcvs010164** [vel21ripn/nDPI#181]
I often use "echo cmd" to add some IP/hostnames. (For example: echo 'Google:www.google.com' >/proc/net/xt_ndpi/host_proto)
Here are some of my questions:

Q1. I read the contents of example/protos.txt. Will it be possible to support adding nBPF and IPv6 addresses through "echo cmd" in the future?

Q2. Is there a way to specify a contract file like ndpiReader does? Use this file to update and reduce "echo cmd" times.

Thank you!

**Comment by vel21ripn** [comment]
`Q1. I read the contents of example/protos.txt. Will it be possible to support adding nBPF and IPv6 addresses through "echo cmd" in the future?`
nBPF is needed to filter packets in userspace mode. nDPI-netfilter works in kernel-mode. nBPF is not needed.
Adding ipv6 addresses will be done in the near future.
`Q2. Is there a way to specify a contract file like ndpiReader does? Use this file to update and reduce "echo cmd" times.`
There are no plans to store settings in a file.
procfs is the only legal way to interact with a kernel module.
