### ISSUE TITLE
Seeking Advice on Updating nDPI on VPS Servers

### ISSUE THREAD

**Issue by houmie** [vel21ripn/nDPI#182]
I have a number of VPS servers set up with this wonderful nDPI project, and it works very well.

Given the recent merge of the dev branch into the main branch, I would like to deploy the latest version on my servers.

What is the best strategy to achieve this? 

Do I just recompile the latest version like this and it will be fine?

```
git clone --single-branch https://github.com/vel21ripn/nDPI.git
cd nDPI
./autogen.sh --with-only-libndpi
make
cd ndpi-netfilter
make
sudo make modules_install
sudo make install
sudo modprobe xt_ndpi
echo "xt_ndpi" | sudo tee /etc/modules >/dev/null
```

Or is there an uninstall process that I may have missed?

Thank you

**Comment by vel21ripn** [comment]
I don't see any errors.
No need to uninstall.
