### ISSUE TITLE
unresolved symbol __aarch64_ldadd8_sync on aarch64

### ISSUE THREAD

**Issue by BrainSlayer** [vel21ripn/nDPI#183]
https://github.com/vel21ripn/nDPI/blob/36d25acd43b92ce6d2d7e9f8d6bb055a819cee94/src/lib/ndpi_main.c#L264

as shown in the link above there is a are kernel api incompatible reference to a atomic function (__sync_fetch_and_add) which leads gcc to generate code which creates references to libgcc on some platforms (reproduceable on aarch64).

solution one. use atomic_add instead
solution two. remove the entire atomic function including the inrement of the memory counter. the only function which make use of it 
is ndpi_get_tot_allocated_memory(). but this function is not referenced by any code. 

same must be done it ndpi_malloc and ndpi_calloc (in ndpi_calloc there is even a bug since the memory counter is increased 2 times)

**Comment by vel21ripn** [comment]
Thank you for the detailed bug report.
It turned out that I missed moving part of the code to the ndpi_memory.c file and, in addition to problems with __sync_fetch_and_add(), code duplication was detected.
I can start fixing the errors after the New Year holidays are over.

**Comment by BrainSlayer** [comment]
yes i know. discovered the same thing and fixed it locally. but since i dont know what your approach was i havent made a pull request yet

**Comment by vel21ripn** [comment]
I removed the use of ndpi_tot_allocated_memory from kernel mode.

**Comment by BrainSlayer** [comment]
looks sane. i will check
