### ISSUE TITLE
host_proto wildcard options.

### ISSUE THREAD

**Issue by netcons** [vel21ripn/nDPI#193]
When adding a default host_proto or a domain risk host_proto item, the module match's:  ***domain.com**

```
echo "add_custom domain_blacklist" > /proc/net/xt_ndpi/proto
echo "-domain_blacklist:*" > /proc/net/xt_ndpi/host_proto
echo "domain_blacklist:domain.com" > /proc/net/xt_ndpi/host_proto
iptables -A OUTPUT -m ndpi --proto domain_blacklist -j LOG --log-prefix domain_blacklist:
```

```
echo "add_custom domain_blacklist" > /proc/net/xt_ndpi/proto
echo "-domain_blacklist:*" > /proc/net/xt_ndpi/host_proto
echo "domain_blacklist:RISK_DOMAIN_domain.com" > /proc/net/xt_ndpi/host_proto
iptables -A OUTPUT -m ndpi --all --risk 27 -j LOG --log-prefix domain_blacklist:
```

At present this causes **gooddomain.com** and **baddomain.com** to match.

Could it be configured? to rather match: **domain.com** and ***.domain.com**

**Comment by vel21ripn** [comment]
If the hostname begins with a "|" character, a match is checked against the beginning of the string.
If the hostname ends with a "|" character, a match is made to the end of the string.
"|name|" this is an exact string match.

**Comment by netcons** [comment]
Thank you.
