### ISSUE TITLE
These are some protocols updated in the new version of ndpi_network_list_compile.h, please update them.

### ISSUE THREAD

**Issue by wlshdjj** [vel21ripn/nDPI#196]
`--- a/src/lib/ndpi_network_list_compile.h	2024-06-10 21:46:50.000000000 +0800
+++ b/src/lib/ndpi_network_list_compile.h	2024-06-22 18:51:46.353270000 +0800
@@ -32,7 +32,7 @@ _P(NDPI_PROTOCOL_VMWARE),
 _P(NDPI_PROTOCOL_MAIL_SMTPS),
 _P(NDPI_PROTOCOL_DTLS),
 _P(NDPI_PROTOCOL_UBNTAC2),
-_P(NDPI_PROTOCOL_KONTIKI),
+_P(NDPI_PROTOCOL_BFCP),
 _P(NDPI_PROTOCOL_YANDEX_MAIL),
 _P(NDPI_PROTOCOL_YANDEX_MUSIC),
 _P(NDPI_PROTOCOL_GNUTELLA),
@@ -54,12 +54,12 @@ _P(NDPI_PROTOCOL_RTSP),
 _P(NDPI_PROTOCOL_MAIL_IMAPS),
 _P(NDPI_PROTOCOL_ICECAST),
 _P(NDPI_PROTOCOL_CPHA),
-_P(NDPI_PROTOCOL_PPSTREAM),
+_P(NDPI_PROTOCOL_IQIYI),
 _P(NDPI_PROTOCOL_ZATTOO),
 _P(NDPI_PROTOCOL_YANDEX_MARKET),
 _P(NDPI_PROTOCOL_YANDEX_DISK),
 _P(NDPI_PROTOCOL_DISCORD),
-_P(NDPI_PROTOCOL_TVUPLAYER),
+_P(NDPI_PROTOCOL_ADOBE_CONNECT),
 _P(NDPI_PROTOCOL_MONGODB),
 _P(NDPI_PROTOCOL_PLURALSIGHT),
 _P(NDPI_PROTOCOL_YANDEX_CLOUD),
@@ -72,7 +72,7 @@ _P(NDPI_PROTOCOL_NATS),
 _P(NDPI_PROTOCOL_AMONG_US),
 _P(NDPI_PROTOCOL_YAHOO),
 _P(NDPI_PROTOCOL_DISNEYPLUS),
-_P(NDPI_PROTOCOL_GOOGLE_PLUS),
+_P(NDPI_PROTOCOL_HART_IP),
 _P(NDPI_PROTOCOL_IP_VRRP),
 _P(NDPI_PROTOCOL_STEAM),
 _P(NDPI_PROTOCOL_HALFLIFE2),
@@ -127,7 +127,7 @@ _P(NDPI_PROTOCOL_GOOGLE_MAPS),
 _P(NDPI_PROTOCOL_YOUTUBE),
 _P(NDPI_PROTOCOL_SKYPE_TEAMS),
 _P(NDPI_PROTOCOL_GOOGLE),
-_P(NDPI_PROTOCOL_RPC),
+_P(NDPI_PROTOCOL_MS_RPCH),
 _P(NDPI_PROTOCOL_NETFLOW),
 _P(NDPI_PROTOCOL_SFLOW),
 _P(NDPI_PROTOCOL_HTTP_CONNECT),
@@ -149,7 +149,7 @@ _P(NDPI_PROTOCOL_APPLE_ITUNES),
 _P(NDPI_PROTOCOL_RADIUS),
 _P(NDPI_PROTOCOL_WINDOWS_UPDATE),
 _P(NDPI_PROTOCOL_TEAMVIEWER),
-_P(NDPI_PROTOCOL_TUENTI),
+_P(NDPI_PROTOCOL_EGD),
 _P(NDPI_PROTOCOL_LOTUS_NOTES),
 _P(NDPI_PROTOCOL_SAP),
 _P(NDPI_PROTOCOL_GTP),
@@ -157,7 +157,7 @@ _P(NDPI_PROTOCOL_WSD),
 _P(NDPI_PROTOCOL_LLMNR),
 _P(NDPI_PROTOCOL_TOCA_BOCA),
 _P(NDPI_PROTOCOL_SPOTIFY),
-_P(NDPI_PROTOCOL_MESSENGER),
+_P(NDPI_PROTOCOL_FACEBOOK_MESSENGER),
 _P(NDPI_PROTOCOL_H323),
 _P(NDPI_PROTOCOL_OPENVPN),
 _P(NDPI_PROTOCOL_NOE),
@@ -182,11 +182,11 @@ _P(NDPI_PROTOCOL_AMAZON),
 _P(NDPI_PROTOCOL_EBAY),
 _P(NDPI_PROTOCOL_CNN),
 _P(NDPI_PROTOCOL_MEGACO),
-_P(NDPI_PROTOCOL_REDIS),
+_P(NDPI_PROTOCOL_RESP),
 _P(NDPI_PROTOCOL_PINTEREST),
 _P(NDPI_PROTOCOL_VHUA),
 _P(NDPI_PROTOCOL_TELEGRAM),
-_P(NDPI_PROTOCOL_VEVO),
+_P(NDPI_PROTOCOL_COD_MOBILE),
 _P(NDPI_PROTOCOL_PANDORA),
 _P(NDPI_PROTOCOL_QUIC),
 _P(NDPI_PROTOCOL_ZOOM),
@@ -201,7 +201,7 @@ _P(NDPI_PROTOCOL_WECHAT),
 _P(NDPI_PROTOCOL_MPEGTS),
 _P(NDPI_PROTOCOL_SNAPCHAT),
 _P(NDPI_PROTOCOL_SINA),
-_P(NDPI_PROTOCOL_HANGOUT_DUO),
+_P(NDPI_PROTOCOL_GOOGLE_MEET),
 _P(NDPI_PROTOCOL_IFLIX),
 _P(NDPI_PROTOCOL_GITHUB),
 _P(NDPI_PROTOCOL_BJNP),
@@ -235,7 +235,7 @@ _P(NDPI_PROTOCOL_PLAYSTATION),
 _P(NDPI_PROTOCOL_PASTEBIN),
 _P(NDPI_PROTOCOL_LINKEDIN),
 _P(NDPI_PROTOCOL_SOUNDCLOUD),
-_P(NDPI_PROTOCOL_CSGO),
+_P(NDPI_PROTOCOL_VALVE_SDR),
 _P(NDPI_PROTOCOL_LISP),
 _P(NDPI_PROTOCOL_DIAMETER),
 _P(NDPI_PROTOCOL_APPLE_PUSH),
@@ -354,7 +354,68 @@ _P(NDPI_PROTOCOL_HAPROXY),
 _P(NDPI_PROTOCOL_RMCP),
 _P(NDPI_PROTOCOL_CAN),
 _P(NDPI_PROTOCOL_PROTOBUF),
-_P(NDPI_PROTOCOL_ETHEREUM)
+_P(NDPI_PROTOCOL_ETHEREUM),
+_P(NDPI_PROTOCOL_TELEGRAM_VOIP),
+_P(NDPI_PROTOCOL_SINA_WEIBO),
+_P(NDPI_PROTOCOL_TESLA_SERVICES),
+_P(NDPI_PROTOCOL_PTPV2),
+_P(NDPI_PROTOCOL_RTPS),
+_P(NDPI_PROTOCOL_OPC_UA),
+_P(NDPI_PROTOCOL_S7COMM_PLUS),
+_P(NDPI_PROTOCOL_FINS),
+_P(NDPI_PROTOCOL_ETHERSIO),
+_P(NDPI_PROTOCOL_UMAS),
+_P(NDPI_PROTOCOL_BECKHOFF_ADS),
+_P(NDPI_PROTOCOL_ISO9506_1_MMS),
+_P(NDPI_PROTOCOL_IEEE_C37118),
+_P(NDPI_PROTOCOL_ETHERSBUS),
+_P(NDPI_PROTOCOL_MONERO),
+_P(NDPI_PROTOCOL_DCERPC),
+_P(NDPI_PROTOCOL_PROFINET_IO),
+_P(NDPI_PROTOCOL_HISLIP),
+_P(NDPI_PROTOCOL_UFTP),
+_P(NDPI_PROTOCOL_OPENFLOW),
+_P(NDPI_PROTOCOL_JSON_RPC),
+_P(NDPI_PROTOCOL_WEBDAV),
+_P(NDPI_PROTOCOL_APACHE_KAFKA),
+_P(NDPI_PROTOCOL_NOMACHINE),
+_P(NDPI_PROTOCOL_IEC62056),
+_P(NDPI_PROTOCOL_HL7),
+_P(NDPI_PROTOCOL_CEPH),
+_P(NDPI_PROTOCOL_GOOGLE_CHAT),
+_P(NDPI_PROTOCOL_ROUGHTIME),
+_P(NDPI_PROTOCOL_PIA),
+_P(NDPI_PROTOCOL_KCP),
+_P(NDPI_PROTOCOL_DOTA2),
+_P(NDPI_PROTOCOL_MUMBLE),
+_P(NDPI_PROTOCOL_YOJIMBO),
+_P(NDPI_PROTOCOL_ELECTRONICARTS),
+_P(NDPI_PROTOCOL_STOMP),
+_P(NDPI_PROTOCOL_RADMIN),
+_P(NDPI_PROTOCOL_RAFT),
+_P(NDPI_PROTOCOL_CIP),
+_P(NDPI_PROTOCOL_GEARMAN),
+_P(NDPI_PROTOCOL_TENCENTGAMES),
+_P(NDPI_PROTOCOL_GAIJIN),
+_P(NDPI_PROTOCOL_C1222),
+_P(NDPI_PROTOCOL_HUAWEI),
+_P(NDPI_PROTOCOL_HUAWEI_CLOUD),
+_P(NDPI_PROTOCOL_DLEP),
+_P(NDPI_PROTOCOL_BFD),
+_P(NDPI_PROTOCOL_NETEASE_GAMES),
+_P(NDPI_PROTOCOL_PATHOFEXILE),
+_P(NDPI_PROTOCOL_GOOGLE_CALL),
+_P(NDPI_PROTOCOL_PFCP),
+_P(NDPI_PROTOCOL_FLUTE),
+_P(NDPI_PROTOCOL_LOLWILDRIFT),
+_P(NDPI_PROTOCOL_TESO),
+_P(NDPI_PROTOCOL_LDP),
+_P(NDPI_PROTOCOL_KNXNET_IP),
+_P(NDPI_PROTOCOL_BLUESKY),
+_P(NDPI_PROTOCOL_MASTODON),
+_P(NDPI_PROTOCOL_THREADS),
+_P(NDPI_PROTOCOL_VIBER_VOIP),
+_P(NDPI_PROTOCOL_ZUG)
 
 };
 #include "inc_generated/ndpi_amazon_aws_match.c.inc"
@@ -362,7 +423,7 @@ _P(NDPI_PROTOCOL_ETHEREUM)
 #include "inc_generated/ndpi_asn_apple.c.inc"
 #include "inc_generated/ndpi_asn_avast.c.inc"
 #include "inc_generated/ndpi_asn_bloomberg.c.inc"
-#include "inc_generated/ndpi_asn_citrix.c.inc"
+//#include "inc_generated/ndpi_asn_citrix.c.inc"
 #include "inc_generated/ndpi_asn_discord.c.inc"
 #include "inc_generated/ndpi_asn_disney_plus.c.inc"
 #include "inc_generated/ndpi_asn_dropbox.c.inc"
@@ -414,7 +475,7 @@ static ndpi_network * ip4list[] = {
  &ndpi_protocol_apple_protocol_list[0],
  &ndpi_protocol_avast_protocol_list[0],
  &ndpi_protocol_bloomberg_protocol_list[0],
- &ndpi_protocol_citrix_protocol_list[0],
+// &ndpi_protocol_citrix_protocol_list[0],
  &ndpi_protocol_discord_protocol_list[0],
  &ndpi_protocol_disneyplus_protocol_list[0],
  &ndpi_protocol_dropbox_protocol_list[0],
@@ -518,7 +579,7 @@ static ndpi_network6 * ip6list[] = {
  &ndpi_protocol_apple_protocol_list_6[0],
  &ndpi_protocol_avast_protocol_list_6[0],
  &ndpi_protocol_bloomberg_protocol_list_6[0],
- &ndpi_protocol_citrix_protocol_list_6[0],
+// &ndpi_protocol_citrix_protocol_list_6[0],
  &ndpi_protocol_discord_protocol_list_6[0],
  &ndpi_protocol_disneyplus_protocol_list_6[0],
  &ndpi_protocol_dropbox_protocol_list_6[0],`
This is the patch:
[004-update_some_protocols.patch](https://github.com/user-attachments/files/15936312/004-update_some_protocols.patch)

**Comment by wlshdjj** [comment]
[004-update_some_protos.patch](https://github.com/user-attachments/files/15936309/004-update_some_protos.patch)
This is the patch.

**Comment by vel21ripn** [comment]
These files (ndpi_network_list_compile.h and ndpi_network_list_compile.c) are no longer used.
Compilation rules for ndpi_network_list_compile  have been removed.
