### ISSUE TITLE
Проходит трафик несоответствующий правилу

### ISSUE THREAD

**Issue by Antaryo** [vel21ripn/nDPI#197]
Пытаюсь построить стенд c с использованием nDPI в netfilter формата:
|Host1| <-LAN-> |FW| <-WAN-> |Host2|

Допустим я хочу разрешить только **ssh** трафик с любыми портами.
Для этого я применил такой набор правил:
```
iptables -P FORWARD DROP
iptables -A FORWARD -m ndpi --proto ssh -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```

В итоге я имею две проблемы:
1. Трафик **ssh** может ходить только по стандартному 22 порту. Если изменить порт, допустим на 80, то соединение не устанавливается.
2. Если на 22 будет гоняться не **ssh** трафик, а **http**, то он тоже будет проходить.

Как правильно бороться с этими проблемами?

**Comment by vel21ripn** [comment]
Нужно пропускать неизвестные пакеты и разрешать устанавливать соединения

iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -m ndpi --proto unknown -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate NEW -m ndpi --proto unknown -j ACCEPT

Есть опция "--inprogress protocols" которая србатывает пока протоколы пока не определены или не исключены которая иногда может быть полезная.

**Comment by Antaryo** [comment]
> Нужно пропускать неизвестные пакеты и разрешать устанавливать соединения
>
> iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -m ndpi --proto unknown -j ACCEPT
> iptables -A FORWARD -m conntrack --ctstate NEW -m ndpi --proto unknown -j ACCEPT

А можно немножко по подробнее как это работает? Разве разрешение неизвестного трафика не должно привести к тому, что кроме **ssh** будет иди ещё какой-нибудь трафик?

**Comment by vel21ripn** [comment]
Для установления соединения тратиться 3 пакета и они естественно считаюся неизвестными.

**Comment by Antaryo** [comment]
Попытался сделать так:
```
iptables -A FORWARD -m ndpi --proto ssh -j ACCEPT
iptables -A FORWARD -m conntrack -i eth0 --ctstate NEW -m ndpi --proto unknown -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -m ndpi --proto unknown -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
```
**http** трафик по 22 порту всё равно проскакивает,  и судя по `iptables -L -v` первые три пакета проходят по правилу `iptables -A FORWARD -m ndpi --proto ssh -j ACCEPT`

**Comment by vel21ripn** [comment]
У протокола ssh есть 2 уровня достоверности NDPI_CONFIDENCE_DPI, который будет после обнаружения сигнатуры и NDPI_CONFIDENCE_MATCH_BY_PORT который будет сразу для порта 22.
Есть сравнение по уровню достоверности --clevel .

**Comment by Antaryo** [comment]
А как работает тогда `inprogress` и можно ли его совмещать с `clevel`?

**Comment by vel21ripn** [comment]
inprogress использует clevel, так что вместе их использовать нет смысла.

inprogress  это когда не завершен процесс определения  протокола и протокол не исключён.

Завершение процесса определения  протокола: это достижение clevel >= DPI_CACHE (DPI_CACHE, DPI, DPI_AGGRESSIVE, CUSTOM_RULE) или исчерпание  возможности определить протокол (исключены все протоколы или превышено число пакетов).

**Comment by Antaryo** [comment]
> inprogress это когда не завершен процесс определения протокола и протокол не исключён.

Я правильно понял, что `inprogress` может пропускать первые пакеты трафика, который не прописан в правиле?

То есть правило такого вида:
`iptables -A FORWARD -m ndpi --inprogress ssh -j ACCEPT`
пропустит не только **ssh**, но и **http**, и другие протоколы

**Comment by vel21ripn** [comment]
Именно так. Нам же нужно как-то получить содержимое пакетов для анализа.
Жесткая фильтрация с помощью dpi не очень простое действие.

**Comment by Antaryo** [comment]
Про уровни достоверности.
Вот список уровней от `iptables -m ndpi --help`:
>  unknown,port,ip,user,nbpf,dpart,dcpart,dcache,dpi

Что это за уровни и в каком порядке они срабатывают?

С какого уровня происходит анализ если не указывать `--clevel`?

**Comment by vel21ripn** [comment]
Порядок должен быть такой:
unknown,port,ip,nbpf,dpart,dcpart,dcache,dpi,user
(Сегодня подправлю)

> С какого уровня происходит анализ если не указывать --clevel?

Если речь идёт о inprogress, то dcache,dpi,user

**Comment by Antaryo** [comment]
А если речь о режиме `--proto`?

**Comment by vel21ripn** [comment]
--proto - это или обнаруженный dpi протокол (мастер или приложения) или данные на основе порта, адреса, пользовательских настроек.

**Comment by Antaryo** [comment]
А где можно посмотреть/изменить порты, адреса для этого?

И что имеется ввиду под пользовательскими настройками? Где они находятся и как их заполнять.
В частности в `ndpi-netfilter/INSTALL` говорится о двух **proc** файлах:
`/proc/net/xt_ndpi/host_proto` и `/proc/net/xt_ndpi/ip_proto`.

**Comment by vel21ripn** [comment]
в ip_proto можно добавлять и удалять данные.
Обрати внимаение на "!" после протокола. Это и есть user, Без него это булет clevel "ip"

**Comment by Antaryo** [comment]
> unknown,port,ip,nbpf,dpart,dcpart,dcache,dpi,user

А что это за уровни? Кто по какому принципу работает.

И правильно ли я понял в `--clevel` перед именем уровня **-** означает ещё использовать более высокие, а **+** более низкие?

**Comment by vel21ripn** [comment]
0 - unknown,
1 - port, стандартный порт для протокола, если есть
2 - ip, можно изменить через ip_proto
3 - nbpf, не используется
4 - dpi partial
5 - dpi partial cached
6 - dpi cached
7 - dpi
8 - dpi aggressive, (не используется)
9 - user, задается через ip_proto c "!"

"clevel -X" это меньше Х
"clevel +X" это больше Х
"clevel X" это равно Х

port,ip,user не анализируют содержимое пакетов.

**Comment by Antaryo** [comment]
То есть при `--clevel +ip` ndpi будет работать по `ip,nbpf,dpart,dcpart,dcache,dpi,user`, верно?
А при `--clevel -ip` будет `unknown,port,ip`?

Я хочу заблокировать **ssh**, но оставить возможность пропускать трафик через 22 порт.
У меня получилось, что такое правило работает:
`iptables -A FORWARD -m ndpi --clevel -port --proto ssh -j DROP`

Под него попадает весь **ssh** трафик, а остальной проходит.

**Comment by Antaryo** [comment]
В файле [nDPI/ndpi-netfilter/README](https://github.com/vel21ripn/nDPI/tree/flow_info-4/ndpi-netfilter#readme) сказано, что для трекинга лучше использовать **conntrack** вместо аналогичной системы в **nDPI**.

Я правильно понимаю, что объединение в одном правиле и **conntrack**, и **ndpi** работает как _**И**_?
То есть должно сработать условие из **conntrack** и из **ndpi**?

И тогда возникает вопрос как это сочетается с `--inprogress`, чтобы исходящий и входящий трафик был валиден с точки зрения **TCP**?

**Comment by vel21ripn** [comment]
Используется ядерный conntrack. Без него nDPI работать не будет!
Все правила сравнения работают через И.
--inprogress нужен чтобы пропускать трафик до момента определния протокола.

**Comment by Antaryo** [comment]
Спасибо за ответы, разобрался.
Удалось построить и вариант с допустимым списком и списком запрещённых протоколов.
