### ISSUE TITLE
The Google Drive traffic isn't caught 

### ISSUE THREAD

**Issue by andrei-bohush** [vel21ripn/nDPI#198]
Hello, nDPI team

## Describe the bug
The nDPI doesn't track the Google Drive traffic app down. Also, the Google Drive website traffic isn't caught.

### Expected behavior
The nDPI tracks down the Google Drive desktop app traffic and the Google Drive website traffic.

### Obtained behavior
We're using the nDPI project to catch the traffic. It misses traffic for the Google Drive desktop app and the Google Drive website.

## nDPI Environment:
* nDPI version or commit hash: 4.8-stable or 212e4120fe16118a7daf8f544804d61f5e65935e.

**Comment by vel21ripn** [comment]
I can't determine the cause of the problem without a traffic sample that is correctly classified by ndpiReader.

**Comment by andrei-bohush** [comment]
Sure, there are traffic packet samples attached

[google_drive_packets_1.pcapng.zip](https://github.com/user-attachments/files/16111232/google_drive_packets_1.pcapng.zip)
[google_drive_packets_2.pcapng.zip](https://github.com/user-attachments/files/16111297/google_drive_packets_2.pcapng.zip)
[google_drive_packets_3.pcapng.zip](https://github.com/user-attachments/files/16111307/google_drive_packets_3.pcapng.zip)
[google_drive_packets_4.pcapng.zip](https://github.com/user-attachments/files/16111316/google_drive_packets_4.pcapng.zip)
[google_drive_packets_5.pcapng.zip](https://github.com/user-attachments/files/16111317/google_drive_packets_5.pcapng.zip)
[google_drive_packets_6.pcapng.zip](https://github.com/user-attachments/files/16111319/google_drive_packets_6.pcapng.zip)
[google_drive_packets_7.pcapng.zip](https://github.com/user-attachments/files/16111322/google_drive_packets_7.pcapng.zip)
[google_drive_packets_app_sync_with_web.pcapng.zip](https://github.com/user-attachments/files/16111324/google_drive_packets_app_sync_with_web.pcapng.zip)
[google_drive_packets_web_1.pcapng.zip](https://github.com/user-attachments/files/16111326/google_drive_packets_web_1.pcapng.zip)
[google_drive_packets_web_2.pcapng.zip](https://github.com/user-attachments/files/16111328/google_drive_packets_web_2.pcapng.zip)
[google_drive_packets_web_3.pcapng.zip](https://github.com/user-attachments/files/16111329/google_drive_packets_web_3.pcapng.zip)

**Comment by vel21ripn** [comment]
nDPI only detects GoogleDrive traffic with the names "drive-thirdparty.googleusercontent.com" and "drive.google.com".
ndpiReader does not classify your traffic samples as GoogleDrive.
I can't help you.
