### ISSUE TITLE
Does nDPI modules work with ip6tables?

### ISSUE THREAD

**Issue by Mile-Lile** [vel21ripn/nDPI#2]
I see that lot's of dissector are capable of recognizing ipv6 traffic but can ipv6 traffic be mangeled with iptables or do we need ip6tables and some sort of xt_nDPI_v6? I am asking because I am not able to block icmpv6 with nDPI ip_icmpv6 and iptables... 
[example.zip](https://github.com/vel21ripn/nDPI/files/280338/example.zip)
and also thank you for your work:)

**Comment by vel21ripn** [comment]
need use ip6tables

**Comment by Mile-Lile** [comment]
thx for clarification. I tried with ip6tables and -m nDPI --ip_icmpv6 -j DROP but got some strange message that nDPI and ip6tables are not compatible...

**Comment by vel21ripn** [comment]
"ip6tables -A INPUT -m ndpi --ip_icmpv6" working.
ip6tables -nvxL | grep icmp
    1508   418798            all      \*      \*       ::/0                 ::/0                 ndpi protocol ip_icmpv6

**Comment by Mile-Lile** [comment]
thx again. you are right! I used -s 192.168.2.30 instead of ipv6 source adress ff00::/8
