### ISSUE TITLE
Вопросы по принципу работы

### ISSUE THREAD

**Issue by Antaryo** [vel21ripn/nDPI#201]
В **issue** #197 Вы показывали такой список для `--clevel`:
> 0 - unknown,
> 1 - port, стандартный порт для протокола, если есть
> 2 - ip, можно изменить через ip_proto
> 3 - nbpf, не используется
> 4 - dpi partial
> 5 - dpi partial cached
> 6 - dpi cached
> 7 - dpi
> 8 - dpi aggressive, (не используется)
> 9 - user, задается через ip_proto c "!"

Объясните, пожалуйста, какой пункт как работает?
Чем отличается **dpi partial** от **dpi**, а **cached** от не **cached**?
В чём отличаются уровни **user** от **ip** для **nDPI**?

**Comment by vel21ripn** [comment]
**port** **ip**  **user** определяются по первому пакету. В этом они идентичны.
**user** предпологается использовать для перекрытия всех остальных способов и DPI при этом использоваться уже не будет.
Все dpi требуют прохождения N пакекетов, при этом иногда требуется прохождение в обе стороны.

Посмотри в коде использование констант NDPI_CONFIDENCE_DPI_*
