### ISSUE TITLE
Some Applications based on QUIC protocol not being detected

### ISSUE THREAD

**Issue by hcvs010164** [vel21ripn/nDPI#204]
## Describe the bug
I tried to filter youtube traffic and let them to do flow info.
This rule was added in prerouting hook point and the priority is mangle.
I noticed that youtube traffic based on QUIC was not marked as Youtube.
Additionally, some Applications (Ex: Discord) based on QUIC also can't be detected.

### Expected behavior
Filter youtube traffic and let them to do flow info.
### Obtained behavior
Some traffic cannot be recognized as Youtube.

## nDPI Environment (please complete the following information):
* Linux version: 5.4.55
* nDPI version or commit hash: [3deea541af037b663b1b83a055b80d9a06a0afd2].

### Reproducible using ndpiReader?
- [x] The reported bug is not reproducible using ndpiReader.

### Visit one of the following websites and check reported traffic:
- www.youtube.com

## Additional context
I tried to trace code and noticed a problem.
When the first few packets of a traffic arrive at almost the same time, conntrack may treat packets as multiple connections.
Conntrack will first create entries for these packets and add them to the unconfirmed list until the first packet is changed to confirmed through postrouing.
For the above situation, the first packet and the second packet cannot be regarded as the same connection by conntrack, and the connection cannot be correctly processed by nDPI.
`The reported bug is not reproducible using ndpiReader because nDPIReader will match the connection for this packet and nDPI.ko depends on conntrack.**`
This problem may be difficult to reproduce, but it can be reproduced as long as the second packet arrives at nDPI.ko before the first packet is confirmed.

**Comment by vel21ripn** [comment]
I highly doubt that two packets with the same addresses and ports will be considered as two different connections by conntrack.
If you have a sample of such traffic and can send it to me, I will try to check this assumption.

**Comment by hcvs010164** [comment]
Hi @vel21ripn ,

I found the problem. On my environment, in addition to using nDPI kernel modules, I also use nf_queue.
And the first packet of the session be queued on userspace, causing the kernel to process the second packet immediately.
Since the conntrack entry to which the first data packet belongs has not yet taken effect, a new conntrack entry is created for the second packet.

Best Regard.
