### ISSUE TITLE
Kernel 4.13.0 nf_ct_iterate_cleanup function

### ISSUE THREAD

**Issue by gklipel** [vel21ripn/nDPI#22]
Hi!

It seems that in new kernel version the function nf_ct_iterate_cleanup was renamed and the module no longer copiles against it.

Other issue that I'd noticed, with module loaded against v4.12 on an armhf and arm64 platform I'm getting kernel hangs, no matter what module or traffic is going on, the result is the same... Anyone experiencing this?

Thanks!

**Comment by k0ste** [comment]
Please, try patch from #20.

**Comment by elico** [comment]
@k0ste can you PR this patch?

**Comment by k0ste** [comment]
@elico what you mean? This is already PR'ed.

**Comment by elico** [comment]
@k0ste Ho, 7 days ago it wasn't... I tested it before the PR.

**Comment by k0ste** [comment]
@elico I was make patch and PR'ed after you mention about problem in #19.

**Comment by elico** [comment]
@k0ste  Thanks!

**Comment by gklipel** [comment]
Thanks!

**Comment by elico** [comment]
@k0ste @gklipel I think this bug can be closed, right?

**Comment by vel21ripn** [comment]
Applied.
