### ISSUE TITLE
Measuring Latency

### ISSUE THREAD

**Issue by faizatahir94** [vel21ripn/nDPI#23]
HI I have a Query. Does anyone can tell how can we measure the Latency involved if we use ndpi-netfilter? Any tools or method?

**Comment by vel21ripn** [comment]
Measure  time of execution ndpi_detection_process_packet()
http://practicepeople.blogspot.ru/2013/10/kernel-programming-7-ktimeget-and.html

**Comment by faizatahir94** [comment]
@vel21ripn Can you please also share when netfilter2.0 will be released ( with ndpi 2.0 stable version )?

**Comment by vel21ripn** [comment]
There is already a beta version. Netfilter2 branch.
