### ISSUE TITLE
ndpi-netfilter 2.0-stable

### ISSUE THREAD

**Issue by vel21ripn** [vel21ripn/nDPI#24]
The netfilter2 branch is available for testing.

**Comment by elico** [comment]
@vel21ripn I hope that next week I will check if it builds nice on a Ubuntu 16.04 Docker container and test it on a tiny router VM.

**Comment by elico** [comment]
@vel21ripn I built the netfilter2 branch but yet to load and test it but... since it's a branch I want to make sure before or after I load the module that it's Version 2.
Where and how should I be able to see that?
in the library so file or the module?
Maybe a specific protocol that exists only in netfilter2?

**Comment by vel21ripn** [comment]
@elico show "grep version /proc/net/xt_ndpi/proto" or  dmesg

**Comment by elico** [comment]
@vel21ripn I would only be able to do this in couple days.
For now it seems to me that "grep AC_INIT configure.ac" good enough to see i'm on the right branch.
I will update you after throwing couple bits on the module.

**Comment by elico** [comment]
@vel21ripn seems like 2.0 works for an hour or two.
```
# grep version /proc/net/xt_ndpi/proto
#id     mark ~mask     name   # count #version 2.0.0-844-054bb8f
```

**Comment by hisham2630** [comment]
i tried to compile https://github.com/openwrt-develop/ndpi-netfilter/blob/master/Makefile for openwrt but fail with some errors,any help appreciated.

make[3]: Entering directory '/home/hisham/Desktop/openwrt/source/feeds/packages/net/ndpi-netfilter'
rm -f /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/.built
touch /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/.built_check
CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c:ndpi-netfilter2-85f459c -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/usr/include -I/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/include -I/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/usr/include -I/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/include/fortify -I/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/include " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c:ndpi-netfilter2-85f459c -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/usr/include -I/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/include -I/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/usr/include -I/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/include/fortify -I/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/include " LDFLAGS="-L/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/usr/lib -L/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/lib -L/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/usr/lib -L/home/hisham/Desktop/openwrt/source/staging_dir/toolchain-mips_24kc_gcc-5.5.0_musl/lib -znow -zrelro " make -j1 -C /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c:ndpi-netfilter2-85f459c -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CROSS="mips-openwrt-linux-musl-" ARCH="mips" KERNEL_DIR="/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/linux-4.9.76" ARCH="mips" NDPI_PATH=/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter CROSS_COMPILE="mips-openwrt-linux-musl-" all ;
make[4]: Entering directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter'
make -C ipt
make[5]: Entering directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/ipt'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/ipt'
make -C src
make[5]: Entering directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src'
make  -C /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/linux-4.9.76 M=$PWD modules -w;
make[6]: Entering directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/linux-4.9.76'
  CC [M]  /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.o
In file included from /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/../../src/include/ndpi_main.h:28:0,
                 from /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:47:
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/../../src/include/ndpi_define.h:61:21: warning: "__LITTLE_ENDIAN" is not defined [-Wundef]
 #if __BYTE_ORDER == __LITTLE_ENDIAN
                     ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:119:2: error: #error NF_CONNTRACK_LABELS not defined
 #error NF_CONNTRACK_LABELS not defined
  ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c: In function 'ndpi_net_exit':
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2455:9: error: 'struct netns_ct' has no member named 'labels_used'
  net->ct.labels_used--;
         ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c: In function 'ndpi_net_init':
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2511:18: error: passing argument 1 of 'set_ndpi_malloc' from incompatible pointer type [-Werror=incompatible-pointer-types]
  set_ndpi_malloc(malloc_wrapper);
                  ^
In file included from /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/../../src/include/ndpi_main.h:32:0,
                 from /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:47:
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/../../src/include/ndpi_api.h:621:8: note: expected 'void * (*)(size_t) {aka void * (*)(unsigned int)}' but argument is of type 'void * (*)(long unsigned int)'
   void set_ndpi_malloc(void* (*__ndpi_malloc)(size_t size));
        ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2604:10: error: 'struct netns_ct' has no member named 'labels_used'
   net->ct.labels_used++;
          ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c: In function 'ndpi_mt_init':
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2703:22: error: 'NF_CT_EXT_LABELS' undeclared (first use in this function)
  nf_ct_ext_id_ndpi = NF_CT_EXT_LABELS;
                      ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2703:22: note: each undeclared identifier is reported only once for each function it appears in
In file included from ./include/linux/printk.h:6:0,
                 from ./include/linux/kernel.h:13,
                 from /home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:23:
./include/linux/kern_levels.h:4:18: warning: format '%zu' expects argument of type 'size_t', but argument 6 has type 'long unsigned int' [-Wformat=]
 #define KERN_SOH "\001"  /* ASCII Start Of Header */
                  ^
./include/linux/kern_levels.h:13:19: note: in expansion of macro 'KERN_SOH'
 #define KERN_INFO KERN_SOH "6" /* informational */
                   ^
./include/linux/printk.h:284:9: note: in expansion of macro 'KERN_INFO'
  printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
         ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2760:2: note: in expansion of macro 'pr_info'
  pr_info("xt_ndpi v1.2 ndpi %s %s\n"
  ^
./include/linux/kern_levels.h:4:18: warning: format '%zu' expects argument of type 'size_t', but argument 7 has type 'long unsigned int' [-Wformat=]
 #define KERN_SOH "\001"  /* ASCII Start Of Header */
                  ^
./include/linux/kern_levels.h:13:19: note: in expansion of macro 'KERN_SOH'
 #define KERN_INFO KERN_SOH "6" /* informational */
                   ^
./include/linux/printk.h:284:9: note: in expansion of macro 'KERN_INFO'
  printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
         ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2760:2: note: in expansion of macro 'pr_info'
  pr_info("xt_ndpi v1.2 ndpi %s %s\n"
  ^
./include/linux/kern_levels.h:4:18: warning: format '%zu' expects argument of type 'size_t', but argument 9 has type 'long unsigned int' [-Wformat=]
 #define KERN_SOH "\001"  /* ASCII Start Of Header */
                  ^
./include/linux/kern_levels.h:13:19: note: in expansion of macro 'KERN_SOH'
 #define KERN_INFO KERN_SOH "6" /* informational */
                   ^
./include/linux/printk.h:284:9: note: in expansion of macro 'KERN_INFO'
  printk(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
         ^
/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.c:2760:2: note: in expansion of macro 'pr_info'
  pr_info("xt_ndpi v1.2 ndpi %s %s\n"
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:293: recipe for target '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.o' failed
make[7]: *** [/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src/main.o] Error 1
Makefile:1495: recipe for target '_module_/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src' failed
make[6]: *** [_module_/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src] Error 2
make[6]: Leaving directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/linux-4.9.76'
Makefile:170: recipe for target 'modules' failed
make[5]: *** [modules] Error 2
make[5]: Leaving directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter/src'
Makefile:2: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/ndpi-netfilter'
Makefile:66: recipe for target '/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/.built' failed
make[3]: *** [/home/hisham/Desktop/openwrt/source/build_dir/target-mips_24kc_musl/linux-lantiq_xrx200/ndpi-netfilter2-85f459c/.built] Error 2
make[3]: Leaving directory '/home/hisham/Desktop/openwrt/source/feeds/packages/net/ndpi-netfilter'
package/Makefile:109: recipe for target 'package/feeds/packages/ndpi-netfilter/compile' failed
make[2]: *** [package/feeds/packages/ndpi-netfilter/compile] Error 2
make[2]: Leaving directory '/home/hisham/Desktop/openwrt/source'
package/Makefile:105: recipe for target '/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/hisham/Desktop/openwrt/source/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/hisham/Desktop/openwrt/source'
/home/hisham/Desktop/openwrt/source/include/toplevel.mk:216: recipe for target 'world' failed
