### ISSUE TITLE
ndpi-netfilter and netfilter2 freezing

### ISSUE THREAD

**Issue by gklipel** [vel21ripn/nDPI#29]
Hi!

Since kernel 4.12 we've noticed some nf_conntrack functions changing names and, don't know if this is an coincidence, but from that version to this very moment, every time I load xt_ndpi module with iptables rules, I try to use any kind of SSL traffic, the linux box hangs and restarts.

Still couldn't get any syslog or dmesg output... The machine freezes and I can't do anything till it reboots itself.

This happens in x86_64, armhf and arm64 as well... Kernels I've tested 4.12.0, 4.13.0, 4.13.12, 4.14.0. Version 4.11 downwards  aren't affected this way.

Any thoughts?

**Comment by vel21ripn** [comment]
Do you use xt_ndpi with a patch for the kernel?

**Comment by gklipel** [comment]
No, didn't patched.
If it is necessary, sorry... And thanks!

**Comment by vel21ripn** [comment]
How long working the system before hang?
Hanging without messages is a symptom of problems with lock / unlock. I'll try to check on the kernel 4.13.12. Using xt_ndpi without a kernel patch is an extreme option.
We have to use hacks, which leads to the inoperability of the code when changing the kernel version :(
Support for the 4.14 kernel will only appear after 4.14.3.

**Comment by gklipel** [comment]
There is no time to hang, it can hang like 5 minutes in use, sometimes takes 20 minutes, an hour... 

Today I tried to apply patch v4.12 against kernel 4.13.12 but I got an error compiling kernel at conntrack compile time. It seems some conntrack fuctions had been changed from 4.12 to 4.13 and 4.14 and I thought it would not be useful post the error here...

Well, thanks in advance and thanks for your efforts on this tool, it is really useful.

**Comment by elico** [comment]
@gklipel On what Linux Distribution?
I can try to run some tests but I need more details such as traffic bandwidth and content type(servers, desktops, mobiles).

**Comment by vel21ripn** [comment]
@gklipel patch v4.12.0.diff applied to kernel 4.13.14 and build kernel without warnings or errors. 
I ran the system for testing (x86_64 4.13.14) about 70 hours ago. The traffic is 100-450Mbit/s, 10-90 thousand conntrack. ndpi-netfilter 1.7 (netfilter-234-0670f78)

Can you describe the configuration of your system (CPU / RAM) and approximate traffic parameters?

**Comment by jirimikosek** [comment]
@vel21ripn I applied patch v4.12.0 to kernel 4.13.14, but during kernel compilation I got error

debian stretch, gcc (Debian 6.3.0-18) 6.3.0 20170516

```
In file included from ./include/uapi/linux/stddef.h:1:0,
                 from ./include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from ./include/uapi/linux/types.h:13,
                 from ./include/linux/types.h:5,
                 from net/netfilter/nf_conntrack_core.c:17:
In function ‘total_extension_size’,
    inlined from ‘nf_conntrack_init_start’ at net/netfilter/nf_conntrack_core.c:1996:2:
./include/linux/compiler.h:546:38: error: call to ‘__compiletime_assert_1962’ declared with attribute error: BUILD_BUG_ON failed: NF_CT_EXT_NUM > 9
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                      ^
./include/linux/compiler.h:526:4: note: in definition of macro ‘__compiletime_assert’
    prefix ## suffix();    \
    ^~~~~~
./include/linux/compiler.h:546:2: note: in expansion of macro ‘_compiletime_assert’
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:46:37: note: in expansion of macro ‘compiletime_assert’
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:70:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
  BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
  ^~~~~~~~~~~~~~~~
net/netfilter/nf_conntrack_core.c:1962:2: note: in expansion of macro ‘BUILD_BUG_ON’
  BUILD_BUG_ON(NF_CT_EXT_NUM > 9);
  ^~~~~~~~~~~~
scripts/Makefile.build:302: recipe for target 'net/netfilter/nf_conntrack_core.o' failed
make[4]: *** [net/netfilter/nf_conntrack_core.o] Error 1
scripts/Makefile.build:561: recipe for target 'net/netfilter' failed
make[3]: *** [net/netfilter] Error 2
Makefile:1019: recipe for target 'net' failed
make[2]: *** [net] Error 2
scripts/package/Makefile:91: recipe for target 'deb-pkg' failed
make[1]: *** [deb-pkg] Error 2
Makefile:1349: recipe for target 'deb-pkg' failed
make: *** [deb-pkg] Error 2
```

**Comment by k0ste** [comment]
@jirimikosek this is because you enable all nf_ct_ext. Set `BUILD_BUG_ON(NF_CT_EXT_NUM > 10);`.

**Comment by jirimikosek** [comment]
its same error, I increased it :(

```
In file included from ./include/uapi/linux/stddef.h:1:0,
                 from ./include/linux/stddef.h:4,
                 from ./include/uapi/linux/posix_types.h:4,
                 from ./include/uapi/linux/types.h:13,
                 from ./include/linux/types.h:5,
                 from net/netfilter/nf_conntrack_core.c:17:
In function ‘total_extension_size’,
    inlined from ‘nf_conntrack_init_start’ at net/netfilter/nf_conntrack_core.c:1996:2:
./include/linux/compiler.h:546:38: error: call to ‘__compiletime_assert_1962’ declared with attribute error: BUILD_BUG_ON failed: NF_CT_EXT_NUM > 10
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                      ^
./include/linux/compiler.h:526:4: note: in definition of macro ‘__compiletime_assert’
    prefix ## suffix();    \
    ^~~~~~
./include/linux/compiler.h:546:2: note: in expansion of macro ‘_compiletime_assert’
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:46:37: note: in expansion of macro ‘compiletime_assert’
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:70:2: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
  BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
  ^~~~~~~~~~~~~~~~
net/netfilter/nf_conntrack_core.c:1962:2: note: in expansion of macro ‘BUILD_BUG_ON’
  BUILD_BUG_ON(NF_CT_EXT_NUM > 10);
  ^~~~~~~~~~~~
make[2]: *** [net/netfilter/nf_conntrack_core.o] Error 1
make[1]: *** [net/netfilter] Error 2
make: *** [net] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by gklipel** [comment]
@vel21ripn sorry for the very late reply... So far I've tested with a cubieboard2 (Kernels 4.9.78 / 4.13.16 / 4.14.4 / 4.14.15) and a Odroid C2 (Kernels 4.13.14 / 4.14.4 / 4.14.16). Only one machine generating traffic, most of it Skype chat... I've tried with x86 processor, same error at compile time.

@elico Debian Jessie (armhf, arm64 and x86_64).

In fact, kernel 4.9.78 patches and build without any warning or errors. But I got the very same error than @jirimikosek on kernels > 4.12.

> this is because you enable all nf_ct_ext

@k0ste what did you meant with it? Sorry but can you give some example?

Thanks!

**Comment by k0ste** [comment]
@gklipel @jirimikosek #16

**Comment by elico** [comment]
@gklipel @jirimikosek How about building the kernel without the patch and make sure it works.
If yes then just double the number of CT_EXT from 9 to 18 and if it still complains bump to 30 and see then what happen.
If with 30 it's not working then it's better you will share you kernel config.

**Comment by gklipel** [comment]
@elico I see, understood! Will increase the value and close the topic as soon as it works.

@k0ste thanks!

**Comment by gklipel** [comment]
Well, CT_EXT > 11 turned out the final value.

Many thanks!

**Comment by gklipel** [comment]
Didn't tried with kernel 4.13.12 because of Odroid C2 support (is better on 4.14). With kernel 4.14.16 still hangs, almost imediately after load iptables ndpi rules.

[mangle]
-A POSTROUTING ! -o lo -j NDPI --ndpi-id --set-clsf
-A PREROUTING ! -i lo -m ndpi --all
-A FORWARD ! -i lo -m ndpi --all
-A FORWARD ! -o lo -m ndpi --all
-A OUTPUT ! -o lo -m ndpi --all

then accepting or droping traffic on filter table.

Tested with netfilter and netfilter2, same results. With netfilter2 the system seems to last longer without hanging, about 5 minutes. The only traffic is a PC loading https and https sites.

I will try in another platform later (possibly x86_64).

**Comment by elico** [comment]
@gklipel @vel21ripn This board Odroid C2 has a very nice "Amlogic S905 Quad Core Cortex™-A53 1.5GHz 64bit ARMv8 processor with Mali™ -450 GPU" which technically is one of the leading(ARMv8 64 bit) CPU in the ARM world.
Since 4.14.17 is considered stable I believe it's worth testing on x86_64 and compare to another ARM 64 bit system like Ubuntu or Debian.
I am not sure what emulator/virualization support this CPU but it's worth re-testing ontop of Ubuntu-arm as well to see if there is a difference.
@gklipel is there any specific reason for this Odroid C2 to work better with the mentioned kernel compared to the Basic Debian one?(or maybe this is the basic one?)

**Comment by vel21ripn** [comment]
The kernel 4.14 has problems with x86/PAE. I can not yet test the work of ndpi-netfilter on the x86 platform.

**Comment by elico** [comment]
@vel21ripn Can you redirect to the place where it's was written?
Are you talking about both x86 and x86_64?

**Comment by vel21ripn** [comment]
@elico I have x86 and x86_64 only.

I have a working kernel configuration for x86 with support for 4GB of RAM (CONFIG_HIGHMEM4G). Changing one configuration parameter CONFIG_HIGHMEM4G = n and CONFIG_HIGHMEM64G = y makes it impossible to load the kernel (instant reboot without messages). For the first time in over 20 years of using linux I encountered such a problem. 2 years ago I was already repairing a similar error (DMA and PAE) in kernel 4.4. The kernel started normally, but could not read data from the disk.

 I now do not have time to do "git bisect" to detect this error. And without this, do not make a bug report in kernel.org.

**Comment by elico** [comment]
@vel21ripn leave the kernel guys to do their "thing" I think that there are much important things in life then finding out why the Linux Kernel have a bug or have an issue.
There are enough companies around the globe else then a single person that really care about this issue and will act to fix it.
I do not have 20 years of experience with Linux but I do have 20 years of experience with computers and I have seen more then one sketch of chips and CPU's over these years.
What you are doing is really something extraordinary already!!
Let's wait and see how the "market" will handle this kernel issue and learn from it.
Thanks for the details until now!

**Comment by gklipel** [comment]
> @gklipel is there any specific reason for this Odroid C2 to work better with the mentioned kernel compared to the Basic Debian one?(or maybe this is the basic one?)

Hardware support.

**Comment by vel21ripn** [comment]
I reproduced the bug with freezing on kernels 4.14.18.
In kernel 4.14 a new feature has appeared: conntrack is not activated until iptables is added a rule related to the conntrack check.
In this case, "conntrack -L" shows 0.
Without the rule "iptables -A FORWARD -m conntrack --ctstate INVALID -j DROP" I get a guaranteed kernel crash for 2-5 seconds with incoming traffic of 300Mbps.

**Comment by vel21ripn** [comment]
@gklipel @elico @k0ste  I updated the netfilter branch. Can you test it on the 4.14 kernel?

**Comment by elico** [comment]
@vel21ripn I do not have a ready to use system that I can test it on now.
I can try to compile a vanilla Linux kernel on gentoo or arch Linux but cannot promise a fast test as in the past.

**Comment by gklipel** [comment]
@vel21ripn it seems to be working now, testing on Odroid C2 with kernel 4.15.9 and it is stable, no hangs anymore.

Many thanks for your efforts!
