### ISSUE TITLE
Compiling on AlpineLinux.

### ISSUE THREAD

**Issue by elico** [vel21ripn/nDPI#3]
I have been working with AlpineLinux for quite some time and it seems that it's a pretty nice routing system but for now I was unable to compile nDPI on it.
I have seen this bug report on AlpineLinux: https://bugs.alpinelinux.org/issues/3526
But the issue is that there is no example of the build node.

**Comment by vel21ripn** [comment]
Do you have errors when compiling ndpi-netfilter project from the repository nDPI/vel21ripn/netfilter?
What hinders add a line "typedef u_char u_int8_t" in linux_compat.h file?

**Comment by elico** [comment]
@vel21ripn I added the typedef and also added "#include <sys/types.h>"
I am now one step forward, will update later.

**Comment by k0ste** [comment]
```
gcc (GCC) 6.1.1 20160802
Linux WorkStation 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
```

Builds okay.

**Comment by elico** [comment]
@k0ste @vel21ripn I will start to see how it all glued together on a docker container.
I managed to make some of it work and now the virt version of the kernel is the next step.

**Comment by elico** [comment]
@vel21ripn @k0ste: works only on latest but not edge:
https://github.com/elico/alipnelinux-ndpi-docker
It was compiled for generic kernel and not the virtual one but might be able to work on the virt one too.
Later we can see how it works on a production router :D

**Comment by elico** [comment]
It works pretty nice.
