### ISSUE TITLE
kernel 4.15.x

### ISSUE THREAD

**Issue by PLumowina** [vel21ripn/nDPI#32]
Hello is there someone that use new stable line 4.15.3? how to make it work with ndpi-netfilter ?

**Comment by vel21ripn** [comment]
Work in progress. In kernel 4.15 changed "struct timer_list". Need changes in  ndpi-kernel code.

**Comment by vel21ripn** [comment]
https://github.com/vel21ripn/nDPI/commit/d21290ab7b5d6407ece8a330a81e015080daee0b
