### ISSUE TITLE
make problem on debian jessie 4.12.14

### ISSUE THREAD

**Issue by tim1014** [vel21ripn/nDPI#33]
When I try to make. It just stops compilating.

make -C ipt
make[1]: Entering directory '/usr/src/nDPI-netfilter/ndpi-netfilter/ipt'
cc -fPIC -I../include -I../lib -I../src -DOPENDPI_NETFILTER_MODULE -O2 -Wall   -c -o libxt_ndpi.o libxt_ndpi.c
cc -shared -o libxt_ndpi.so libxt_ndpi.o;
rm libxt_ndpi.o
make[1]: Leaving directory '/usr/src/nDPI-netfilter/ndpi-netfilter/ipt'
make -C src
make[1]: Entering directory '/usr/src/nDPI-netfilter/ndpi-netfilter/src'
make -j 4 -C /lib/modules/4.12.14-041214-generic/build M=$PWD modules -w;
make[2]: Entering directory '/usr/src/linux-headers-4.12.14-041214-generic'
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/main.o
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/../third_party/src/node.o
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/../third_party/src/ahocorasick.o
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/ndpi_main.o
/usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/ndpi_main.c:54:35: fatal error: ndpi_network_list.c.inc: No such file or directory
 #include "ndpi_network_list.c.inc"
                                   ^
compilation terminated.
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/aimini.o
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/afp.o
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c: In function ‘debug_printf’:
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c:360:1: warning: the frame size of 1056 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c: In function ‘n_ipdef_proc_read’:
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c:2261:1: warning: the frame size of 1688 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c: In function ‘nproto_proc_write’:
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c:2486:1: warning: the frame size of 1160 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/applejuice.o
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/armagetron.o
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c: In function ‘n_ipdef_proc_write’:
/usr/src/nDPI-netfilter/ndpi-netfilter/src/main.c:2298:1: warning: the frame size of 1608 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
  CC [M]  /usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/protocols/ayiya.o
scripts/Makefile.build:302: recipe for target '/usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/ndpi_main.o' failed
make[3]: *** [/usr/src/nDPI-netfilter/ndpi-netfilter/src/../lib/ndpi_main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:1515: recipe for target '_module_/usr/src/nDPI-netfilter/ndpi-netfilter/src' failed
make[2]: *** [_module_/usr/src/nDPI-netfilter/ndpi-netfilter/src] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.12.14-041214-generic'
Makefile:165: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/usr/src/nDPI-netfilter/ndpi-netfilter/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by vel21ripn** [comment]
```
./autogen.sh
( cd src/lib ; make ndpi_network_list.c.inc )
( cd ndpi-netfilter ; make )
```

**Comment by tim1014** [comment]
@vel21ripn thx, the problem solved. but when I following the guide to do make module_install. it said No rule to make target 'modules_install'.

**Comment by vel21ripn** [comment]
Target "modules_install" is available in ndpi-netfilter and ndpi-netfilter/src directories.
```
./autogen.sh
( cd src/lib ; make ndpi_network_list.c.inc )
cd ndpi-netfilter ; make && ( make install ; make modules_install )
```

**Comment by tim1014** [comment]
Thank you so much for helping. I am looking for this kind of DPI filter for two years. And it is working now.

**Comment by elico** [comment]
@vel21ripn I verified and the same issue exists on Ubuntu\Debian + CentOS + others.
the:
`( cd src/lib ; make ndpi_network_list.c.inc )`
seems to me like a mandatory part of the build.
Can you document it somewhere in the sources?

**Comment by vel21ripn** [comment]
I'm updated the file ndpi-netfilter/INSTALL

**Comment by elico** [comment]
@vel21ripn Thanks!
