### ISSUE TITLE
HTTP dynamic domain matching module?

### ISSUE THREAD

**Issue by elico** [vel21ripn/nDPI#34]
I have seen this nice project:
https://github.com/Lochnair/xt_tls

Which actually is based on this project code.
I was wondering if it would be possible to either create or extend the current http/1.x module to be able to match more then just it but also a dynamic domain such as "rule --domain x.y.net -j DROP".

**Comment by vel21ripn** [comment]
I do not quite understand what I want to get in the end?
In version 1.7, this is most likely not done, but in the "2. +" branch, it probably makes sense to add a comparison for the domain name.
```
iptables .... -m ndpi --https --http-host .google.com ...
```

**Comment by elico** [comment]
@vel21ripn I am not talking about https but plain http(1.x) such as:

> iptables .... -m ndpi --http --http-host .google.com ...
> iptables .... -m ndpi --http --http-host *.google.com ...
> iptables .... -m ndpi --http --http-host test.*.google.com ...

Which basically will make admins life easier in general to handle a strict http\https access policy without going to the depth of a full http proxy installation.
It will also make iptables more modular then it is now.

The dream would be to be able to send something like the src ip and the current destination domain to some local in ram Filtering DB and the response will decide if the connection is allowed or not but it's a dream and requires from someone to put _some_ cash on the it. 

From what I remember suricata-ids have such a feature but it was so complex for me to install and configure that I left it and continued to work with a custom tproxy.

**Comment by vel21ripn** [comment]
I solved common problems with migration to dev-2.3, now I can try to add this functionality.

**Comment by k0ste** [comment]
I think, for this feature best functional is 'sets', like:

```bash
# create set
iptables -t mangle -A POSTROUTING -m ndpi --http-domain --set name0 -j DROP
iptables -t mangle -A PREROUTING -m ndpi --http-domain --set name0 -j DROP
# add domain
echo +google.com > /proc/net/ndpi_http_domain/name0
# delete domain
echo -google.com > /proc/net/ndpi_http_domain/name0
# add multiple domain
echo +google.com,google.co.jp > /proc/net/ndpi_http_domain/name0
```

This is just a copy-paste - functional was already implemented int [aabc/ipt-ratelimit](https://github.com/aabc/ipt-ratelimit/blob/master/README#L73-L135).

**Comment by vel21ripn** [comment]
@k0ste No! In "nDPI" there is a comparison for domains. You need to add the ability to override it without recompiling.  It works with the ssl, http and dns protocols.

**Comment by k0ste** [comment]
Why this:
```
# Big list in magle
iptables -t mangle -A PREROUTING -m ndpi --domain --match google.com -j DROP
iptables -t mangle -A PREROUTING -m ndpi --domain --match google.cz -j DROP
iptables -t mangle -A PREROUTING -m ndpi --domain --match google.cn -j DROP
```

Better than this:
```
# one rule
iptables -t mangle -A PREROUTING -m ndpi --domain --set name0 -j DROP
# one management set
echo +google.com,google.cz,google.cn > /proc/net/ndpi_http_domain/name0
```

The case: I need to filter 3 different clients:
 * first client have 500 domains in list;
 * 2nd: 3500 domains;
 * 3rd: 1000 domains.

All domains is different.

**Comment by vel21ripn** [comment]
All this is already in nDPI. You need to add an interface to load the list of domains.

**Comment by vel21ripn** [comment]
See https://github.com/vel21ripn/nDPI/commit/16d3ab32aa9fca12eddd817d7c21e2c97aaa17f9
I don't tested long domain names list.
Theoretically, the list of hosts can be changed during work, but I have not tried to do so yet. Rebuilding the search tree is a rather lengthy task.

**Comment by vel21ripn** [comment]
I changed the procedure for loading hostnames. Theoretically, there are no restrictions on the number of host names. Updates take place atomically.

**Comment by vel21ripn** [comment]
Commit 0b5ec1ed7f5e4c48f0adfad1c557ae72d166af1e fixed critical error.
