### ISSUE TITLE
[   17.772352] xt_ndpi: Unknown symbol __aeabi_uldivmod (err 0)

### ISSUE THREAD

**Issue by panda-mute** [vel21ripn/nDPI#39]
produced in: mvebu arm 32bit
Seems it is introduced in commit: 
b0cf474844c57f2115af6cf61b13afeb4473e24d
Fixed wrong tick_timestamp calculation.

**Comment by vel21ripn** [comment]
Please check https://github.com/vel21ripn/nDPI/commit/ef2028190ec9117419a503e080fc2a0be4d3a5e0

**Comment by panda-mute** [comment]
Fixed. Thanks!
