### ISSUE TITLE
can not match Youtube traffic 

### ISSUE THREAD

**Issue by lyt0112** [vel21ripn/nDPI#40]
Hi All

I tried to control YouTube traffic...
But I added the following commands:
/sbin/iptables -w -t mangle -A PREROUTING -s 192.168.1.0/24 -m ndpi --YouTube -j MARK --set-mark 0x3ea
/sbin/iptables -w -t mangle -A PREROUTING -s 192.168.1.0/24 -m ndpi --YouTubeUpload -j MARK --set-mark 0x3ea
No traffic can be matched. Is there any possibility to cause the problem?
My kernel is 3.18.0 and I patched the kernel according to this project's document.

I also tried the project: https://github.com/betolj/ndpi-netfilter with same command(Only -m ndpi --YouTube), Youtube traffic can be matched via IE/Forefox/Edge,but Chrome can not work.

**Comment by vel21ripn** [comment]
It is necessary to analyze traffic in both directions. Try adding the command
```
iptables -t mangle -A POSTROUTING -d 192.168.1.0/24 -m ndpi --all
```

**Comment by lyt0112** [comment]
Hi
I've tried the command you provided,seems like YouTube traffic can only match to HTTP & HTTP_Download.

[root@~ xt_ndpi]# cat /proc/net/xt_ndpi/host_proto |grep YouTube
YouTube:youtubei.googleapis.com,youtube.,youtu.be.,yt3.ggpht.com,.googlevideo.com
YouTube:.ytimg.com,youtube-nocookie.
YouTubeUpload:upload.youtube.com,upload.video.google.com

[root@~ xt_ndpi]# cat /proc/net/xt_ndpi/proto |grep -v "# 0 debug=0"
#id     mark ~mask     name   # count #version 2.4.0-1318-a360566
00         0/000001ff Unknown          # 21 debug=0
05         5/000001ff DNS              # 379 debug=0
07         7/000001ff HTTP             # 6848 debug=0
08         8/000001ff MDNS             # 1 debug=0
0a         a/000001ff NetBIOS          # 6 debug=0
0e         e/000001ff SNMP             # 45 debug=0
10        10/000001ff SMB              # 9 debug=0
3c        3c/000001ff HTTP_Download    # 5592 debug=0

[root@~ xt_ndpi]# iptables -t mangle -L -vn
Chain PREROUTING (policy ACCEPT 175K packets, 135M bytes)
 pkts bytes target     prot opt in     out     source               destination
 122K 6006K            all  --  *      *       192.168.1.0/24       0.0.0.0/0            ndpi all protocols
 137K  197M            all  --  *      *       0.0.0.0/0            192.168.1.0/24       ndpi all protocols
    0     0 MARK       all  --  *      *       0.0.0.0/0            192.168.1.0/24       ndpi protocol YouTube MARK set 0x3ea
    0     0 MARK       all  --  *      *       192.168.1.0/24       0.0.0.0/0            ndpi protocol YouTube MARK set 0x3ea

Chain INPUT (policy ACCEPT 2751 packets, 149K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 172K packets, 135M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 4571 packets, 633K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 177K packets, 136M bytes)
 pkts bytes target     prot opt in     out     source               destination
 141K  202M            all  --  *      *       0.0.0.0/0            192.168.1.0/24       ndpi all protocols
 126K 6381K            all  --  *      *       192.168.1.0/24       0.0.0.0/0            ndpi all protocols
    0     0 MARK       all  --  *      *       0.0.0.0/0            192.168.1.0/24       ndpi protocol YouTube MARK set 0x3ea
    0     0 MARK       all  --  *      *       192.168.1.0/24       0.0.0.0/0            ndpi protocol YouTube MARK set 0x3ea

**Comment by elico** [comment]
@lyt0112 It is possible that Chrome is using either UDP based connection to google systems or it uses a proxy connection to them.
To make sure what happens on the network level you can try to block with firewall rules any port and protocol except:
- http(80/tcp)
- https(443/tcp)
- dns(53/udp)
- dns(53/tcp)
- ping(icmp*)

Then see what happens.
If it is still the same then maybe there is a way to find out what traffic chrome uses using wireshark and tcpdump.

**Comment by lyt0112** [comment]
@elico I used IE/forefox to test,and got same test result.
Finally,I chose betolj's ndpi-netfilter. 
I dropped the QUIC protocol to make Youtube can work on the Chrome.
All can work fine now...thanks for everyone's help...

**Comment by elico** [comment]
@lyt0112 On what OS did you installed the module?
If I would be able to test it I might be able to see what's wrong.
