### ISSUE TITLE
xt_ndpi: Warning! Hostdef 'mmg-fna.whatsapp.net' missmatch! Skipping.

### ISSUE THREAD

**Issue by clebig** [vel21ripn/nDPI#42]
Dear all, 

After having compiled the branch netfilter-2.6 and loaded the xt_ndpi module, I get the following in my dmesg :
`
[  486.886228] [NDPI] Missmatch 'ggpht.com' proto YouTube origin PlayStore
[  486.888417] xt_ndpi: Warning! Hostdef 'mmg-fna.whatsapp.net' missmatch! Skipping.
[  486.888537] xt_ndpi: Warning! Hostdef 'ggpht.com' missmatch! Skipping.

[  486.889990] xt_ndpi v1.2 ndpi 2.4.0-1320-97f4744 IPv6=YES debug_message=no
BT: hash_size 0k, hash_expiation 0 sec, log_size 128kb
sizeof hash_ip4p_node=44 id_struct=296 PATRICIA_MAXBITS=128
flow_struct=2024 packet_struct=1400
flow_tcp_struct=41 flow_udp_struct=27 int_one_line_struct=16
ndpi_ip_addr_t=16 ndpi_protocol=8 nf_ct_ext_ndpi=60
spinlock_t=4
NF_EXT_ID 9
[  486.889991] xt_ndpi MAX_PROTOCOLS 320 LAST_PROTOCOL 243`

I'm wondering the meaning of the 3 messages containing "Missmatch" and if it makes the corresponding dissectors unusable.

Then, I see `xt_ndpi v1.2 ndpi 2.4.0-1320-97f4744 IPv6=YES debug_message=no`. I compiled the netfilter-2.6 branch, so  what is the actual version of ndpi currently used by my xt_ndpi module ?

Thank you.
Clément

**Comment by vel21ripn** [comment]
No. These three lines say they are ignored in struct host_match [].
I know about the problem with 'ggpht.com' and in the near future I am going to fix it.

You loaded old module. branch-2.6 have string "xt_ndpi v1.2 ndpi 2.6.0-......"
Try "cd ndpi-netfilter/src ; insmod ./xt_ndpi.ko" after building module.

**Comment by clebig** [comment]
You are right, I was totally sure I did choose the netfilter-2.6 when I built it but I was still on 2.2... 

Actually, the missmatch errors disappeared now with netfilter-2.6 branch.

```
[336698.271028] xt_ndpi v1.2 ndpi 2.6.0-1422-2586e77 IPv6=YES debug_message=no
                 BT: hash_size 0k, hash_expiation 0 sec, log_size 128kb
                 sizeof hash_ip4p_node=44 id_struct=296 PATRICIA_MAXBITS=128
                 flow_struct=2056 packet_struct=1400
                   flow_tcp_struct=42 flow_udp_struct=27 int_one_line_struct=16
                 ndpi_ip_addr_t=16 ndpi_protocol=8 nf_ct_ext_ndpi=60
                 spinlock_t=4
                 NF_EXT_ID 9
[336698.271029] xt_ndpi MAX_PROTOCOLS 320 LAST_PROTOCOL 243
```
So everything is fine now.
