### ISSUE TITLE
Usages of --match-proto --match-master and --have-master

### ISSUE THREAD

**Issue by clebig** [vel21ripn/nDPI#43]
Dear Vitaly,

I've seen some new options (--match-proto --match-master and --have-master) in your libxt_ndpi code and I would like to know how to take benefit from them.

Could you give us an example of an usage of these options with an application relying on SSL or HTTP as master protocol ? In which situation are those option useful ?

Thank you,
Clément

**Comment by vel21ripn** [comment]
The option --match-master compares only with the main protocol for a match, and the option --match-proto checks both the main protocol and the application protocol.
SSL and HTTP have the parameter "hostname / certname" which can be compared through "--host-or-cert"

**Comment by clebig** [comment]
Thank you for your reply.
Does --host-or-cert option can deal with wildcards or can it work using just a word or a pattern that would represent a part of the FQDN or TLD (ex --host-or-cert faceb matching cdn.facebook.com) ?

**Comment by vel21ripn** [comment]
--host, --cert, --host-or-cert may be string or regexp.
'www' - substring 'www'
'/(com|info|net)$/'  - regexp ( first and last symbol is '/' )

For large domain list use "user defined protocols" and /proc/net/xt_ndpi/host_proto

**Comment by clebig** [comment]
that's wonderful, thank you !

**Comment by clebig** [comment]
I understand now why there is a new directory named libre and containing regex.c and regex.h :-). The new options are more than welcome.
