### ISSUE TITLE
After some changes ndpi stuck my system.

### ISSUE THREAD

**Issue by k0ste** [vel21ripn/nDPI#45]
When I was debugging for #41 I'll found my kernels stuck by unknown reason.
Debugging deeper I was found that is not involved by kernel, just ndpi updates. I checked this with last commit of netfilter-2.6 branch (1.2_2.6.0.1423.dfc2fc1), then I revert ndpi to stable version 1.2_2.3.0.1262.97099ff and bug is not reproducible. I use this version with kernel 4.17.13 from "Tue 07 Aug 2018 02:16:35 PM UTC" and this pretty stable for me.
I think only way out is test all commits from 97099ffbda6bf613e4698f2152f22721061f911b and find when it's start.

**Comment by vel21ripn** [comment]
Write me on the mail ilivie at guap dot ru, it will greatly speed up the process. All the letters "i" are superfluous.
