### ISSUE TITLE
BUILD_BUG_ON(NF_CT_EXT_NUM > 9) - On kernel 4.14.97

### ISSUE THREAD

**Issue by ummeegge** [vel21ripn/nDPI#46]
Hi,
wanted to report a problem with the v4.14.0.diff kernel patch. Am using an IPFire appliance with a 4.14.97 kernel . The problem log portion looks like this:

`
In file included from ./include/linux/init.h:5:0,
                 from ./include/linux/netfilter.h:5,
                 from net/netfilter/nf_conntrack_core.c:18:
In function 'total_extension_size',
    inlined from 'nf_conntrack_init_start' at net/netfilter/nf_conntrack_core.c:2011:2:
./include/linux/compiler.h:328:38: error: call to '__compiletime_assert_1977' declared with attribute error: BUILD_BUG_ON failed: NF_CT_EXT_NUM > 9
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
                                      ^
./include/linux/compiler.h:308:4: note: in definition of macro '__compiletime_assert'
    prefix ## suffix();    \
    ^~~~~~
./include/linux/compiler.h:328:2: note: in expansion of macro '_compiletime_assert'
  _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)
  ^~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:47:37: note: in expansion of macro 'compiletime_assert'
 #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
                                     ^~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:71:2: note: in expansion of macro 'BUILD_BUG_ON_MSG'
  BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
  ^~~~~~~~~~~~~~~~
net/netfilter/nf_conntrack_core.c:1977:2: note: in expansion of macro 'BUILD_BUG_ON'
  BUILD_BUG_ON(NF_CT_EXT_NUM > 9);
  ^~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:326: net/netfilter/nf_conntrack_core.o] Error 1
make[2]: *** [scripts/Makefile.build:585: net/netfilter] Error 2
`
you can also find the full build log in here --> https://people.ipfire.org/~ummeegge/logs/kernel_log_KCFG-ERROR-nDPI-netfilter . 

If you need some more information, just let it me know.

Best,

Erik

**Comment by vel21ripn** [comment]
Try patch v4.15.3.diff

**Comment by ummeegge** [comment]
The v4.15.3.diff works, thanks for the hint and in general thanks for your work.

Best,

Erik
