### ISSUE TITLE
[Help] Documentation or resources needed for using xt_ndpi.ko

### ISSUE THREAD

**Issue by ItsNayabSD** [vel21ripn/nDPI#48]
I have cross compiled `ndpi-netfilter` for ARM and able to load the `xt_ndpi` module successfully.

I am able to see `iptables -m ndpi --help` giving all the options related to ndpi and the supported protocols.

Would you please provide any document or resources on how to monitor the traffic and classify the information?

**Comment by vel21ripn** [comment]
All parameters of the xt_ndpi module are described in the file 
https://github.com/vel21ripn/nDPI/blob/netfilter-2.6/ndpi-netfilter/INSTALL.
Answers to other questions about nDPI need to look at https://github.com/ntop/nDPI.
I implemented the collection and accumulation of traffic information (similar to ipt_NETFLOW). Testing is almost complete. Perhaps in a week I will publish a new branch "flow_info".

**Comment by ItsNayabSD** [comment]
Thanks. I am looking forward to it.
