### ISSUE TITLE
The following error was reported in centos 7.2. How to resolve it

### ISSUE THREAD

**Issue by wangchuanfang** [vel21ripn/nDPI#53]
AUTHORS  COPYING  FLOW_INFO.txt  INSTALL  ipt  kernel-patch  libre  Makefile  README  src  tests
[root@test1 ndpi-netfilter]#make
make -C ipt
make[1]: Entering directory `/usr/src/kernels/nDPI/ndpi-netfilter/ipt'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/usr/src/kernels/nDPI/ndpi-netfilter/ipt'
make -C src
$xt_ndpi-y is [main.o ndpi_strcol.o ndpi_proc_parsers.o ndpi_proc_generic.o ndpi_proc_info.o  ndpi_proc_flow.o ndpi_proc_hostdef.o ndpi_proc_ipdef.o ../libre/regexp.o ../../src/lib/third_party/src/node.o ../../src/lib/third_party/src/ahocorasick.o ../../src/lib/third_party/src/libcache.o ../../src/lib/third_party/src/ndpi_patricia.o ../../src/lib/third_party/src/ht_hash.o ../../src/lib/third_party/src/btlib.o ../../src/lib/ndpi_main.o ../../src/lib/protocols/*.o]
make[1]: Entering directory `/usr/src/kernels/nDPI/ndpi-netfilter/src'
\
make  -C /lib/modules/3.10.0-327.el7.x86_64/build M=$PWD modules -w;
make[2]: Entering directory `/usr/lib/modules/3.10.0-327.el7.x86_64/build'
  CC [M]  /usr/src/kernels/nDPI/ndpi-netfilter/src/main.o
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_mt’:
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:1176:2: error: implicit declaration of function ‘xt_net’ [-Werror=implicit-function-declaration]
  n = ndpi_pernet(xt_net(par));
  ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:1176:2: warning: passing argument 1 of ‘ndpi_pernet’ makes pointer from integer without a cast [enabled by default]
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:349:32: note: expected ‘struct net *’ but argument is of type int’
 static inline struct ndpi_net *ndpi_pernet(struct net *net)
                                ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_tg’:
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:1564:9: warning: passing argument 1 of ‘ndpi_pernet’ makes pointer from integer without a cast [enabled by default]
  struct ndpi_net *n = ndpi_pernet(xt_net(par));
         ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:349:32: note: expected ‘struct net *’ but argument is of type int’
 static inline struct ndpi_net *ndpi_pernet(struct net *net)
                                ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c: At top level:
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2153:3: warning: initialization from incompatible pointer type [enabled by default]
   .hook  = ndpi_nat_do_chain,
   ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2153:3: warning: (near initialization for ‘nf_nat_ipv4_ops[0].hook’) [enabled by default]
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2159:3: warning: initialization from incompatible pointer type [enabled by default]
   .hook  = ndpi_nat_do_chain,
   ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2159:3: warning: (near initialization for ‘nf_nat_ipv4_ops[1].hook’) [enabled by default]
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2165:3: warning: initialization from incompatible pointer type [enabled by default]
   .hook  = ndpi_nat_do_chain,
   ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2165:3: warning: (near initialization for ‘nf_nat_ipv4_ops[2].hook’) [enabled by default]
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_net_exit’:
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2193:6: error: implicit declaration of function ‘nf_unregister_net_hooks’ [-Werror=implicit-function-declaration]
      nf_unregister_net_hooks(net, nf_nat_ipv4_ops, 
      ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2203:2: error: too few arguments to function ‘nf_ct_iterate_cleanup’
  nf_ct_iterate_cleanup(net, __ndpi_free_flow, n);
  ^
In file included from /usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:48:0:
include/net/netfilter/nf_conntrack.h:248:6: note: declared here
 void nf_ct_iterate_cleanup(struct net *net,
      ^
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c: In function ‘ndpi_net_init’:
/usr/src/kernels/nDPI/ndpi-netfilter/src/main.c:2477:7: error: implicit declaration of function ‘nf_register_net_hooks’ [-Werror=implicit-function-declaration]
       nf_register_net_hooks(net, nf_nat_ipv4_ops,
       ^
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/kernels/nDPI/ndpi-netfilter/src/main.o] Error 1
make[2]: *** [_module_/usr/src/kernels/nDPI/ndpi-netfilter/src] Error 2
make[2]: Leaving directory `/usr/lib/modules/3.10.0-327.el7.x86_64/build'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/usr/src/kernels/nDPI/ndpi-netfilter/src'
make: *** [all] Error 2
[root@test1 ndpi-netfilter]#

**Comment by vel21ripn** [comment]
Kernel version 3.10.0-327 is a mutant! It is no longer like the original series kernel 3.10.
To build a module you need to make changes to the code.
The easiest way to build this model is to upgrade to the current kernel version (4.4 and higher).

**Comment by wangchuanfang** [comment]
Ok, I'll try.Thank you very much
