### ISSUE TITLE
Compilation error for Linux kernel version 3.14

### ISSUE THREAD

**Issue by ItsNayabSD** [vel21ripn/nDPI#56]
Following is the error I am getting while compiling latest flow_info branch with the kernel verison 3.14.
```
make  -C /home/nayab/bld/sdk/build/projects/mod/linux-3.14.77 M=$PWD modules --no-print-directory;
  CC [M]  /home/nayab/bld/sdk/build/projects/mod/nDPI-flow/ndpi-netfilter/src/main.o
/home/nayab/bld/sdk/build/projects/mod/nDPI-flow/ndpi-netfilter/src/main.c: In function 'ct_proto_last':
/home/nayab/bld/sdk/build/projects/mod/nDPI-flow/ndpi-netfilter/src/main.c:215:17: error: implicit declaration of function 'READ_ONCE' [-Werror=implicit-function-declaration]
  return (struct nf_conn *)(READ_ONCE(cb->last_ct) & ~0x7ul);
``` 
In 3.14, there ar no definitions of `READ_ONCE` or `WRITE_ONCE`. Can you please update the code for kernel version 3.14?

**Comment by ItsNayabSD** [comment]
I have replaced `WRITE_ONCE` and `READ_ONCE` with `ACCESS_ONCE`. Does it make any problem?

**Comment by vel21ripn** [comment]
IMHO Most likely it will work.
I do not have the ability to test on old kernels (up to 4.14.x)

**Comment by ItsNayabSD** [comment]
It's working fine. I didn't run it for long though.
