### ISSUE TITLE
src/lib/ndpi_content_match.c.inc #if 0 line 23

### ISSUE THREAD

**Issue by clebig** [vel21ripn/nDPI#57]
Dear Vitaly, 

Is it normal to find <code># if 0</code> at line 23 in ndpi_content_match.c.inc https://github.com/vel21ripn/nDPI/commit/1b837da429a23c18bc805f90fb5c7b41104dff9e ?

**Comment by vel21ripn** [comment]
Yes!
Struct host_protocol_list[] is moved to ndpi_network_list.c.inc.
The file ndpi_network_list.c.inc is generated from ndpi_network_list_*.yaml
