### ISSUE TITLE
Cannot add user defined protocols. 

### ISSUE THREAD

**Issue by clebig** [vel21ripn/nDPI#59]
The folowing code returns me erros.
<code>
root@EgatewayNG:~/ndpimay/nDPI# echo "add_custom line_me"> /proc/net/xt_ndpi/proto
-bash: echo: write error: Invalid argument

root@EgatewayNG:~/ndpimay/nDPI# echo 'line_me:.line.naver.jp' >/proc/net/xt_ndpi/host_proto
-bash: echo: write error: Invalid argument
</code>

Running unmodified code based on commit 20e62533408c2e2577139e198572cb9e282b0cdd

```
echo  "add_custom line_me" >/proc/net/xt_ndpi/proto
cat >/proc/net/xt_ndpi/ip_proto <<EOF
103.2.28.0/24    line_me
103.2.30.0/23    line_me
119.235.224.0/20 line_me
147.92.128.0/17  line_me
203.104.128.0/20 line_me
203.104.144.0/21 line_me
203.104.152.0/22 line_me
203.104.156.0/23 line_me
203.104.158.0/24 line_me
EOF
echo 'line_me:.line.naver.jp' >/proc/net/xt_ndpi/host_proto
```

_Originally posted by @vel21ripn in https://github.com/vel21ripn/nDPI/pull/58#issuecomment-491731030_

**Comment by vel21ripn** [comment]
Show dmesg.
We need to add custom protocols before using it in iptables (after the module is loaded). I agree that this is not very convenient and I think that adding custom protocols can be allowed at any time.
See commit https://github.com/vel21ripn/nDPI/commit/a92e9877cc539e7ade6c39b055508c5d3d36c1b2

**Comment by clebig** [comment]
Yep, that's it !
<code>[4958810.129821] NDPI: iptables in use. can't create custom protocol! See README</code>

**Comment by clebig** [comment]
> Show dmesg.
> We need to add custom protocols before using it in iptables (after the module is loaded). I agree that this is not very convenient and I think that adding custom protocols can be allowed at any time.
> See commit [a92e987](https://github.com/vel21ripn/nDPI/commit/a92e9877cc539e7ade6c39b055508c5d3d36c1b2)

Flushing existing iptables rules and applying it before restoring the rules is enough or do we have to conntrack -F && rmmod xt_ndpi.ko && insmod xt_ndpi.ko too ?

**Comment by vel21ripn** [comment]
ip_proto and host_proto may be changed in any time.
After commit a92e987, custom protocols can be added at any time.
Before this commit, you could add a custom protocol only after the module was loaded and before the first rule in iptables using the ndpi extension.

**Comment by clebig** [comment]
Compiled and installed https://github.com/vel21ripn/nDPI/commit/a92e9877cc539e7ade6c39b055508c5d3d36c1b2. 
It works as expected. 
Thank you.
