### ISSUE TITLE
All traffic marked as "error"

### ISSUE THREAD

**Issue by wirelessmundi** [vel21ripn/nDPI#6]
Hi,

I compiled ndpi-netfilter against kernel 4.4.X given instructions in INSTALL file.

When testing with the following script (checking out http, all, unknown and error), iptables counters show that all traffic is classified as "error" by ndpi-netfilter!

script:
iptables -t mangle -A PREROUTING -m ndpi --http -j LOG
iptables -t mangle -A PREROUTING -m ndpi --all -j LOG
iptables -t mangle -A PREROUTING -m ndpi --unknown -j LOG
iptables -t mangle -A PREROUTING -m ndpi --error -j LOG

I tried loading module with options log_debug=100 and log_trace=100, but it only gives me lots of initialization messages, nothing showing what the errors could be.

What could I be doing wrong? Is there a way to debug?

I tested with and without the kernel patch (with/without CONNLABELS), and I get the same error.

**Comment by vel21ripn** [comment]
It is necessary to check the traffic in both directions. 

> iptables -t mangle -A PREROUTING -m ndpi --all
> iptables -t mangle -A PREROUTING -m ndpi --error -j LOG
> iptables -t mangle -A OUTPUT -m ndpi --all
> iptables -t mangle -A POSTROUTING -m ndpi --error -j LOG

See "grep -a . /sys/module/xt_ndpi/parameters/*"

Debug level may be changed via "echo 2  >/sys/modules/xt_ndpi/log_debug"

**Comment by wirelessmundi** [comment]
Sorry i forgot to mention I had the same rules in POSTROUTING. Adding OUTPUT rules does not change much.

I will try the log_debug, thanks for the suggestion.

I see a non-zero "err_oversize" when executing checking out the xt_ndpi parameters in /sys (see output below), not sure what it means:

_# grep -a . /sys/module/xt_ndpi/parameters/*
/sys/module/xt_ndpi/parameters/bt_gc_count:0
/sys/module/xt_ndpi/parameters/bt_hash_size:0
/sys/module/xt_ndpi/parameters/bt_hash_timeout:1200
/sys/module/xt_ndpi/parameters/bt_log_size:128
/sys/module/xt_ndpi/parameters/cached:0
/sys/module/xt_ndpi/parameters/c_all_not:0
/sys/module/xt_ndpi/parameters/c_ct_not:0
/sys/module/xt_ndpi/parameters/c_id_not:0
/sys/module/xt_ndpi/parameters/c_skb_not:0
/sys/module/xt_ndpi/parameters/ct_confirm:213742
/sys/module/xt_ndpi/parameters/err_add_ndpi:0
/sys/module/xt_ndpi/parameters/err_alloc_flow:0
/sys/module/xt_ndpi/parameters/err_alloc_id:0
/sys/module/xt_ndpi/parameters/err_bad_tcp_udp:0
/sys/module/xt_ndpi/parameters/err_ip_frag_len:0
/sys/module/xt_ndpi/parameters/err_oversize:784
/sys/module/xt_ndpi/parameters/err_prot_err:0
/sys/module/xt_ndpi/parameters/err_prot_err1:0
/sys/module/xt_ndpi/parameters/err_skb_linear:0
/sys/module/xt_ndpi/parameters/flow_created:0
/sys/module/xt_ndpi/parameters/flow_deleted:0
/sys/module/xt_ndpi/parameters/id_num:0
/sys/module/xt_ndpi/parameters/ipv4:214526
/sys/module/xt_ndpi/parameters/ipv6:0
/sys/module/xt_ndpi/parameters/l4mismatch:0
/sys/module/xt_ndpi/parameters/l4mis_size:0
/sys/module/xt_ndpi/parameters/log_debug:0
/sys/module/xt_ndpi/parameters/log_trace:0
/sys/module/xt_ndpi/parameters/max_parsed_lines:0
/sys/module/xt_ndpi/parameters/mtu:1520
/sys/module/xt_ndpi/parameters/ndpi_match:213739
/sys/module/xt_ndpi/parameters/ndpi_size_flow_struct:904
/sys/module/xt_ndpi/parameters/ndpi_size_hash_ip4p_node:44
/sys/module/xt_ndpi/parameters/ndpi_size_id_struct:256
/sys/module/xt_ndpi/parameters/noncached:0
/sys/module/xt_ndpi/parameters/nonip:0
/sys/module/xt_ndpi/parameters/non_tcpudp:1000
/sys/module/xt_ndpi/parameters/skb_lin:0
/sys/module/xt_ndpi/parameters/skb_seg:0_

**Comment by wirelessmundi** [comment]
Changing log_debug does not generate any output in dmesg.

Tried with the following cmd:
_echo 2 >/sys/modules/xt_ndpi/parameters/log_debug_

**Comment by vel21ripn** [comment]
> err_oversize:784 

You have packets larger than 1500 bytes. 
Increase the mtu parameter for xt_ndpi  or disable sg, tso, gso, gro via Ethtool on NIC.
After "echo 2  >/sys/modules/xt_ndpi/parameters/log_debug"

> Oct 24 13:56:02 ls-gw-r2 kernel: process     skb ffff8800c8cdfe00 ct ffff88041c96a120 proto 17 188.233.038.108:19768 -> 194.226.199.004:27954 len 54
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff8800c8cdfe00 ct ffff88041c96a120 proto 17 188.233.038.108:19768 -> 194.226.199.004:27954 len 54
> Oct 24 13:56:02 ls-gw-r2 last message repeated 26 times
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff8800c8cdfe00 ct ffff8804108130e0 proto 6 012.129.242.024:3724 -> 194.226.199.004:56528 len 40
> Oct 24 13:56:02 ls-gw-r2 last message repeated 34 times
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff8800c8cdfe00 ct ffff88040d44ea20 proto 6 194.226.199.061:29039 -> 068.232.035.098:443 len 40
> Oct 24 13:56:02 ls-gw-r2 last message repeated 34 times
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff880411aad300 ct ffff8804104799e0 proto 6 194.226.199.003:63774 -> 089.108.105.040:80 len 554
> Oct 24 13:56:02 ls-gw-r2 last message repeated 33 times
> Oct 24 13:56:02 ls-gw-r2 kernel: process     skb ffff8800c8cdfe00 ct ffff88040dedeb40 proto 17 194.226.199.004:53341 -> 031.200.233.026:50824 len 116
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff8800c8cdfe00 ct ffff88040d3cf560 proto 6 194.226.199.059:51971 -> 074.125.110.081:443 len 52
> Oct 24 13:56:02 ls-gw-r2 last message repeated 21 times
> Oct 24 13:56:02 ls-gw-r2 kernel: process     skb ffff88040f369400 ct ffff88040d44ea20 proto 6 194.226.199.061:29039 -> 068.232.035.098:443 len 40
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff88040f369400 ct ffff88040d44ea20 proto 6 194.226.199.061:29039 -> 068.232.035.098:443 len 40
> Oct 24 13:56:02 ls-gw-r2 last message repeated 11 times
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff88041bf24d00 ct ffff88040d44ea20 proto 6 068.232.035.098:443 -> 194.226.199.061:29039 len 1500
> Oct 24 13:56:02 ls-gw-r2 last message repeated 15 times
> Oct 24 13:56:02 ls-gw-r2 kernel: process     skb ffff88040d768c00 ct ffff88040d44ea20 proto 6 068.232.035.098:443 -> 194.226.199.061:29039 len 1500
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff88040d768c00 ct ffff88040d44ea20 proto 6 068.232.035.098:443 -> 194.226.199.061:29039 len 1500
> Oct 24 13:56:02 ls-gw-r2 last message repeated 16 times
> Oct 24 13:56:02 ls-gw-r2 kernel: process     skb ffff88040f369400 ct ffff88040d44ea20 proto 6 194.226.199.061:29039 -> 068.232.035.098:443 len 40
> Oct 24 13:56:02 ls-gw-r2 kernel: cache       skb ffff88040f369400 ct ffff88040d44ea20 proto 6 194.226.199.061:29039 -> 068.232.035.098:443 len 40

**Comment by wirelessmundi** [comment]
Ok, I've ensured the mtu was 1500, and disabled all eth's feature to be sure (see following ethtool commands), but iptables still only counts the --error.

_# iptables -t mangle -L POSTROUTING -v
Chain POSTROUTING (policy ACCEPT 348 packets, 35808 bytes)
 pkts bytes target     prot opt in     out     source               destination  
    0     0 LOG        all  --  any    any     anywhere             anywhere             ndpi protocol http LOG level warning
    0     0 LOG        all  --  any    any     anywhere             anywhere             ndpi all protocols LOG level warning
    0     0 LOG        all  --  any    any     anywhere             anywhere             ndpi protocol unknown LOG level warning
  348 35808 LOG        all  --  any    any     anywhere             anywhere             ndpi error LOG level warning_

The only difference is that now the xt_ndpi parameters do not show anything in error counter anymore!

Also, I still don't see any output after activating debug log like so:
_echo 2 >/sys/module/xt_ndpi/parameters/log_debug_

*\* ethtool commands:
_ethtool -K eth0 tso off
ethtool -K eth0 gro off
ethtool -K eth0 lro off
ethtool -K eth0 gso off
ethtool -K eth0 rx off
ethtool -K eth0 tx off
ethtool -K eth0 sg off
ethtool -K eth0 rxvlan off
ethtool -K eth0 txvlan off_

*\* iptables commands (done also in POSTROUTING and OUTPUT)
_iptables -t mangle -A PREROUTING -m ndpi --http -j LOG
iptables -t mangle -A PREROUTING -m ndpi --all -j LOG
iptables -t mangle -A PREROUTING -m ndpi --unknown -j LOG
iptables -t mangle -A PREROUTING -m ndpi --error -j LOG_

*\* xt_ndpi parameters output:
_# grep -a . /sys/module/xt_ndpi/parameters/*
/sys/module/xt_ndpi/parameters/bt_gc_count:0
/sys/module/xt_ndpi/parameters/bt_hash_size:0
/sys/module/xt_ndpi/parameters/bt_hash_timeout:1200
/sys/module/xt_ndpi/parameters/bt_log_size:128
/sys/module/xt_ndpi/parameters/cached:0
/sys/module/xt_ndpi/parameters/c_all_not:0
/sys/module/xt_ndpi/parameters/c_ct_not:0
/sys/module/xt_ndpi/parameters/c_id_not:0
/sys/module/xt_ndpi/parameters/c_skb_not:0
/sys/module/xt_ndpi/parameters/ct_confirm:3698
/sys/module/xt_ndpi/parameters/err_add_ndpi:0
/sys/module/xt_ndpi/parameters/err_alloc_flow:0
/sys/module/xt_ndpi/parameters/err_alloc_id:0
/sys/module/xt_ndpi/parameters/err_bad_tcp_udp:0
/sys/module/xt_ndpi/parameters/err_ip_frag_len:0
/sys/module/xt_ndpi/parameters/err_oversize:0
/sys/module/xt_ndpi/parameters/err_prot_err:0
/sys/module/xt_ndpi/parameters/err_prot_err1:0
/sys/module/xt_ndpi/parameters/err_skb_linear:0
/sys/module/xt_ndpi/parameters/flow_created:0
/sys/module/xt_ndpi/parameters/flow_deleted:0
/sys/module/xt_ndpi/parameters/id_num:0
/sys/module/xt_ndpi/parameters/ipv4:3697
/sys/module/xt_ndpi/parameters/ipv6:0
/sys/module/xt_ndpi/parameters/l4mismatch:0
/sys/module/xt_ndpi/parameters/l4mis_size:0
/sys/module/xt_ndpi/parameters/log_debug:2
/sys/module/xt_ndpi/parameters/log_trace:0
/sys/module/xt_ndpi/parameters/max_parsed_lines:0
/sys/module/xt_ndpi/parameters/mtu:1520
/sys/module/xt_ndpi/parameters/ndpi_match:3697
/sys/module/xt_ndpi/parameters/ndpi_size_flow_struct:904
/sys/module/xt_ndpi/parameters/ndpi_size_hash_ip4p_node:44
/sys/module/xt_ndpi/parameters/ndpi_size_id_struct:256
/sys/module/xt_ndpi/parameters/noncached:0
/sys/module/xt_ndpi/parameters/nonip:0
/sys/module/xt_ndpi/parameters/non_tcpudp:48
/sys/module/xt_ndpi/parameters/skb_lin:0
/sys/module/xt_ndpi/parameters/skb_seg:0_

**Comment by wirelessmundi** [comment]
Note that I always had a positive value in _ndpi_match_ so something seems to be working!

Unfortunately it seems that iptables cannot see the match results somehow (--all or --unknown should have counters > 0), and the log_debug doesn't generate output.

**Comment by vel21ripn** [comment]
> ct_confirm:3698

This is "nf_conntrack" problems:
can't get nf_ct_get (skb,...) or nf_ct_is_untracked(ct) or nf_ct_is_confirmed(ct)

"conntrack -F" did not help?

> and the log_debug doesn't generate output.

Before the packet processing is not reached, that there is no protocol.

**Comment by wirelessmundi** [comment]
Yehehe! Thanks a lot for the help, I got it working thanks to what you just said.

I noticed that "conntrack -L" was empty, i know that it happens when i have no "-m conntrack" rules, so I just added a random one to make conntrack work:
_iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j LOG_

And xt_ndpi started to work and the "--error" counter stopped increasing!!!

Could xt_ndpi load all dependencies (nf_conntrack, xt_conntrack, and maybe connlabels stuff) automatically?

**Comment by k0ste** [comment]
> Could xt_ndpi load all dependencies (nf_conntrack, xt_conntrack, and maybe connlabels stuff) automatically?

You can do it yourself in the order in which you want via [systemd-modules-load](https://www.freedesktop.org/software/systemd/man/modules-load.d.html).

`for e in `ls /etc/modules-load.d/*|sort`; do echo -e "File $e:\n---------------" ; cat $e ; echo -e "\n"; done`

``` shell
File /etc/modules-load.d/10-htb.conf:
---------------
sch_htb


File /etc/modules-load.d/20-conntrack.conf:
---------------
nf_conntrack
nf_conntrack_netlink
nf_nat_ipv4
nf_nat
nf_reject_ipv4
nf_defrag_ipv4
nf_conntrack_ipv4
nf_conntrack_pptp
nf_conntrack_proto_gre
nfnetlink


File /etc/modules-load.d/98-ndpi.conf:
---------------
xt_ndpi


File /etc/modules-load.d/99-netflow.conf:
---------------
ipt_NETFLOW
```

**Comment by wirelessmundi** [comment]
Thanks k0ste, I know one can do it manually or with an init script, that's actually what we are doing right now.

I was just wondering if could be loaded automatically with modprobe, I thought maybe depmod could find out external symbols used by the module and allow for this to happen!
