### ISSUE TITLE
[Help] Deleting the iptable rule

### ISSUE THREAD

**Issue by ItsNayabSD** [vel21ripn/nDPI#60]
I have added the following iptbale rule. Rule added successfully as I have verified with `iptables-save` command.

> iptables -t mangle -A PREROUTING -m ndpi ! --error -j NDPI --flow-info

I wanted to remove that rule to unload the xt_ndpi kernel module. I have used the following command to remove the rule. But I am getting the error.
```
iptables -t mangle -D PREROUTING -m ndpi ! --error -j NDPI --flow-info
iptables: No chain/target/match by that name.
```
Somebody tell me the proper way to remove it please....

**Comment by clebig** [comment]
Type
 iptables -t mangle -nvL PREROUTING --line

Look at the number of the line of your interest then

iptables -t mangle -D PREROUTING [NUMBER]
