### ISSUE TITLE
Youtube not intercepted in bridge

### ISSUE THREAD

**Issue by UnveilTech** [vel21ripn/nDPI#61]
Hello,
not sure if that issue was already posted:
latest ndpi_flows compiled and installed, all is ok with a computer with 2 NICs (2 IP addr.)
but same computer 2 NICs in bridge, then Youtube is not intercepted when Facebook, SSL, etc... are done correctly.
computer with the next Debian 10 (testing build) using official brctl package.
config of the bridge:
auto lo
iface lo inet loopback

auto br0
iface br0 inet static
	bridge_ports enp2s0 enp1s0
	address 192.168.2.10
	netmask 255.255.255.0
	gateway 192.168.2.1
	broadcast 192.168.2.255
	bridge_stp off
	bridge_waitport 0
	bridge_fd 0

iptables:
:POSTROUTING ACCEPT [191352:88792994]
:qosmark - [0:0]
-A PREROUTING -j qosmark
-A PREROUTING -m ndpi  --all
-A PREROUTING -i br0 -m ndpi ! --error -j NDPI --flow-info
-A OUTPUT -j qosmark
-A OUTPUT -m ndpi  --all
-A POSTROUTING -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A POSTROUTING -o br0 -m ndpi ! --error -j NDPI --flow-info
-A qosmark -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A qosmark -m mark --mark 0x0 -j MARK --set-xmark 0xffff/0xffffffff
-A qosmark -m connbytes --connbytes 10 --connbytes-mode packets --connbytes-dir both -j RETURN
-A qosmark -m ndpi  --Facebook  -j MARK --set-xmark 0x40/0xffffffff
-A qosmark -m ndpi  --YouTube  -j MARK --set-xmark 0x80/0xffffffff

is something missing from my side or maybe Youtube cannot be detected in bridge ?

thanks in advance.
Bye David

**Comment by vel21ripn** [comment]
Do you analyze traffic between bridge interfaces or between a bridge and another network interface?
To analyze the traffic inside the bridge, you need sysctl net.bridge.bridge-nf-call-iptables = 1

**Comment by UnveilTech** [comment]
Hi,
thanks, we'll test the sysctl on next monday.

in the meantime i have another question, how to delete a protocol from the "/proc/net/xt_ndpi/proto" ?
let say we add a custom proto then we need to delete it because we failed in the naming.
we tried: echo "reset myproto" >/proc/net/xt_ndpi/proto, but it does not work.

bye David

**Comment by vel21ripn** [comment]
No way for remove/rename protocol from the /proc/net/xt_ndpi/proto :(
The command "reset"  not available  for the  /proc/net/xt_ndpi/proto.
Use rmmod/modprobe for removing custom protocols.

**Comment by UnveilTech** [comment]
Hi,
bridge is now ok.
thanks for your help
