### ISSUE TITLE
[Help] Behaviour of `read_all`, `read_closed` and `read_flows`

### ISSUE THREAD

**Issue by ItsNayabSD** [vel21ripn/nDPI#62]
Hi,

I am not seeing any difference in some particular flow when I changed the read modes.

> [root@me ~]# 
> [root@me ~]# echo "read_all" > /proc/net/xt_ndpi/flows
> [root@me ~]# 
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925" 
> 1559219925 1559221206 4 17 115.111.4.108 4500 192.168.101.61 43333 145 0 5 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221226 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221246 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]#
> [root@me ~]#
> [root@me ~]# echo "read_closed" > /proc/net/xt_ndpi/flows
> [root@me ~]#
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221266 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221286 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221306 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221326 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221346 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221366 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]#
> [root@me ~]#
> [root@me ~]# echo "read_flows" > /proc/net/xt_ndpi/flows
> [root@me ~]#
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221386 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221406 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec
> [root@me ~]# cat /proc/net/xt_ndpi/flows | grep "1559219925"
> 1559219925 1559221426 4 17 115.111.4.108 4500 192.168.101.61 43333 29 0 1 0 I=38,0 P=IPsec

Am I doing anything wrong here? My understanding is that with `read_closed` mode, the flow which started with start time `1559219925` should not show up until the flow is finished. If that particular IP `115.111.4.108` shows up again in the flow, the start time should be different.

**Comment by vel21ripn** [comment]
The “echo read_closed >/proc/net/xt_ndpi/ flow” command changes only the read mode until the file is closed.
The following command "cat /proc/net/xt_ndpi/flow" will read the data in the "read_all" mode.
bash is not suitable for reading data in modes other than read_all.

**Comment by ItsNayabSD** [comment]
Thanks @vel21ripn .

How do you suggest me to save the `/proc/net/xt_ndpi/flows` data in `read_closed` mode into a separate file? Currently I am using `open` system call to save the content to a separate file. I guess it's storing in `read_all` mode only.
