### ISSUE TITLE
Proposal: new protos to add

### ISSUE THREAD

**Issue by UnveilTech** [vel21ripn/nDPI#63]
Hello,
is that possible to add those new protos, here are details:

Proto: Tiktok
Protocol_ids: NDPI_PROTOCOL_TIKTOK
Protocol_risk: NDPI_PROTOCOL_FUN
Category: NDPI_PROTOCOL_CATEGORY_SOCIAL_NETWORK
domains: .musical.ly, .muscdn.com, .tiktokcdn.com

Proto: Xvideos
Protocol_ids: NDPI_PROTOCOL_XVIDEOS
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_PORN (to be created)
domains: .xvideos.com, .xnxx.com, .xvideos-cdn.com, .xnxx-cdn.com

Proto: iGamecg
Protocol_ids: NDPI_PROTOCOL_IGAMECG
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_GAME
domains: .igamecj.com

Proto: Blizzard
Protocol_ids: NDPI_PROTOCOL_BLIZZARD
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_GAME
domains: .blizzard.com

Proto: Hastidownload
Protocol_ids: NDPI_PROTOCOL_HASTIDOWNLOAD
Protocol_risk: NDPI_PROTOCOL_ACCEPTABLE
Category: NDPI_PROTOCOL_CATEGORY_MEDIA
domains: .hastidownload.at, .hastidownload.com, .hastidownload.me, .hastidownload.pw, .hastidownload.us

Proto: Film2movie
Protocol_ids: NDPI_PROTOCOL_FILM2MOVIE
Protocol_risk: NDPI_PROTOCOL_ACCEPTABLE
Category: NDPI_PROTOCOL_CATEGORY_MEDIA
domains: .film2movie.biz, .film2movie.co, .film2movie.me, .film2movie.us

Proto: LimelightNetworks
Protocol_ids: NDPI_PROTOCOL_LLN
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_WEBHOSTING (to be created)
domains: .llnwd.net

Proto: Aparat
Protocol_ids: NDPI_PROTOCOL_APARAT
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_MEDIA
domains: .aparat.com

Proto: Vimeo
Protocol_ids: NDPI_PROTOCOL_VIMEO
Protocol_risk: NDPI_PROTOCOL_FUN
Category: NDPI_PROTOCOL_CATEGORY_MEDIA
domains: .vimeo.com, .vimeocdn.com

Proto: Samsung
Protocol_ids: NDPI_PROTOCOL_SAMSUNG
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_SYSTEM_OS
domains: .samsungapps.com, .ospserver.net, .samsungdm.com

Proto: Mediafire
Protocol_ids: NDPI_PROTOCOL_MEDIAFIRE
Protocol_risk: NDPI_PROTOCOL_ACCEPTABLE
Category: NDPI_PROTOCOL_WEBHOSTING
domains: .mediafire.com

Proto: Mega
Protocol_ids: NDPI_PROTOCOL_MEGA
Protocol_risk: NDPI_PROTOCOL_ACCEPTABLE
Category: NDPI_PROTOCOL_WEBHOSTING
domains: .mega.co.nz

Proto: Perfectgirls
Protocol_ids: NDPI_PROTOCOL_PERFECTGIRLS
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_PORN
domains: .perfectgirls.net

Proto: Adobe
Protocol_ids: NDPI_PROTOCOL_ADOBE
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_SW_UPDATE
domains: .adobe.com

Proto: Blackberry
Protocol_ids: NDPI_PROTOCOL_BLACKBERRY
Protocol_risk: NDPI_PROTOCOL_SAFE
Category: NDPI_PROTOCOL_CATEGORY_SYSTEM_OS
domains: .blackberry.com

we tried to give all infos, if something missing, just ask :)
bye David

**Comment by vel21ripn** [comment]
ndpi-netfilter don't support "Protocol_risk" and "Category".
Read the nDPI ndpi-netfilter/INSTALL file.
Find the "Adding user-defined protocol" and "/proc/net/xt_ndpi/host_proto"

**Comment by UnveilTech** [comment]
ok thanks
