### ISSUE TITLE
Getting wireless interface index

### ISSUE THREAD

**Issue by ItsNayabSD** [vel21ripn/nDPI#65]
Please show the output of the command
```
ip ro
```
Sorry for the late reply. Here is the output

```
[root@TheBOX ~]# ip ro
default via 192.168.101.1 dev br-lan 
127.0.0.0/8 dev lo  scope link 
192.168.96.0/20 dev br-lan  proto kernel  scope link  src 192.168.104.23 
```
_Originally posted by @vel21ripn in https://github.com/vel21ripn/nDPI/issues/64#issuecomment-505444131_

**Comment by vel21ripn** [comment]
Definition of a physical interface for bridge/vlan/bond is not planned. 
You can mark connections through connmark with different labels depending on the physical interface ( -m physdev ).
In the file /proc/net/xt_ndpi/flows for a connection with a non-zero connmark there will be a field "CM=xxxx"
