### ISSUE TITLE
Quickstart guide?

### ISSUE THREAD

**Issue by mrbluecoat** [vel21ripn/nDPI#69]
Is there a quickstart guide for implementing nDPI in the kernel?  For example, various issues reference https://github.com/betolj/ndpi-netfilter , https://github.com/ewildgoose/ndpi-netfilter , libnetfilter_conntrack , etc. and there's also a lot of back-and-forth dialog with tickets like https://github.com/vel21ripn/nDPI/issues/40 which can be difficult to follow.  It would be great to have a clear and concise "hello world" quickstart guide that, for example, shows you how to compile nDPI on Raspbian and then block YouTube.

P.S. Great work on this project!

**Comment by vel21ripn** [comment]
I do not consider nDPI as a means of reliably blocking traffic.
In some cases, the protocol will be determined after several packets with a payload, which is not a complete blocking of the protocol.
I see nDPI as monitoring, accounting, and a classifier for prioritizing traffic.
Anyone who knows how to compile the kernel and packages from the source code will be able to compile nDPI. Now the  patch for kernel is not needed.

**Comment by mrbluecoat** [comment]
Sounds good, thanks
