### ISSUE TITLE
netfilter install on ubuntu 18.0.4

### ISSUE THREAD

**Issue by joeneh28** [vel21ripn/nDPI#70]
hi
i am facing problem while trying to install netfilter on ubuntu 18.0.4 
can you please help 

thank you

**Comment by vel21ripn** [comment]
What problem you are facing?

**Comment by joeneh28** [comment]
root@ntopng:/nDPI/ndpi-netfilter# make
make -C ipt
make[1]: Entering directory '/nDPI/ndpi-netfilter/ipt'
cc -fPIC -I../.. -I../../src/include -I../../src/lib -I../src -I../libre -DOPENDPI_NETFILTER_MODULE -O2 -Wall   -c -o libxt_ndpi.o libxt_ndpi.c
libxt_ndpi.c:34:10: fatal error: ndpi_config.h: No such file or directory
 #include "ndpi_config.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'libxt_ndpi.o' failed
make[1]: *** [libxt_ndpi.o] Error 1
make[1]: Leaving directory '/nDPI/ndpi-netfilter/ipt'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
root@ntopng:/nDPI/ndpi-netfilter#

**Comment by vel21ripn** [comment]
ndpi-netfilter/INSTALL
```
./autogen.sh
( cd src/lib ; make ndpi_network_list.c.inc )
cd  ndpi-netfilter
make
```
