### ISSUE TITLE
echo reset >/proc/net/xt_ndpi/ip_proto

### ISSUE THREAD

**Issue by prozaklob** [vel21ripn/nDPI#71]
```
echo reset >/proc/net/xt_ndpi/ip_proto
echo: write error: Invalid argument
```

Добавление не ругается,но в файле записи не появляется
`echo "10.10.10.10 bad_ip" > /proc/net/xt_ndpi/ip_proto`

**Comment by vel21ripn** [comment]
reset для ip_proto отсутствует.

```
echo "add_custom bad_ip" >/proc/net/xt_ndpi/proto 
echo '223.255.255.255 bad_ip' >/proc/net/xt_ndpi/ip_proto
grep bad_ip /proc/net/xt_ndpi/ip_proto
```
Вроде работает.

**Comment by prozaklob** [comment]
> reset для ip_proto отсутствует.
> 
> ```
> echo "add_custom bad_ip" >/proc/net/xt_ndpi/proto 
> echo '223.255.255.255 bad_ip' >/proc/net/xt_ndpi/ip_proto
> grep bad_ip /proc/net/xt_ndpi/ip_proto
> ```
> 
> Вроде работает.

а как дропнуть список адресов?

**Comment by prozaklob** [comment]
`echo "add_custom bad_ip" > /proc/net/xt_ndpi/proto;`

```
 grep bad_ip /proc/net/xt_ndpi/proto
f4        f4/000001ff bad_ip           # 0 debug=0

```

```
iptables -A FORWARD -m ndpi --bad_ip -j DROP
iptables v1.8.2 (nf_tables): unknown option "--bad_ip"
```

**Comment by vel21ripn** [comment]
```
sed -e '2,$ s/^/-/' /proc/net/xt_ndpi/ip_proto >/tmp/remove_ip
cat /tmp/remove_ip >/proc/net/xt_ndpi/ip_proto
```
Спасибо за обнаружение 2-х ошибок.

**Comment by prozaklob** [comment]
> ```
> sed -e '2,$ s/^/-/' /proc/net/xt_ndpi/ip_proto >/tmp/remove_ip
> cat /tmp/remove_ip >/proc/net/xt_ndpi/ip_proto
> ```
> 
> Спасибо за обнаружение 2-х ошибок.

еще нашел проблему:

Делаю
`echo "add_custom badip" > /proc/net/xt_ndpi/proto;`
Работает.

Далее делаю:
`echo "add_custom badhost" > /proc/net/xt_ndpi/proto;`

```
grep bad /proc/net/xt_ndpi/proto
f3        f3/000001ff badip            # 86 debug=0
f4        f4/000001ff badhost          # 0 debug=0
```

```
 iptables -m ndpi --badhost
iptables v1.8.2 (nf_tables): unknown option "--badhost"
Try `iptables -h' or 'iptables --help' for more information.
```

не даёт подгрузить 2 кастомных протокола,хотя оба есть в proto

**Comment by vel21ripn** [comment]
iptables -m ndpi --proto badhost ?

**Comment by prozaklob** [comment]
> iptables -m ndpi --proto badhost ?

```
iptables -m ndpi --proto badhost
iptables v1.8.2 (nf_tables): no command specified
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by stasn77** [comment]
iptables -A FORWARD -m ndpi --proto badhost

**Comment by prozaklob** [comment]
> iptables -A FORWARD -m ndpi --proto badhost

try. thx
