### ISSUE TITLE
не отрабатывают правила в бридже not work rules on bridge

### ISSUE THREAD

**Issue by prozaklob** [vel21ripn/nDPI#73]
Доброго времени суток!

на сервере собран бридж в интерфейс br0 из двух интерфейсов
Пытаюсь применить правила DROP по списку bad_host/bad_ip

Правила не срабатывают

```
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-arptables = 1
```

```
Варианты правил,которые пробовались:
iptables -A FORWARD -m ndpi --bad_host -m physdev --physdev-is-bridge -j DROP
iptables -A FORWARD -m ndpi --bad_host -j DROP
с указанием --proto bad_host
с -i br0 то
```

не срабатывает правило и касательно штатных протоколов аЛя bittorrent и youtube

Возможно в системе нужно что-то дополнительно включить?
С такой проблемой уже сталкивался,плясал с бубном долго,но не могу вспомнить что сделал.

Один из нюансов в этой ситуации:
винты ( Система ) переехали на другое железо,интерфейсы из бриджа сменили название. ( хотя в прошлый раз не работало и не родной машине )
Спасибо!

**Comment by elico** [comment]
@prozaklob have you seen: https://github.com/vel21ripn/nDPI/issues/26 ?

**Comment by prozaklob** [comment]
Вопрос снят.
Оба линка бриджа были подключены в trunk порты,на которых висел vlan и внутри vlan ходил трафик.
Переделал порты в access и всё полетело.
Предполагаемый один из выходов - создать vlan на сервере DPI.
