### ISSUE TITLE
Is --proto option in iptables command mandatory now?

### ISSUE THREAD

**Issue by sharonenoch** [vel21ripn/nDPI#77]
Hi

I had compiled the flow_info-3.2 branch and the default flow_info branch.. The former does not seem to be accepting the old format of entering iptables commands. It keeps giving error. It only accepts it with --proto option.. 

root@r2:~/nDPI/ndpi-netfilter/ipt# iptables -A INPUT -m ndpi --youtube -j DROP
iptables v1.6.1: unknown option "--youtube"
Try `iptables -h' or 'iptables --help' for more information.

root@r2:~/nDPI/ndpi-netfilter/ipt# iptables -A INPUT -m ndpi **--proto** youtube -j DROP

but when viewed in iptables-save it gives the string below without the --proto option

root@r2:~/nDPI/ndpi-netfilter/ipt# iptables-save | grep -i ndpi
-A INPUT -m ndpi  --youtube  -j DROP

The flow_info branch accepts the old format without the --proto option and the iptables-save matches.

Just wanted to make sure if we are going to use --proto moving forward so that I can change my local scripts accordingly. I am using Ubuntu 18.04 with the default kernel 4.15.0-20-generic

**Comment by vel21ripn** [comment]
Yes, now only "--proto name[,proto...]"
nDPI-3.2 has 249 built-in protocols and, together with other options, exceeds the iptables limit of 256 options :(

> The flow_info branch accepts the old format without the --proto option and the iptables-save matches.

Thanks. I will fix it. This is not the only problem.

**Comment by sharonenoch** [comment]
Thanks for the fixes uploaded. I will test them today

**Comment by sharonenoch** [comment]
Working good
