### ISSUE TITLE
ipaddress range hex values are not proper. Throws warning during compilation 

### ISSUE THREAD

**Issue by sharonenoch** [vel21ripn/nDPI#78]
Hi 

I was not sure where to report this ntop/nDPI or here.. as it was not proper in that repo too. These were reported as warning while compiling make ndpi_network_list.c.inc which uses the nlist.pl to generate the yaml based on the ndpi_content_match.inc. I have attached the fixed file here.

**Team Viewer**

Warning: line  634: '159.122.189.48/21' is not network
```
/* Teamviewer 159.122.189.32-63 */
{ 0x9F7ABD30 /* 159.122.189.32 */, 21, NDPI_PROTOCOL_TEAMVIEWER },
```
should be

`{ 0x9F7ABD20 /* 159.122.189.32 */, 27, NDPI_PROTOCOL_TEAMVIEWER },`

**Viber has leading zeros in hex**

Warning: line  706: '1.44.48.64/23' is not network
Warning: line  707: '1.44.69.80/25' is not network
Warning: line  708: '2.46.138.52/28' is not network
Warning: line  709: '2.47.103.32/23' is not network
[ndpi_network_list.c.inc.txt](https://github.com/vel21ripn/nDPI/files/4371670/ndpi_network_list.c.inc.txt)

```
{ 0x012C30400 /* 18.195.4.0/23 */, 23, NDPI_PROTOCOL_VIBER },
{ 0x012C45500 /* 18.196.85.0/25 */, 25, NDPI_PROTOCOL_VIBER },
{ 0x022E8A340 /* 34.232.163.64/28 */, 28, NDPI_PROTOCOL_VIBER },
{ 0x022F67200 /* 34.246.114.0/23 */, 23, NDPI_PROTOCOL_VIBER },

```
It should be

```
{ 0x12C30400 /* 18.195.4.0/23 */, 23, NDPI_PROTOCOL_VIBER },
{ 0x12C45500 /* 18.196.85.0/25 */, 25, NDPI_PROTOCOL_VIBER },
{ 0x22E8A340 /* 34.232.163.64/28 */, 28, NDPI_PROTOCOL_VIBER },
{ 0x22F67200 /* 34.246.114.0/23 */, 23, NDPI_PROTOCOL_VIBER },
```

**STEAM**

Warning: line  628: '208.64.201.0/22' is not network

```
{ 0xD040C800 /* 208.64.200.0/24 */, 24, NDPI_PROTOCOL_STEAM },
{ 0xD040C900 /* **208.64.201.0/22 */, 22**, NDPI_PROTOCOL_STEAM },

```
I think they meant to enter **208.64.201.0/24, 24**  based on the previous entry?

**NETFLIX**
Warning: line  295: '209.148.214.135/21' is not network

`{ 0xD194D687 /* 209.148.214.135/21 */, 21, NDPI_PROTOCOL_NETFLIX },`

Not sure about this one.. The ASN is AS812 Rogers Communications Inc Canada? For now I removed it from the file.

**CLOUDFARE**

Warning: line   65: '141.101.88.0/19' is not network

I had to reorder it based on the AS13335. I combined what I could into a single entry based on the netmask.

 ```
 { 0x8D654000 /* 141.101.64.0/20 */, 20, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D654800 /* 141.101.72.0/22 */, 22, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D654C00 /* 141.101.76.0/23 */, 23, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D655000 /* 141.101.80.0/22 */, 22, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D655400 /* 141.101.84.0/23 */, 23, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D655E00 /* 141.101.94.0/23 */, 23, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D656000 /* 141.101.96.0/22 */, 22, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8D656400 /* 141.101.100.0/22 */, 22, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8d656800 /* 141.101.104.0/22 */, 22, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8d656C00 /* 141.101.108.0/23 */, 23, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8d656E00 /* 141.101.110.0/24 */, 24, NDPI_PROTOCOL_CLOUDFLARE },
  { 0x8d657000 /* 141.101.112.0/20 */, 20, NDPI_PROTOCOL_CLOUDFLARE },
```

```
root@r2:~/nDPI/src/lib# perl nlist.pl
host_protocol_list start
list end
ndpi_category_match category_match start
list end
Write ndpi_network_list_tor.yaml OK
Write ndpi_network_list_amazon.yaml OK
Write ndpi_network_list_whatsapp.yaml OK
Write ndpi_network_list_std.yaml OK

root@r2:~/nDPI/src/lib# make ndpi_network_list.c.inc
./ndpi_network_list_compile -o ndpi_network_list.c.inc ndpi_network_list_amazon.yaml ndpi_network_list_std.yaml ndpi_network_list_whatsapp.yaml ndpi_network_list_tor.yaml

```

**Comment by sharonenoch** [comment]
Copied the ndpi_network_list.c.inc. file instead of the ndpi_content_match.c.inc file. Correct file attached here

[ndpi_content_match.c.inc.txt](https://github.com/vel21ripn/nDPI/files/4371997/ndpi_content_match.c.inc.txt)

**Comment by sharonenoch** [comment]
Copied the ndpi_network_list.c.inc. file instead of the ndpi_content_match.c.inc file. Correct file attached here

[ndpi_content_match.c.inc.txt](https://github.com/vel21ripn/nDPI/files/4372033/ndpi_content_match.c.inc.txt)

**Comment by vel21ripn** [comment]
I fixed the network addresses. Changes are best made through .yaml files.

**Comment by sharonenoch** [comment]
Thanks.. Will update the yaml next time..
