### ISSUE TITLE
Microsoft Teams Support In ndpi-netfilter

### ISSUE THREAD

**Issue by Yuval-Ai** [vel21ripn/nDPI#81]
Hi!
First off, thank you very much for ndpi-netfilter.

Is support for MS Teams planned in ndpi-netfilter?

Seems that nDPI added it recently: [711ba99](https://github.com/ntop/nDPI/commit/711ba99eaa0cdc125975f4443239b0d66c46113d)

Thanks!

**Comment by vel21ripn** [comment]
This week I will not have time to work with this project.
If the patch is applied without errors, then I don’t see the reason why it will not work.
