### ISSUE TITLE
What branch should I use?

### ISSUE THREAD

**Issue by elico** [vel21ripn/nDPI#84]
I want to test nDPI but a bit confused what branch should I build and test against?

**Comment by k0ste** [comment]
[flow_info-3.2](https://github.com/vel21ripn/nDPI/tree/flow_info-3.2)

**Comment by vel21ripn** [comment]
I planned to make flow_info-3.2 the current branch in about a week.

**Comment by elico** [comment]
@k0ste @vel21ripn I am looking for compilation instructions on debian 10.

**Comment by k0ste** [comment]
> @k0ste @vel21ripn I am looking for compilation instructions on debian 10.

```
git clone ...
cd nDPI
git checkout flow_info-3.2
```

**Comment by elico** [comment]
@k0ste This is what I came up with:
https://github.com/elico/debian10-dev-ndpi-vel

It builds fine but I have not tested it on a VM.
