### ISSUE TITLE
Is it possible to match a lists of protocols as category?

### ISSUE THREAD

**Issue by elico** [vel21ripn/nDPI#87]
I was wondering about Protocol categories lists/matrix.
Maybe a command like then next would be possible:
`iptables -t mangle -A FORWARD -m ndpi --category p2p -j DROP`

For example match
VOIP:
* sip
* iax
* tuenti
..

P2P:
* directconnect
* fasttrack
* gnutella
* thunder
* bittorrent
* edonkey

GAMES:
* guildwars
* halflife2
* playstation
* starcraft
* steam
* warcraft3
* worldofkungfu
* worldofwarcraft
* xbox

MAIL:
* smtp
* smtps
* imap
* imaps
* pop3
* pops

**Comment by stasn77** [comment]
You may use fwmark for each category. For ex.:

voip="sip iax tuenti"
for p in $voip; do
    echo "$p 2" >/proc/net/xt_ndpi/proto
done
iptables -t mangle -A FORWARD -j NDPI --ndpi-id-p --set-mark
iptables -t mangle -A FORWARD -m mark --mark 0x2 -j DROP

**Comment by elico** [comment]
@stasn77 I am using marks for other purposes so it overlap one another.
Currently what I am doing using is:
`iptables -t mangle -A FORWARD -m ndpi --proto directconnect,fasttrack,gnutella,thunder,bittorrent,edonkey -j P2P`
