### ISSUE TITLE
Issue installing nDPI + netfilter. iptables v1.6.1: unknown option "--youtube"

### ISSUE THREAD

**Issue by alamgirqazi** [vel21ripn/nDPI#88]
Hi, I'm following the commands from https://github.com/vel21ripn/nDPI/blob/flow_info-3.2/ndpi-netfilter/INSTALL. Everything worked well however when I try to block a protocol, it gives an error.

 ```sudo iptables -A INPUT -m ndpi --youtube -j DROP```

![image](https://user-images.githubusercontent.com/13376173/86778804-3966d000-c074-11ea-98ba-a662b737d243.png)

What could be the possible issue ? Thanks

**Comment by vel21ripn** [comment]
```
iptables -A INPUT -m ndpi --proto youtube -j DROP
```

This is a limitation of iptables

**Comment by alamgirqazi** [comment]
1. Thank you Vitaly @vel21ripn. Can you elaborate further ? I had this working for earlier versions of nDPI and Netfilter. Do you think its because of updates in linux kernel ?

2. Also, how can I block Youtube or any other protocol using this ?

3. I have iptables v1.6.1 but the latest is 1.8.x, that could be an issue ? 

Thank you
