### ISSUE TITLE
xt_ndpi: Unknown symbol nf_ct_destroy (err 0) [solved]

### ISSUE THREAD

**Issue by BenSchweikert** [vel21ripn/nDPI#9]
Hi,
I build the netfilter modules for my firewall distribution. Basically it is compiling the kernel modules. I am using Kernel 4.9.13 at the moment without the ndpi kernel patches. When I try to load the module, I get a 
"xt_ndpi: Unknown symbol nf_ct_destroy (err 0)" 
error in dmesg. 

Building and loading with these sources is working: https://github.com/betolj/ndpi-netfilter
But I had a kernel crahs, did not investigate any further on this. 

Any idea why the nf_ct_destroy error occures, as far as I can see, it is part of the netfilter core.

BR 
Ben

**Comment by elico** [comment]
@BenSchweikert what OS are you using?

**Comment by BenSchweikert** [comment]
It is called ipfire.org (x86_64) with a costum build kernel from my side. Basically it is a Linux From Scratch with its own building framework.
Kernel config: 
http://git.ipfire.org/?p=people/arne_f/ipfire-2.x.git;a=blob_plain;f=config/kernel/kernel.config.x86_64-ipfire;hb=refs/heads/kernel-4.9

Additional Kernel Patches:
grsecurity-3.1-4.9.13-201703052141.patch.xz
linux-4.9-imq.diff
linux-4.9.13-layer7.patch

I do not even know where to start looking for a problem, all mentioned needed kernel configs are enabled.

**Comment by vel21ripn** [comment]
Yes. nf_ct_destroy is part of the netfilter core. The minimum requirements for the kernel configuration (without ndpi kernel patch)
```
CONFIG_NF_CONNTRACK=m or y
CONFIG_NF_CONNTRACK_LABELS=y
CONFIG_NETFILTER_XT_MATCH_CONNLABEL=m
```

**Comment by BenSchweikert** [comment]
yes I know, that was the part of my message wiith "needed kernel configs". Here an extract of the kernel config:
```
CONFIG_NF_CONNTRACK=y
CONFIG_NF_CONNTRACK_LABELS=y
CONFIG_NETFILTER_XT_MATCH_CONNLABEL=m
```

**Comment by vel21ripn** [comment]
```
grsecurity-3.1-4.9.13-201703052141.patch.xz
linux-4.9.13-layer7.patch
```
Can you give a link to these patches?

**Comment by BenSchweikert** [comment]
Layer7: http://git.ipfire.org/?p=people/arne_f/ipfire-2.x.git;a=blob_plain;f=src/patches/linux/linux-4.9.13-layer7.patch;hb=refs/heads/kernel-4.9
GRSecurity: https://beert.de/grsecurity-3.1-4.9.13-201703052141.patch.xz

**Comment by vel21ripn** [comment]
Theoretically, these patches should not create such problems.
```
grep nf_ct_destroy System.map
```
is empty ?
How did you build the module ?
Did you build the module already on the running 4.9.13 kernel?
To build with a specific (non-current) kernel, you need to use "cd nDPI/ndpi-netfilter && make KERNEL_DIR =..."

**Comment by BenSchweikert** [comment]
```
grep nf_ct_destroy System.map-4.9.13-ipfire                                                                                                         
ffffffff81198e40 D nf_ct_destroy 
```
No it is a chroot as far as I can see at the building system. I will try to rebuild the ndpi module with the kernel_dir option. 

Here is an extract of the building script:
```
        cd $(DIR_APP)/ && ./autogen.sh                                                                                                                                  
        cd $(DIR_APP)/ && ./configure \                                                                                                                                 
                                --prefix=/usr \                                                                                                                         
                                --sysconfdir=/etc                                                                                                                       
        cd $(DIR_APP)/ndpi-netfilter/ && make  $(MAKETUNING)                                                                                  
        cd $(DIR_APP)/ndpi-netfilter/ && make modules_install                                                                                                           
        cd /usr/src/linux && make modules_prepare 
```

**Comment by BenSchweikert** [comment]
Building with KERNEL_DIR=.. did not change anything.

**Comment by elico** [comment]
@BenSchweikert Can I reproduce the development environment in some way?
I wrote a dockerfile for OepnSUE\Debian\Ubuntu and Willing to give a shot for a one to ipfire.
If there is a VM I can build it's also good to try and reproduce on a regular kernel compared to a modified one.

**Comment by BenSchweikert** [comment]
@elico There does not exist a pre defined docker image or VM, but you can easily create the dev. env.:

```
git clone git://git.ipfire.org/people/arne_f/ipfire-2.x.git
git checkout -b kernel-4.9 -t origin/kernel-4.9
./make.sh --target=x86_64 downloadsrc
./make.sh --target=x86_64 gettoolchain
./make.sh --target=x86_64 build      # starts building process
./make.sh --target=x86_64 shell       # puts you inside the chroot env.
```

For an i5 with SSD it takes 2-3h for compiling. This one is without nDPI. You can put it into the "cache" dir. Inside the Chroot env go to /usr/src/ there is a link into cache dir and you can build it.

**Comment by BenSchweikert** [comment]
Kernel is compiled with # CONFIG_UNUSED_SYMBOLS is not set.. hopefully that is the problem.
Currently rebuilding the kernel.

**Comment by BenSchweikert** [comment]
Eureka!
Indeed the problem was CONFIG_UNUSED_SYMBOLS was not set. Now the module is loading. I will test it now

**Comment by elico** [comment]
@BenSchweikert Great!!!
I would be happpy if it would be possible to try and build a docker containser.
Basically I need only the chroot tar file in order to have a full dev docker container.
I will be in touch with you directly to see how to make it work.
Docker compared to a VM works\compiles 500% faster...

**Comment by BenSchweikert** [comment]
@elico Alright, I will tar all you need. 

These packages are needed for ubuntu: git-core, g++, realpath, patch, byacc, make, python-urlgrabber, autoconf, automake, build-essentials

The Build Env can be found here: https://beert.de/ipfire-2.x-docker.tar.xz

Go into the ipfire-2.x-docker directory and execute ./make_x86_64.sh to start the build process. The chroot is in ./build

**Comment by elico** [comment]
@BenSchweikert can you contact me directly via email regarding the docker?
eliezer@ngtech.co.il

**Comment by vel21ripn** [comment]
@BenSchweikert Thanks for the solution found.
I corrected the section on the requirements for the kernel.

**Comment by elico** [comment]
@BenSchweikert just so it would be publically avaliable.. the basic docker skeleton for ipfire build:
https://gist.github.com/elico/7c0c008e70431f1a6bb4b16b794f0eb3
