### ISSUE TITLE
Module not loading on 32bit ARM(RPI 4)

### ISSUE THREAD

**Issue by rstanislav** [vel21ripn/nDPI#91]
On last commit - modprobe: 
ERROR: could not insert 'xt_ndpi': Unknown symbol in module, or unknown parameter (see dmesg)

dmesg:

[  457.551340] xt_ndpi: no symbol version for module_layout
[  457.551395] xt_ndpi: loading out-of-tree module taints kernel.
[  457.563158] xt_ndpi: Unknown symbol __aeabi_uldivmod (err -2)

Last that i found works is commit 77d882638232fb9236123b50b9aac8bccc409ed9

Can't found how to debug to find where error is :(

Can you help me, please ?

**Comment by vel21ripn** [comment]
This is an integer division of 64-bit numbers.
I already found several places like this (flow-> packet.current_time_ms / 1000)
See 3bf4551e2234dc9f32a510ecd8760db29fd4c503

**Comment by BrainSlayer** [comment]
@vel21ripn there are in kernel helper functions for 64 bit divisons which help you do work around these compiler generated symbols

**Comment by rstanislav** [comment]
It loads now with trunk version, but crashes kernel =(

**Comment by vel21ripn** [comment]
I don't know how to fix this situation yet. It is necessary to determine in what place the crash occurs.
I do not have platforms other than x86 and x86_64 and I do not know the specifics of ARM platforms.
I know xt_ndpi ran successfully on mips64

**Comment by vel21ripn** [comment]
In a couple of days I will have the opportunity to experiment with RPI4.
What distribution do you have on PRI4?

**Comment by rstanislav** [comment]
Raspbian(debian buster) with 5.4 kernel (trunk git version).

**Comment by BrainSlayer** [comment]
@rstanislav can you show me the crashlog?

**Comment by vel21ripn** [comment]
I built nDPI without any problems with kernel 5.4.51-v7l.
The only additional thing I did was rebuild the kernel. I don't know how to build a kernel module without a compiled kernel.
```
Linux raspberrypi 5.4.51-v7l-x1+ #1 SMP Sun Jul 26 15:52:17 MSK 2020 armv7l GNU/Linux

[Tue Jul 28 17:14:33 2020] xt_ndpi v1.2 ndpi 3.3.0-2681-3bf4551e IPv6=YES debug_message=YES
                            BT: hash_size 0k, hash_expiation 0 sec, log_size 128kb
                            sizeof hash_ip4p_node=32 id_struct=240
                            flow_struct=1488 packet_struct=736
                              flow_tcp_struct=84 flow_udp_struct=36 int_one_line_struct=8
                            ndpi_ip_addr_t=16 ndpi_protocol=4 nf_ct_ext_ndpi=152
                            flow_info=112 spinlock_t=4  NF_LABEL_ID 6
```

**Comment by BrainSlayer** [comment]
> I built nDPI without any problems with kernel 5.4.51-v7l.
> The only additional thing I did was rebuild the kernel. I don't know how to build a kernel module without a compiled kernel.
> 
> ```
> Linux raspberrypi 5.4.51-v7l-x1+ #1 SMP Sun Jul 26 15:52:17 MSK 2020 armv7l GNU/Linux
> 
> [Tue Jul 28 17:14:33 2020] xt_ndpi v1.2 ndpi 3.3.0-2681-3bf4551e IPv6=YES debug_message=YES
>                             BT: hash_size 0k, hash_expiation 0 sec, log_size 128kb
>                             sizeof hash_ip4p_node=32 id_struct=240
>                             flow_struct=1488 packet_struct=736
>                               flow_tcp_struct=84 flow_udp_struct=36 int_one_line_struct=8
>                             ndpi_ip_addr_t=16 ndpi_protocol=4 nf_ct_ext_ndpi=152
>                             flow_info=112 spinlock_t=4  NF_LABEL_ID 6
> ```

you dont need the compiled kernel, but you need the kernel config and the kernel source since the kernel source and buildsystem is required for compiling. of course the config must fit to the running kernel and the compiler version should be identical too in best case
