### ISSUE TITLE
Is there a recommended way to update the IP lists seamlessly in a running system?

### ISSUE THREAD

**Issue by sharonenoch** [vel21ripn/nDPI#92]
I already have the xt_ndpi.ko driver loaded in my system and rules set for matching applications etc based on a code base from a month or more ago.. I was looking to update just the IP lists as I see updates to the YAML files from then..

Is there a way to push those updates alone, seamlessly, or would I need to recompile the driver and reload the ndpi driver and apply the rules again?

**Comment by vel21ripn** [comment]
Protocol information can be added and changed via /proc/net/xt_ndpi/{proto,ip_proto,host_proto} without modifying the module. Only the removal of protocols is not implemented.
See ndpi-netfilter/INSTALL "procfs files"

**Comment by sharonenoch** [comment]
Thank you. Went through the INSTALL file. Will try the procfs option to update.
