### ISSUE TITLE
Compatibility with original ndpi source

### ISSUE THREAD

**Issue by alrferreira** [vel21ripn/nDPI#93]
Hello people. Congratulations on the project. Its code has worked very well with iptables.
I have a question and would like your help. Compared to the original nDPi source (https://github.com/ntop/nDPI), what version are you on?

**Comment by vel21ripn** [comment]
Based on "dev" branch.
I am trying to keep up with the "dev" branch by more than 1 month.

**Comment by alrferreira** [comment]
Very good!
The category of protocols "IoT / Scada" were added yesterday in the root of nDPi, if you can update it will help me a lot.
Please give me more information on how to make financial donations for your project.

**Comment by vel21ripn** [comment]
ndpi-iptables does not use protocol categories. 
Mark and mask are used to group the protocols (see ndpi-netfilter/INSTALL p. 4).
The mark can be used to mark a packet (analogue -j MARK) or for classification (analogue -j CLASSIFY)
IoT/Scada is 3 protocols: Modbus, DNP3, IEC60870

**Comment by alrferreira** [comment]
Yeap.
Is your code up to date with Modbus and DNP3?

PS: Please give me more information on how to make financial donations for your project.
