### ISSUE TITLE
question about /proc/net/xt_ndpi/proto

### ISSUE THREAD

**Issue by didgaudin** [vel21ripn/nDPI#94]
hello,
do you think it is possible to have the command del_custom to remove custom protocol added by the command add_custom on the proc file system ?

**Comment by vel21ripn** [comment]
Not. Removal is too complex and resource-intensive operation.
The file /proc/net/xt_ndpi/host_proto must be cleared entirely with the "reset" command and loaded without unnecessary protocols.
The file /proc/net/xt_ndpi/ip_proto allows deletion of addresses for protocols.
Complete deletion of the created protocol is possible only by unloading the module.

IMHO libndpi still doesn't know how to delete user-created protocols.
