### ISSUE TITLE
not working in kernel 4.19.146 

### ISSUE THREAD

**Issue by mhkndo** [vel21ripn/nDPI#95]
Hello @vel21ripn,

I'm trying to use ndpi-netfilter in a 4.19.146 version kernel linux in a virtualbox and it is not working. 

in my host pc I've ubuntu 16.04 with 4.15.96-generic kernel 

in both pc's kernel these flags are set:
CONFIG_NF_CONNTRACK=m or y
CONFIG_NF_CONNTRACK_LABELS=y
CONFIG_NETFILTER_XT_MATCH_CONNLABEL=m
CONFIG_UNUSED_SYMBOLS=y

When I call iptables with command "sudo iptables -I INPUT -m ndpi --proto facebook -j REJECT" in host linux I see that it is blocking facebook. 
However, when I call the same command from vm linux (4.19.146) it is not blocking facebook.

So any suggestions? How do you check if it is working?

ps: both kernel versions doesn't have the kernel patches

**Comment by vel21ripn** [comment]
"iptables -I INPUT" filters packets addressed to the host.
To filter packets addressed to the virtual machine, you need to use FORWARDING and do not forget about net.bridge.bridge-nf-call-iptables = 1

**Comment by mhkndo** [comment]
Hi @vel21ripn, thanks for answer,

>"iptables -I INPUT" filters packets addressed to the host.

I'm calling this command in the vm, I want to do filtering in the virtual machine, not in the host. so when I enter command "iptables -I INPUT" in vm, it is effective on packets coming to vm right?

>net.bridge.bridge-nf-call-iptables = 1 

setting it to "0" on host machine is not changing anything.

by the way I'm trying to add ndpi-netfilter to vyos 4.19.146. Build is ok, kernel module is installed with no problem however, it is not working as in the host machine. Any other suggestions?

**Comment by mhkndo** [comment]
Hi @vel21ripn I've solved the problem. it was because off empty conntrack table.
