### ISSUE TITLE
Bittorrent detection not working properly

### ISSUE THREAD

**Issue by ananas77777** [vel21ripn/nDPI#96]
Using the rules below, I can detect like 20% only of the traffic as bittorrent. However, Ntopng detects nearly 100% of the traffic.

*mangle
-A PREROUTING -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A POSTROUTING -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A POSTROUTING -m mark ! --mark 0x0 -j ACCEPT
-A POSTROUTING -m mark --mark 0x0 -m ndpi  --proto bittorrent  -j MARK --set-xmark 0x1/0xffffffff
-A POSTROUTING -j CONNMARK --save-mark --nfmask 0xffffffff --ctmask 0xffffffff
*filter
-A INPUT -m mark --mark 0x1 -j ACCEPT

Any help would be appreciated.

**Comment by vel21ripn** [comment]
Traffic must be inspected in both directions.
Try adding a rule:
```
iptables -A PREROUTING -m ndpi --any
```

**Comment by clebig** [comment]
That will not work ;-) table missing.

Le mer. 7 oct. 2020 à 10:22, Vitaly Lavrov <notifications@github.com> a
écrit :

**Comment by ananas77777** [comment]
Thanks for the feedback guys. Looks like moving the rule into mangle prerouting does a much better job than using the connmark. It's currently detecting around 98% of the packets.
