### ISSUE TITLE
skbuff.h No such directory or file

### ISSUE THREAD

**Issue by fet4** [vel21ripn/nDPI#97]
cd  ndpi-netfilter
make
...
grep: /lib/modules/4.19.0-11-amd64/build/source/include/linux/skbuff.h: Нет такого файла или каталога
...

Но он находится в другом месте 
 find / -name "skbuff.h"
/usr/src/linux-headers-4.19.0-11-common/include/linux/skbuff.h

Как указать путь для make ?

**Comment by vel21ripn** [comment]
Для тебя оно никак не влияет на сборку.
Нужно выкинуть эти 3 строки.
