### ISSUE TITLE
Question about flow features

### ISSUE THREAD

**Issue by jason416** [vel21ripn/nDPI#98]
Hello @vel21ripn ,
I am using flow feature flowing the instructions in FLOW_INFO.txt, which says:
>
>An example for sample traffic passing only through a specific network
>interface eth1 :
>	iptables -t mangle -A PREROUTING -m ndpi --all
>	iptables -t mangle -A OUTPUT -m ndpi --all
>	iptables -t mangle -A PREROUTING -i eth1  -m ndpi ! --error -j NDPI --flow-info
>	iptables -t mangle -A POSTROUTING -o eth1 -m ndpi ! --error -j NDPI --flow-info
>

I tried only add these line below, It seems to  works fine.
```
iptables -t mangle -A PREROUTING -i eth1  -m ndpi --all -j NDPI --flow-info
iptables -t mangle -A POSTROUTING -o eth1 -m ndpi --all -j NDPI --flow-info
```

Does line 1 and 2 which without NDPI target necessary? and I wonder why use `! --error` but not '-all'.

**Comment by vel21ripn** [comment]
Two conditions must be met:
1. through "-m ndpi" traffic must pass in both directions.
2. "-m ndpi" must be used before "-j NDPI --flow-info"
   This is possible within one command "iptables ... -m ndpi --all -j NDPI --flow-info"

Everything else can be done as you like.

You can use --all.
If the packet went through "-m ndpi --all" earlier, then "-j NDPI --flow-info" can be used without "-m ndpi ..."

**Comment by jason416** [comment]
Hi @vel21ripn, Thanks for reply! 
And another question is that, the flow seems to be less than flow in interface via ifconfig.
Is it because this kmod was in netfilter and can not count packets below L3?

**Comment by vel21ripn** [comment]
Some time ago I was comparing the traffic counters flow_info and tcpdump.
If tso, gro, gso, sg, lro are disabled on the network interfaces, then the accuracy was 100%.
If you enable tso, gro, gso, sg, lro, then there will be a discrepancy in the number of packages (less) and a slight difference in the amount of data (less).
If you have enabled tso, gro, gso, sg, lro, then it is advisable to load the module with parameter "mtu = 64000"

**Comment by jason416** [comment]
Got it, Thanks for your help! Now I will close this issue.
