### ISSUE TITLE
Module crashes with the vm_alloc error

### ISSUE THREAD

**Issue by chirayu-patel** [vel21ripn/nDPI#99]
I am using OpenWRT based Access Point

root@OpenWrt:~# uname -a
Linux OpenWrt 4.4.60 #99 SMP PREEMPT Thu Nov 12 08:51:24 UTC 2020 armv7l GNU/Linux

When applying the latest module (version 3.2 with the commit id : b3fa670) - getting the following error in dmesg.

vmap allocation for size 589824 failed: use vmalloc= to increase size.

Does it have anything to do with the increase in number of protocols ?? Not sure.

and when the traffic passes through the iptables rule, it crashes and the AP hangs. Need to reboot it

Version 2.8 is working perfectly fine..

Please help

**Comment by vel21ripn** [comment]
armv7l  - this is Raspberry PI 2?

I can try to build and load this module only on raspberry Pi4 (kernel 5.4/Raspbian).

**Comment by chirayu-patel** [comment]
No, the chipset is Qualcomm IPQ 4019.  Would you need further info to figure out the issue and why is it not working for the latest version ?

**Comment by vel21ripn** [comment]
What parameters are you loading the module with?
